### ISSUE TITLE
2.0: Add settings for the REST API

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1000]
We should make sure that the REST API is only exposed if people want it to be (and perhaps disabled by default).

- [x] Add a new global GravityView setting for REST API access. Default: Off
- [x] Add filters to modify REST API access
- [x] Add per-View setting, using the global default

**Comment by soulseekah** [comment]
Sure, should be a really easy thing. Disabled by default, definitely. Maybe even on a per-View basis?

**Comment by soulseekah** [comment]
Filter is called `gravityview/view/output/rest` can be set to false to override all settings.
Global setting and local setting added.

See f78c6aa

**Comment by zackkatz** [comment]
I'd like to have a "Disabled" globally, enabled per-View option. Right now, it's only enabled globally, disabled per-View.

How do you think we should handle that, @soulseekah?

**Comment by soulseekah** [comment]
Done. They only minor concern I have is that the routes are registered even if never used, so there's no way to disable the routes completely via the UI.

Maybe we should have 3 settings :D "enable", "soft disable", "hard disable"?
