### ISSUE TITLE
2.0: PHP 5.2.4 not failing gracefully when Extensions are running

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1006]
### 1. Missing `gravityview()` 

Extensions call `GravityView_Plugin::include_extension_framework()` to load in the extension framework. That calls `gravityview()`, which doesn't exist if you're not running 5.3+.

```Fatal error: Call to undefined function gravityview() in /app/public/wp-content/plugins/gravityview/gravityview.php on line 172```

So I wrapped in `if ( function_exists( 'gravityview' ) ) {`.

### 2. Missing `GravityView_Extension`

```Fatal error: Class 'GravityView_Extension' not found in /app/public/wp-content/plugins/gravityview-advanced-filter/advanced-filter.php on line 34```

Okay, so I switched `GravityView_Plugin::include_extension_framework()` to private, so that it woul fail the `is_callable()` check the Extensions make, thus requiring the Extension to load its own `GravityView_Extension` class.

### 3. Missing `GravityView_Compatibility` 

```Fatal error: Class 'GravityView_Compatibility' not found in /app/public/wp-content/plugins/gravityview-advanced-filter/lib/class-gravityview-extension.php on line 363```

Turns out the Extension classes call `GravityView_Compatibility` without checking to see if it exists:

```
self::$is_compatible = GravityView_Compatibility::is_valid();
```

So then I decided instead of continuing, I should ask Gennady if he had any ideas 😆

**Comment by zackkatz** [comment]
Note: some of these errors may only be reproducible if you upgrade by hot-swapping folders (not by activating/deactivating).

**Comment by soulseekah** [comment]
Specific steps to reproduce with specific plugins?

I'm compiling php5.2 now...

**Comment by zackkatz** [comment]
1. Run advanced filtering 1.x and GV 1.x on 5.2.x
1. Hot-swap GV folder to 2.0, so it remains active
1. Errors
