### ISSUE TITLE
Intermittently-failing test

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1009]
This test fails every so often, but when I re-run it, it works.

```
GVFuture_Test::test_widget_render
Failed asserting that '<div class="gv-table-view gv-table-container gv-table-multiple-container gv-container gv-container-149 gv-container-no-results">
<table class="gv-table-view">
	<thead>
				<tr>
			<th id="gv-field-246-16" class="gv-field-246-16"><span class="gv-field-label">Textarea</span></th><th id="gv-field-246-id" class="gv-field-246-id"><span class="gv-field-label">Entry ID</span></th>		</tr>
	</thead>
	<tbody>
					<tr>
								<td colspan="2" class="gv-no-results">
					<p>No entries match your request.</p>
				</td>
							</tr>
			</tbody>
	<tfoot>
		<tr>
			<th id="gv-field-246-16" class="gv-field-246-16"><span class="gv-field-label">Textarea</span></th><th id="gv-field-246-id" class="gv-field-246-id"><span class="gv-field-label">Entry ID</span></th>		</tr>
			</tfoot>
</table>
</div><!-- end .gv-table-container -->
<input type="hidden" class="gravityview-view-id" value="149">' contains "<strong class="floaty">GravityViewfoo</strong>".
/home/travis/build/gravityview/GravityView/tests/unit-tests/GravityView_Future_Test.php:5320
```
As seen here: https://travis-ci.org/gravityview/GravityView/jobs/376642808

![failing test](http://share.gravityview.co/QdRjOr+)

**Comment by zackkatz** [comment]
See https://travis-ci.org/gravityview/GravityView/jobs/376711796

**Comment by zackkatz** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/379762363

**Comment by zackkatz** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/396519760

**Comment by zackkatz** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/397567507

**Comment by soulseekah** [comment]
I ran the test in isolation hundreds of times on Travis, no luck. I'll add some debug code so we can see what happened. I've added some debug output so we can see what the View configuration was like in a fail state. btw the IDs are still 4-letters long, but the chances of a collision are very slim, I ran a test for half an hour using just calling `wp_generate_password` twice in a row and didn't get a single collision.

**Comment by soulseekah** [comment]
We just had a hit https://travis-ci.org/gravityview/GravityView/jobs/398756581

The output of /tmp/test.log should give us more hints.

**Comment by soulseekah** [comment]
The configuration seems fine, I ran it a couple of times and it worked fine. Something else is amiss...

It's not ID collisions, though. Also the widget ID (`'id'`) is the same in both cases, just means its' the same type of widget, irrelevant.

**Comment by soulseekah** [comment]
And we have an instant fail here: https://travis-ci.org/gravityview/GravityView/jobs/399736220

`View::$widgets` is simply empty... thoughts on what may be going on? Off the bat, perhaps the configuration is not being persisted. Need to dig deeper.

**Comment by zackkatz** [comment]
@soulseekah https://travis-ci.org/gravityview/GravityView/jobs/402047077

No, I have no idea what might be going on.

```
array (
  'View::$_gravityview_directory_widgets' => 
  array (
    'header_top' => 
    array (
      'Tm7q' => 
      array (
        'id' => '1QQH-widget',
        'test' => 'foo',
      ),
    ),
    'footer_right' => 
    array (
      'Qtp1' => 
      array (
        'id' => '1QQH-widget',
        'test' => 'bar',
      ),
    ),
  ),
  'Widget_Collection::from_configuration' => 
  GV\Widget_Collection::__set_state(array(
     'storage' => 
    array (
    ),
  )),
  'View::$widgets' => 
  GV\Widget_Collection::__set_state(array(
     'storage' => 
    array (
    ),
  )),
  'filters' => 
  array (
    'gravityview/view/configuration/widgets' => NULL,
    'gravityview/view/widgets' => NULL,
  ),
)
```

**Comment by zackkatz** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/408607964

**Comment by soulseekah** [comment]
Getting there ... https://travis-ci.org/gravityview/GravityView/jobs/411248497

The class somehow is non-existent. Looking at what class this is.

**Comment by soulseekah** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/411392109

The widget is not being registered at all. Some kind of non-deterministic caching where calling `new Widget` without storing its value is skipped? Probably not... continuing to debug.

**Comment by soulseekah** [comment]
We may be on to something, a huge amount of fails here: https://travis-ci.org/gravityview/GravityView/builds/411690201 see the commit :)

**Comment by soulseekah** [comment]
...Non-deterministic opcode optimization?

**Comment by soulseekah** [comment]
Reproduced locally. We're at the end of our journey...

**Comment by soulseekah** [comment]
So here's what basically happens: `in_array` is a non-strict equals check by default. That's sort of fine, until you start registering widgets with IDs starting with a number :)

One of the tests that runs before this one adds a widget with and ID of '1'. That's fine.
Then this test that failed would intermittently try to register with and ID starting with '1xxx'.
What happens is that registration of the Widget doesn't go through, because it things that '1xxx' is already registered ('1' from before, `in_array( '1xxx', array( '1', 'hello', 'world' ) ) => true`).

One 4 letter fix for a 3+ month goosechase. Glad it's over. I'll scan for unstrict uses of `in_array` all over our core :)

**Comment by zackkatz** [comment]
Simply amazing that all this was a weak `in_array()` check.

Do you think this ever caused real-world problems? Or just in our test suite?

**Comment by soulseekah** [comment]
Nope, we have noone naming their widget IDs with weird names ;) We're safe, just tests. But a great lesson (again) into `in_array` weakness ;)
