### ISSUE TITLE
[gravitypdf] Shortcode no longer working in 2.0

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1012]
> Hey. Just want to say that the custom content shortcode Gravity pdf does not work in the new version 2.0.1
> 
> Like a `[gravitypdf name="Test" id="5ae4352bae6d2" text="PDF" type="view"]`

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/577574795/14481?folderId=408730

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/577617799/14485?folderId=408730

**Comment by zackkatz** [comment]
The issue is GF PDF calls legacy API:

```
$gravityview_view = GravityView_View::getInstance();
$entry            = $gravityview_view->getCurrentEntry();
```

**Comment by soulseekah** [comment]
https://github.com/gravityview/GravityView/commit/90bb21273e5279e2d6288919a147f16fa4de0c2b should fix this, tested on single list, table, directory list, table.
