### ISSUE TITLE
DataTables missing "GravityView_Extension" fatal error when updating GravityView to 2.0.1

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1013]
> Hi I updated the plugin this morning and receiving the following error: 
> 
> Fatal error: Class 'GravityView_Extension' not found in /wp-content/plugins/gravityview-datatables/datatables.php on line 50

[HS#14484](https://secure.helpscout.net/conversation/577599050/14484/?folderId=408735)

**Comment by soulseekah** [comment]
After our morning fix with the _stub.php file gravityview@439058f9aa3a7765a98fe06a0ea218025f8a33ae (Nov 2017) fails with:

![image](https://user-images.githubusercontent.com/685880/39841292-b747cd9a-53fb-11e8-850b-8648e4721b24.png)

as expected. `GravityView_Extension` is loaded as a stub with ::$is_compatible set to `false`. More information required, what version of DT she had, what version of GV she had.

**Comment by zackkatz** [comment]
Asked customer for more details, she hasn't responded in 4 days. Closing for now.

**Comment by girmay** [comment]
This still happens btw if one deactivates gravity forms while all else is active (gravityviews and any installed extensions of gv)

**Comment by soulseekah** [comment]
Does not happen on latest develop for GV, DT:

![image](https://user-images.githubusercontent.com/685880/70546323-204e7d00-1b80-11ea-8f47-affa34fc3b3e.png)
