### ISSUE TITLE
Extension not compatible with this version of GravityView after update to Versión 2.0.1

### ISSUE THREAD

**Issue by despazzito** [gravityview/GravityView#1014]
Hello, I updated the plugin this morning and receiving the following error:

> The DataTables Extension is not compatible with this version of GravityView. Please update the Extension to the latest version.
> 
> The DIY Layout Extension is not compatible with this version of GravityView. Please update the Extension to the latest version.

I have a working Galactic License

**Comment by zackkatz** [comment]
Hi @despazzito - There should be updates available to those plugins (2.0.2 for DIY, and 2.2 for DataTables). If you don't see them on your site, go to Dashboard, click Updates, and then click the "Check Again" button. If that doesn't work, you can download from your Account page.

For support, please contact us at [support@gravityview.co](mailto:support@gravityview.co)—we don't normally provide support here.
