### ISSUE TITLE
Max execution time fatal error

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1024]
> Fatal error: Maximum execution time of 60 seconds exceeded in /[...]/wp-content/plugins/gravityview/future/includes/class-gv-template-field.php on line 204

That line is related to merging field-specific templates: https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-template-field.php#L204

See https://secure.helpscout.net/conversation/578880799/14566

**Comment by soulseekah** [comment]
Pretty sure the destructor is not being called because there's a circular reference in the object :(

![image](https://user-images.githubusercontent.com/685880/39956098-760c0c7a-55f3-11e8-986e-e4c6e4727114.png)

**Comment by soulseekah** [comment]
Addressed in https://github.com/gravityview/GravityView/commit/5c3f7068968f0a70a834e9c4c8cc4e0780546713

@zackkatz We need this pushed as an update as soon as possible, please :)

**Comment by zackkatz** [comment]
Fixed in 2.0.4
