### ISSUE TITLE
Duplicate .gv-list-view html class

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#1026]
`gv-list-view` class is on both the container and each entry.
https://github.com/gravityview/GravityView/blob/master/templates/views/list/list-header.php#L9
https://github.com/gravityview/GravityView/blob/master/templates/views/list/list-body.php#L29

Not sure if this was intentional. If so maybe add an additional default class to the entry? 
2.0 styled all my containers like entries. 😀

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995549112044139)

**Comment by soulseekah** [comment]
Thanks for opening the issue. This does seem to be valid, we'll investigate further and have fix ASAP.

:+1:

**Comment by zackkatz** [comment]
Yeah, it's valid—there are `.gv-list-container` and `.gv-list-multiple-container` classes for the container—I added this to be consistent with the other layouts' CSS usage.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/39949154-7f991df2-5592-11e8-95a3-c8ec7f1b7020.png)

This is in the deprecated template, it behaved the same as far as I can tell.

**Comment by zackkatz** [comment]
Yeah, that was in the entry loop, but not in the container. https://github.com/gravityview/GravityView/blob/tweak/edit-entry-calculation-fields/templates/list-header.php#L12

**Comment by zackkatz** [comment]
@m-e-h Well, it took three years, but this is fixed in 2.10 😄 

It's a "breaking change" but you're right that it makes sense to break. We don't change CSS selectors lightly!
