### ISSUE TITLE
Add a "Filter" search for the admin field picker

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1027]
This is an interim step before our Gutenberg support: we should make it easy to filter fields by adding a little search field in the tooltip:

![](http://share.gravityview.co/ofOafu+)

**Comment by mrcasual** [comment]
Implemented in https://github.com/gravityview/GravityView/commit/0af6ef80b3737f5ff60a64c9d190fd432d06344c

**Comment by zackkatz** [comment]
Added in 2.0.11!
