### ISSUE TITLE
Yoast SEO & Jetpack Social Share buttons block widget rendering

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#1035]
When the "Add sharing buttons to your posts" is switched on in the Jetpack Sharing settings, View Widgets aren't rendered on the /view/ page.

This only happens on non-embedded Views. If the View is embedded, widgets appear as they should.

Unselecting the View post-type and "Disable CSS and JS" in the Jetpack settings has no effect. Still no View Widgets.

Not sure what's happening but this is the only interesting thing I see when debugging while the Social Share module is active.

`[debug, GravityView_View->render_widget_hooks] Not rendering header_10588_widgets; already rendered`
`[debug, GravityView_View->render_widget_hooks] Not rendering footer_10588_widgets; already rendered`

I've tested on several sites and get the same results.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/581652959/14670

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/582455631/14695

**Comment by soulseekah** [comment]
Ask to try develop.zip, please?

**Comment by zackkatz** [comment]
@m-e-h Can you please install [the `develop` branch version](https://github.com/gravityview/GravityView/archive/develop.zip) and let us know if it fixes the issue for you? Thanks!

**Comment by m-e-h** [comment]
Sure, I'll be able to try it out a little later this evening.

Marty

**Comment by m-e-h** [comment]
That seems to have fixed it. I'm seeing Header and Footer Widgets with Jetpack sharing on or off.

**Comment by zackkatz** [comment]
Closed in ef3c16e3b1ef57188fdf61b81a8a13658d5e95c9
