### ISSUE TITLE
[gv_entry_link] now requires entry_id and view_id parameters to work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1062]
This breaks lots of Views out there which are using `[gv_entry_link]View details[/gv_entry_link]` only.

**Comment by soulseekah** [comment]
Adding the code into an entry custom content works fine for me without the parameters, how else is this being used?

**Comment by zackkatz** [comment]
[HS#15001](https://secure.helpscout.net/conversation/591091193/15001/)

@soulseekah The above ticket has multiple shortcodes embedded on a page

**Comment by zackkatz** [comment]
[HS#15021](https://secure.helpscout.net/conversation/591710520/15021?folderId=408735) - Edit and Delete links…

**Comment by zackkatz** [comment]
See [HS#593270289](https://secure.helpscout.net/conversation/590895693/593270289/) again, Multiple Views on a page, edit entry links

**Comment by zackkatz** [comment]
This seems fixed with 2.0.10, but #1100 still exists
