### ISSUE TITLE
 My actions and filters are not working 

### ISSUE THREAD

**Issue by keshav1990** [gravityview/GravityView#1073]
add_filter( 'gravityview_entries', 'neo_show_only_awaiting_list_item' ,1);
add_action( 'gravityview/approve_entries/updated', 'neo_send_email_on_entry_status_changed' ,1);
This is my code with custom function but it's not working anymore, none of filter is working i have placed those code in functions.php

**Comment by soulseekah** [comment]
Thanks for opening the issue. Please contact support@gravityview.co along with your license information for immediate assistance.

**Comment by zackkatz** [comment]
See [HS#15000](https://secure.helpscout.net/conversation/591078084/15000?folderId=408735)
