### ISSUE TITLE
Configure Codeception testing

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1075]
One of the reasons the 2.0 launch was a bit…not as smooth…as it should have been was that we didn't have visual testing tools. The code we were checking output the expected values, but there were visual changes that should have been caught but weren't. An easy example is that the sorting links were removed from the Table layout. That should have been caught.

We should use [core GF unit tests](https://github.com/gravityforms/gravityforms/tree/master/tests/acceptance-tests) as a starting point for creating a suite of our own acceptance tests.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995555127346950)

**Comment by soulseekah** [comment]
Guh @zackkatz :)

What's the action plan here?

Related: https://github.com/gravityview/Import-Entries/issues/183

**Comment by zackkatz** [comment]
@mrcasual I'd love to get this up and running, with very basic tests to start with. Reminder: you can start with how Gravity Forms does tests: https://github.com/gravityforms/gravityforms/tree/master/tests/acceptance-tests

**Comment by mrcasual** [comment]
@zackkatz [added](https://github.com/gravityview/GravityView/commit/4331c9714e69fc0a58d1e9174d0404b7feb27c8e).

**Comment by zackkatz** [comment]
@mrcasual Is the only way to do this with a hard-coded database?

**Comment by mrcasual** [comment]
@zackkatz That one particular test uses prepopulated data but nothing prevents us from creating a View and other objects as part of a test.
