### ISSUE TITLE
Support Chained Selects add-on

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1082]
> I am trying to display the individual select subfield values in a Chained Select Field... the values are appearing as a table with 2 rows. By selecting the individual subfields from within GravityViews, I would expect them to show as individual columns.
> 
> Eg a GF address field, can have individual subfields of Town, State etc that can be displayed individually in GV. But it seems like Chained Select subfields are not working the same.

We need to support Chained Select better overall.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995555168467983)

**Comment by zackkatz** [comment]
See [HS#15038](https://secure.helpscout.net/conversation/591944263/15038/?folderId=408730)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/790197340/19403/

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/55140127-25d27700-5159-11e9-808f-fa91404feb16.png)

They do show up as individual columns. Can haz confirm, plz?

**Comment by soulseekah** [comment]
> https://secure.helpscout.net/conversation/790197340/19403/

This client is doing dynamic value population, @rafaehlers. It doesn't work for any of the field types at all. We filter and sort by what is stored in the database, not whatever PHP overrides the entries to afterwards. So you're correct in suggesting that this can only be achieved by custom code, shouldn't be too difficult, but it will be much much slower.

Now, what we can do, @zackkatz, for dynamic value override support is have a checkbox that does filtering and sorting in PHP instead, which would work with overrides. We can open a separate issue for this feature :)

**Comment by zackkatz** [comment]
@soulseekah Please create a separate issue for the feature, including making note of what field settings would be needed in the View Configuration screen.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1291500676/29447

**Comment by zackkatz** [comment]
https://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/42263932-conational-field-in-advanced-filtering-on-search

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1523983694/34713

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1594348499/36235
