### ISSUE TITLE
?gvid being added when embedding a single shortcode/oEmbed

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1090]
**Describe the Issue**

We added `?gvid` every time to the Edit Entry and Delete Entry links, but for just Entry Link, it shouldn't add `?gvid`; it makes ugly URLs.

**This does not happen when using the `[gv_entry_link]` shortcode.**

--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [x] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[gravityview id="1234"]`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

**Comment by rafaehlers** [comment]
But we need ?gvid when we have two Views on the same page. Also, if one of the Views has a Ratings link and you click on it, it won't work, unless you use ?gvid

Example:

https://website.com/client-reviews/entry/1239/?gvid=55814/#gv-entry-reviews
