### ISSUE TITLE
Entry Link field still not pointing to correct URL when embedding View

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1100]
> As an FYI, using the Link to Entry widget is still embedding the single-view on the current page rather than navigating to single-view url.

Related to #1062

See [HS#15001](https://secure.helpscout.net/conversation/591091193/15001?folderId=408730)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995555922280591)

**Comment by rafaehlers** [comment]
This issue doesn't make sense. The user was using the `[gv_entry_link]` inside a Custom Content widget, not a field. I've just tested and the shortcode doesn't run, which is correct.
