### ISSUE TITLE
You are not allowed to view this content.

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1103]
The user is seeing that message when trying to: 

`[embed]http://website.com/?gravityview=72&entry=467[/embed]` in a WordPress Post

GV 2.0.10
DT 2.2.21
Adv Filter 1.22

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/599826407/15407?folderId=408730

**Comment by zackkatz** [comment]
Fixed in https://github.com/gravityview/GravityView/commit/6290577b8ac5b34fae50ca1a55d0f99546bddc20
