### ISSUE TITLE
A conflict with Divi theme

### ISSUE THREAD

**Issue by ahmmetwally** [gravityview/GravityView#1111]
**Describe the Issue**
Hi there,
After installing the GravityView plugin, I got an issue as shown in the attached picture.
Briefly, there are imperfections at the end of the custom post of the GeavityView.
Would you please help to get this issue resolved?

![issue_with_gravityview_plugin](https://user-images.githubusercontent.com/22862338/41776646-e1421bd8-7628-11e8-870e-650f1617b66c.png)

Also, it has another impact, please see the other photo for another issue of the same plugin.

https://i.imgur.com/TQ6nKvn.png

Thanks
--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [ ] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[replace me]`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [ ] No

**If yes, please drag a screenshot below:**

**Comment by zackkatz** [comment]
Try turning off "No-Conflict Mode" setting in GravityView.

If that doesn't work, we don't provide support here; please send an email to support@gravityview.co. Thanks!
