### ISSUE TITLE
Field merge tags are evaluated to null (disappear) in field Custom Labels

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1117]
Merge Tags aren't being replaced in Custom Labels for any templates.

- DataTables Single Entry
- Table single entry
- List multiple entry & single entry
- Happens with joins and no joins

@soulseekah When addressing this, please also test with joins; for example, in `Entry_Table_Template::the_entry()`, the `$form` that is passed just uses `$this->view->form` instead of referencing the current entry's form.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/607246399/15580/?folderId=408730

**Comment by soulseekah** [comment]
Do not test joins for now, it's tracked in a separate ticket here https://github.com/gravityview/joins/issues/23

Otherwise this can be closed after testing and merge. The fix includes unit tests.
