### ISSUE TITLE
Edit Entry doesn't work in oEmbed

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1118]
**Describe the Issue**

When clicking Edit Entry from an oEmbed in a post, the "Layout has not been configured" warning will display.

**What should happen:**

Full edit entry form should display.

**What happens:**

The "not configured" warning displays:

![](http://share.gravityview.co/ySPsj+)
--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [ ] Embedded via shortcode
- [x] Embedded via oEmbed

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995556454664824)

**Comment by soulseekah** [comment]
Links in oEmbeds aren't clickable though, no? This is how my View oEmbeds look like:

![image](https://user-images.githubusercontent.com/685880/42133342-2684a5b2-7d31-11e8-9330-e55096e021b1.png)

What am I missing?

**Comment by soulseekah** [comment]
- Configure Single Entry to have an "Edit Entry" link
- Click the Edit Entry link
- Should go to

**Comment by soulseekah** [comment]
Related to https://github.com/gravityview/GravityView/issues/850

**Comment by zackkatz** [comment]
@soulseekah This is when embedding a single entry in oEmbed, not a Multiple Entry.

What I was describing is this:

- Create a post
- Embed a Single Entry via oEmbed `https://example.com/view/entry/123/`
- The Edit Entry link doesn't work

**Comment by soulseekah** [comment]
Single Entry oEmbed:

![image](https://user-images.githubusercontent.com/685880/69473210-37415100-0dc4-11ea-911c-dd5c2fd92514.png)

Directory oEmbed:

![image](https://user-images.githubusercontent.com/685880/69473051-fa288f00-0dc2-11ea-954a-461295776e65.png)

I think an even bigger additional issue is that the rendering is absolutely off, no line breaks, nothing, no HTML for directories.

**Comment by soulseekah** [comment]
> I think an even bigger additional issue is that the rendering is absolutely off, no line breaks, nothing, no HTML for directories.

We have no oEmbed handler for regular Views, that's why the default WordPress post handler comes in. Needs a new issue of its own. #1379 

Also related #1314, #1079

**Comment by soulseekah** [comment]
Our single entry oEmbed handler does not know how to handle edit links. The links are relative to the oEmbed.

Our options:

1. Make them work in an oEmbed context.
2. Make the edit entry link detect an oEmbed context and output a direct link to the View edit.

I think 1 is the better way to go. Thoughts?

**Comment by zackkatz** [comment]
Yep, 1 is better @soulseekah 

Directory embeds are not supported, just single entry and, ideally, edit.

**Comment by jlgrisham** [comment]
Edit Entry link working when single entry embedded in a post.
