### ISSUE TITLE
Joins fatal error - call to member function on null

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1119]
> Error: Call to a member function as_entry() on null in /app/public/wp-content/plugins/gravityview/future/includes/class-gv-template-field.php on line 337

Stack trace:
![](http://share.gravityview.co/bI2k9N+)

Setup:
![](http://share.gravityview.co/YItCIS+)
![](http://share.gravityview.co/lKbsDH+)

@soulseekah let me know if you need a DB dump

**Comment by soulseekah** [comment]
Looks like there's no joining entry perhaps, hmm. Send in the dump I'll look, thanks!
