### ISSUE TITLE
Rest API doesn't work with Advanced Filters

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1122]
Get any View and apply a "Created By Logged-in User" filter and the REST API will return:
`{"code":"gravityview-no-entries","message":"No Entries found.","data":null}`

Other filters do work as expected.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/609333185/15629

**Comment by soulseekah** [comment]
This is not a bug, sorry. In the WordPress REST API there's a security feature wherein all REST requests that depend on the user being set (`wp_get_current_user`, `is_user_logged_in`, `get_current_user_id`, etc.) will not work without setting the `X-WP-Nonce` header.

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

> For developers making manual Ajax requests, the nonce will need to be passed with each request. The API uses nonces with the action set to wp_rest. These can then be passed to the API via the _wpnonce data parameter (either POST data or in the query for GET requests), or via the X-WP-Nonce header. If no nonce is provided the API will set the current user to 0, turning the request into an unauthenticated request, even if you’re logged into WordPress.

Does this make sense?

Voting to close as not a bug @zackkatz

**Comment by rafaehlers** [comment]
Not a Bug, but an essential GV feature which is not working for our REST API. So we need to decide how to handle this.

**Comment by soulseekah** [comment]
Nonce security is very important. It's like asking us to turn off password-based authentication for /wp-admin/, it's a built-in feature of the REST API in WordPress that protects against CSRF vulnerabilities in a web-application.

Making this work the right way is following the documentation regarding authenticated requests to the API (i.e. posting a X-WP-Nonce header with the request). This should not be difficult.

I can give you a ticking time-bomb in the form of:

```
remove_filter( 'rest_authentication_errors', 'rest_cookie_check_errors', 100 );
```

But I'm on the verge of crying when writing this :(

**Comment by rafaehlers** [comment]
"Solved": https://docs.gravityview.co/article/468-rest-api
