### ISSUE TITLE
Add support for `X-WP-Nonce` authenticated requests to REST API 

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1123]
In order to allow for Advanced Filtering to work, we'll need to tell the REST API what user is making the requests. 

> Making this work the right way is following the documentation regarding authenticated requests to the API (i.e. posting a X-WP-Nonce header with the request). This should not be difficult.

See #1122

**Comment by soulseekah** [comment]
This is already supported out of the box in the WordPress REST API, what exactly do we have to do?

**Comment by zackkatz** [comment]
I don't know! I was just separating this from #1122 — what do you think we need to do?

**Comment by soulseekah** [comment]
Nothing, those are instructions for consumers of the API, they have to supply the header with the nonce. I have tested this, when supplying the header as per the documentation our endpoints work as expected :)

**Comment by zackkatz** [comment]
Okay, can you [update the docs](https://docs.gravityview.co/article/468-rest-api) with information about that process?

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/42473078-372100fe-83cc-11e8-9718-c1207f817042.png)

**Comment by zackkatz** [comment]
Great, thanks!
