### ISSUE TITLE
Unapprove an entry when its modified

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1129]
Add a setting to enable this:
When an entry is updated, change its approved status to "Unapproved"

- [x] Add a per-View setting whether to unapprove entries when edited via Edit Entry
- [ ] Implement the setting in Edit Entry
- [ ] Write a snippet plugin to enble updating status when editing via GFAPI and GF Edit Entry

**Comment by soulseekah** [comment]
Hey, hope you don't mind my snooping around here.

> Write a snippet plugin to enble updating status when editing via GFAPI and GF Edit Entry

Care to elaborate more on this, please? Like there's a setting already, what would the proposed snippet do?

**Comment by zackkatz** [comment]
@soulseekah That is to un-approve entries when edited with Gravity Forms' "Edit Entry" admin screen and GFAPI, as opposed to GV

**Comment by zackkatz** [comment]
Here's the code, for posterity: https://gist.github.com/zackkatz/36712b2fd3bfd65ed7a764d7a56decd1
