### ISSUE TITLE
Create a GV-branded loader/spinner featuring Floaty

### ISSUE THREAD

**Issue by mrcasual** [gravityview/GravityView#1132]
`Issue`: WP spinner is too minimalist and doesn't work well as a full-screen loader.

`Solution`: create a custom loader that will launch Floaty into an endless spinning mode.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995560258716006)

**Comment by zackkatz** [comment]
Geekbot has a great one we could use as a reference. I don't like the idea of Floaty himself spinning, but something spinning around Floaty would be great.

![](https://share.gravityview.co/ql1FJK+)

```
<div class="c-standup-form-submit-loading__content"><div class="c-standup-form-submit-loading__loading"><img class="c-image" src="/dashboard/b6d0026abaa7c61010443bae60503ceb.svg" alt=""><div style="display: block;" class="loader"><svg class="circular" viewBox="25 25 50 50"><circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10"></circle></svg></div></div></div>
```

```
.c-standup-form-submit-loading__content {
width: 300px;
min-height: 195px;
position: fixed;
top: 50%;
left: 50%;
-webkit-transform: translate(-50%, -55%);
transform: translate(-50%, -55%);
background: #fff;
padding: 25px;
border-radius: 5px;
}
```

**Comment by zackkatz** [comment]
In progress 🙂

https://www.fiverr.com/mostafamohamed2/create-pixel-art-scene-of-your-choice
