### ISSUE TITLE
Support Gravity Perks Nested Forms

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1136]
https://gravitywiz.com/documentation/gravity-forms-nested-forms/

I'll investigate what's needed and what's not currently working and I'll complete this issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995560289494085)

**Comment by zackkatz** [comment]
And how you'd like it to work, in a perfect world. For example, would it be essentially embedding `[gventry]`?  Or embedding a separate View? The more detail, the better 👍

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/815303526/19944?folderId=1210164

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/901275492/21510

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/66386144-5a59a200-e9ca-11e9-80fa-b30ff59f69d4.png)

Some good news perhaps.

**Comment by rafaehlers** [comment]
I'm checking that with @spivurno to confirm.

**Comment by spivurno** [comment]
Yes, Nested Forms now supports Gravity View. A Nested Form field can be included in any view including the edit view. 

The only limitation we are currently aware of is not being able to search/filter parent entries by values in their child entries.

**Comment by adizos** [comment]
There are more limitations. Images uploaded  through  Nested Forms upload Field doesn't show in a gravityview preview. Images on the Parent Form shows up in previews but not for Nested Forms
