### ISSUE TITLE
Embedded View in an embedded View not working

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1137]
**Describe the Issue**

When embedding a View inside an embedded View, the Entry Renderer class will not display the entry because "The requested entry does not belong to this View."

**Comment by soulseekah** [comment]
Unfortunately, all my local tests resulted in everything working as expected. Any chance to get a SQL dump for this? I tried this in directory context, single context, embedded on a page, embedded on a post. It works fine :(

**Comment by soulseekah** [comment]
@zackkatz ping

**Comment by rafaehlers** [comment]
Here's a ticket about this [HS#15925](https://secure.helpscout.net/conversation/623938349/15925/) and a video of me reproducing it: http://take.ms/6b1DP

The parent View must be embedded into a page. And the nested View won't show up in the Single entry page, just on the Multiple Entries page.

**Comment by soulseekah** [comment]
Please test and let me know.

Let's please not support views inside views inside views, otherwise we'll need to develop some sort of embed stack to track this stuff.

**Comment by soulseekah** [comment]
744f011 was reverted as it broke some very important things.

**Comment by soulseekah** [comment]
Regression fixed in e1c3d92, although I'm looking at performance a bit now and I think we'll have to do this stack-based. Most importantly I wrote the regression test so we'll not break these things again (and hopefully not others, either).

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/623938349/15925/
