### ISSUE TITLE
Exclude fields from search

### ISSUE THREAD

**Issue by Woklet** [gravityview/GravityView#1139]
Hi - we have a couple of forms with custom fields. I'd like to be able to exclude certain fields from searching. 

So, for example, if I have the field "Favourite Food" which contains the value "Hamburger" and I **also** have the field "Allergies" which **also** contains the value "Hamburger", I'd like to exclude the "Favourite Food" field from searching so that I only get results for entries that have "Hamburger" in the "Allergies" field.

I'm currently working off seeing if I can use the gravityview_fe_search_criteria filter to do this but I'm not sure if that's the right approach.

**Comment by soulseekah** [comment]
Thanks for opening the issue. Please contact support@gravityview.co along with your license information for immediate assistance.
