### ISSUE TITLE
GV support for the Survey Add-on misses the "Survey Total Score" column

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1140]
We must have the option to add this value as a field/column to add to the View:

![gv-survey-total-score](https://user-images.githubusercontent.com/1222472/43504189-d02ff11a-9538-11e8-8d70-99307fbc58e5.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995560792236448)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/631083683/16073

**Comment by soulseekah** [comment]
This can be done by using the `{survey_total_score}` merge tag. I don't think we need a separate field in the choices? Thoughts?

**Comment by rafaehlers** [comment]
@soulseekah where did you get that Merge Tag? I couldn't find it in the Gravity Forms KB articles.

**Comment by soulseekah** [comment]
@rafaehlers in the GF Survey plugin :)
