### ISSUE TITLE
+ Add All Fields should only add parent fields, not inputs

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1145]
**Affects only the [improvement/widget-field-add-logic](https://github.com/gravityview/GravityView/tree/improvement/widget-field-add-logic) branch.**

- Create a form with Address field
- Create a View connected to that form
- Click Add All Fields

**What should happen:** 

The "Address" field is added to the View Configuration.

**What does happen:**

The Address field is added, as well as each of the Address Field inputs (State, ZIP, Country, etc.).

![](http://share.gravityview.co/3VZVHe+)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995560815657600)

**Comment by rafaehlers** [comment]
Fixed! Tested on GV 2.13.1
