### ISSUE TITLE
Add "Page Size" widget so users can update # of entries per page from front-end

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1150]
Currently, the number of entries shown per page is set by the administrator. Most sites allow users to define the number of entries they want to see with a dropdown.

This has some vectors for abuse if there is a form with billions of entries, we would not want the user to be able to pass `?page_size=1000000000` and break the site, so we need to be careful.

- Create a GV Widget, with options for the page sizes, similar to how DataTables works
- Only filter the page size if the GV Widget is present
- Only allow one of the options defined in the Page Size widget
- Check everywhere in the code where `pagenum` is set, as well as `offset`
- Write a _bunch_ of tests

**Comment by zackkatz** [comment]
@soulseekah Any thoughts on issues that might arise?

**Comment by soulseekah** [comment]
We already allow search and filters with Widgets, allowing page size should be fine as the View is being output the Widget will filter the search criteria. We'll set a sane limit, like 100. It can be a dropdown like on DataTables, too, perhaps.
