### ISSUE TITLE
Entry cannot be displayed. Failed a criterium for ALL mode

### ISSUE THREAD

**Issue by pacerdev** [gravityview/GravityView#1151]
From the log:

... is not approved for viewing: [apply_filters_to_entry] Entry cannot be displayed. Failed a criterium for ALL mode

This is happening when using the shortcode in a do_shortcode() call.

**Comment by zackkatz** [comment]
@pacerdev We don't provide support here; please [contact support](mailto:support@gravityview.co). Thanks!
