### ISSUE TITLE
Allow searching a View based on approval status

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1152]
There's no way to search by approval status! Silly!

We do it in the Dashboard, we should enable this on the frontend.

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/662231002/16745?folderId=408730

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/706603307/17605?folderId=408735

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/48469058-c3f31f80-e7fe-11e8-8433-7aae6f2713c9.png)
