### ISSUE TITLE
GravityView widgets not rendering inside Elementor page builder pages

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1153]
The [Elementor page builder](https://wordpress.org/plugins/elementor/) pre-parses the HTML that generates the pages. The pre-parsing means that the widget actions are already triggered by the time we get to the content loop, so we don't re-render the widgets when it's time to render.

Similar to the WordPress SEO issue.

- [Discussion in Slack](https://gravityview.slack.com/archives/G727B06MB/p1537309788000100)
- [HS#16714](https://secure.helpscout.net/conversation/661200573/16714/)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995573961193409)

**Comment by soulseekah** [comment]
It seems to work fine with plain Elementor. But for that client it's the Elementor Modal Plugin that seems to break things. The page in that issue contains a PopBox with the form inside of it.

https://wordpress.org/plugins/modal-for-elementor/

**Comment by soulseekah** [comment]
Heh... the call is literally the same, they're at the same buffer depth level of 4... there's no way to differentiate the two calls, they're literally just made one after the other inside `the_content`. Eeek!

What do we do? A mechanism for the suppression of widget render protection? Something like:

![image](https://user-images.githubusercontent.com/685880/46016909-caa6c580-c0de-11e8-8017-2f27336aaf0a.png)

**Comment by soulseekah** [comment]
Related to #946

**Comment by rafaehlers** [comment]
This doesn't happen anymore. Tested on GV 2.13.1 and Elementor 3.4.4. Widgets show up fine.
