### ISSUE TITLE
Add `search_operator` shortcode argument

### ISSUE THREAD

**Issue by cliffordp** [gravityview/GravityView#1158]
Example: `[gravityview id="208" search_field="5" search_value="abc" search_operator="is"]`

Problem: The `search_operator="is"` part of that shortcode does not do anything *(but I'm requesting that it does).* By default, the query's `search_operator` is set to `'contains'` and therefore if the value is `"abcxyz"`, it _does_ appear in the results, but not if `search_operator="is"` would work.

**Describe alternatives you've considered**
Using the `gravityview_fe_search_criteria` filter instead of the shortcode.

**Comment by soulseekah** [comment]
This has been tested many times and works as expected. The `search_operator` has been a supported shortcode argument for ages. If it's still not working for you please contact support via https://gravityview.co/support/

**Comment by cliffordp** [comment]
@soulseekah OK, thanks, didn't see it documented at https://docs.gravityview.co/article/73-using-the-shortcode and it seemed an obvious one to add... guess the documentation just needs updating... I was just testing things out to see of GV will work for me. I'm guessing it will after playing with it a while, especially if this is available. I'll give it a closer look/testing. tyvm.

**Comment by soulseekah** [comment]
@zackkatz doc update due?

**Comment by zackkatz** [comment]
Yep, sorry about that, @cliffordp!

**Comment by zackkatz** [comment]
Updated.

**Comment by cliffordp** [comment]
Awesome. Thanks so much!
