### ISSUE TITLE
The Clear link from the Search Bar widget generates a JS error if the View is not a DT layout

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1164]
We should implement a check on the Clear link to prevent this from happening when not using a DataTables View.

![gv-search-bug](https://user-images.githubusercontent.com/1222472/46315549-215f4400-c5a4-11e8-9c76-a822c0ec43d2.jpg)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/668901633/16858

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/728943631/18147/

**Comment by mrcasual** [comment]
Fixed in https://github.com/gravityview/DataTables/pull/109
