### ISSUE TITLE
The Quiz Letter Grade is lost if Edit Entry does not contain all Quiz fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1166]
**Describe the Issue**

1. Assuming you have a form with one Single Input field and several other Quiz fields;
2. Set this form to Letter Grade on Form Settings > Quiz Settings;
3. Create a View, add all the fields and add the Quiz Letter Grade field;
4. Add just the Single Input field to your Edit Entry tab;
5. Edit one entry and change something on that Single Input field;
6. The Quiz Letter Grade is lost/erased unless you add all other Quiz fields to the Edit Entry page.

Test form attached.

Video of the bug reproduced: http://take.ms/FLSSI

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/677953811/17011/

**Comment by soulseekah** [comment]
Indeed. GFQuiz reevaluates the whole form on update and our cut-down forms would not be enough to recalculate the grade. Fixed. Please test `develop` and let us know.

**Comment by rafaehlers** [comment]
The fix didn't work. You can re-test here: https://debug.gravityview.co/blog/view/quiz/

**Comment by soulseekah** [comment]
Can you try https://github.com/gravityview/GravityView/commit/d0fd4b6e11d6f2ffab6e1c95c82c63c75a8b9389 please?

**Comment by rafaehlers** [comment]
@soulseekah that worked! :+1:  @zackkatz you can merge that one!

**Comment by soulseekah** [comment]
It's merged in develop. Issue will be closed in next release.
