### ISSUE TITLE
White label GravityView

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1168]
## User Feedback:

>Really wish you guys would consider NOT displaying all the license information in the admin panel settings. Its annoying to hear the clients complain they are being charged for an annual license fee that is x % of the total cost PLUS its a bit of a security issue i dont want other folks that might have admin to obtain my information - even if though I am capable of disabling the license here.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/687889358/17221/

**Comment by zackkatz** [comment]
This is better done with user capabilities. [Here's a doc](https://docs.gravityview.co/article/333-modifying-user-role-capabilities)

**Comment by soulseekah** [comment]
There are also a couple of admin whitelabel plugins out there that let you hide specific menus and whatnot.
