### ISSUE TITLE
Multi-column sorting of entries

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1172]
As a user with tabular data, I want to be able to sort by multiple columns (as you can do in common spreadsheet applications).

This should also be enabled in DataTables using the [Multi-column ordering functionality](https://datatables.net/examples/basic_init/multi_col_sort.html).

## Implementation

- In View settings: Convert the single field drop-down to a repeating dropdown, in the order of the sorting priorities.
- In the front-end, add JS so that the Table layout and DataTables layout work the same way: Shift-Click the column to sort by secondary field
- Support in the REST API

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995546064391834)

**Comment by zackkatz** [comment]
@soulseekah can you tackle the PHP, then assign the issue to @mrcasual so he can take over the JS work.

**Comment by soulseekah** [comment]
This would not be possible without a patch getting into `GF_Query` first :(
There's no support for multiple-column sorting yet.

We can hack it via a SQL query filter, of course until `GF_Query` supports multiple sorting functionality.

Thoughts? @zackkatz

**Comment by zackkatz** [comment]
How hard is the patch? @soulseekah

**Comment by soulseekah** [comment]
Not too hard (4-8 hours of work probably, with tests) from what I remember and what I read into from the latest version, but definitely something that might take some time to get into GF, they might put it towards GF 2.4. Might be quite a wait to get in. But the sooner we start the better I'm sure.

**Comment by zackkatz** [comment]
Let’s go for it. :100: @gennady

It’s a long-standing customer request.

**Comment by soulseekah** [comment]
Okay, for the UI the plan is the following:

## Configuration

`sort_field` and `sort_direction` become arrays.

`{"sort_field":[1,2],"sort_direction":["ASC","DESC"]}`

## URL Parameters

For sorting dynamically `sort` becomes multiple `sort[]` parameters, and `dir` becomes multiple `dir[]` parameters.

`/view/example?sort[]=1&dir[]=asc&sort[]=2&dir[]=desc`

The old non-array formats will still be supported, of course.

Thoughts and suggestions welcome.

**Comment by soulseekah** [comment]
Please reassign for some UI love. The groundwork is in the `feature/multisort` branch, works perfectly on simple examples.

`GF_Query` ended up not being touched, so we're good to go on a release ASAP :)
Needs hand testing as well, obviously. And DataTables should work with the same GET parameters.

**Comment by soulseekah** [comment]
`CAST AS DECIMAL`, see https://gravityview.slack.com/archives/CDSTQ9QQ0/p1541758525093800

**Comment by diegodelprado** [comment]
https://secure.helpscout.net/conversation/733887532/18246
