### ISSUE TITLE
Broken update user password via Edit Entry

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1175]
GF User Registration + GV Edit Entry

When updating a password field the cookies are inherently reset. But since we do this mid-page we get headers already output issues. Related problems to mid-page header output encountered here #698

https://secure.helpscout.net/conversation/695406713/17371/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995546025886746)

**Comment by soulseekah** [comment]
`wp_update_user` will force cookie clearing if it's supplied with a `user_pass` argument.

![image](https://user-images.githubusercontent.com/685880/47715775-d17ea600-dc51-11e8-8353-1e56ef7fcd0d.png)

**Comment by soulseekah** [comment]
I think this should better be left for EE 2.0. I looked through the code a bit more and while we can probably hack the processing step to run before output the implications of doing so might add up to a lot of new bugs and issues. Not sure I'd want to risk it. This needs a rewrite from the ground up.

**Comment by rafaehlers** [comment]
I can't replicate this anymore. Tested with GF 2.5.12, GV 2.13.1, and UR 4.8
