### ISSUE TITLE
wp_title is different from the the_title thus affecting SEO

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1176]
When embedding a View into a page, the title output on the `<title>` tag is different from the `<h1>` title.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995546021681044)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/699998411/17488/

**Comment by soulseekah** [comment]
This should be a documentation page somewhere. Can we write one and close? @zackkatz

**Comment by zackkatz** [comment]
Yes, can you write that doc, Gennady? It can be technical; ping me when it's ready and I can edit it.

**Comment by soulseekah** [comment]
https://secure.helpscout.net/docs/566dfabbc6979143615564bf/article/5dde1efe2c7d3a7e9ae47807/
