### ISSUE TITLE
Fields lists not refreshing on source change

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1178]
When changing the source for a View the fields lists are not changed and remain from the old source. It is necessary to save the page without fields to get the new ones.

`develop`

![edit-2](https://user-images.githubusercontent.com/685880/48064072-d86c6200-e1d7-11e8-9cc9-f55488cfe7a2.gif)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995544701401259)

**Comment by rafaehlers** [comment]
This doesn't happen anymore after the View editor refactor. Tested on GV 2.13.1
