### ISSUE TITLE
Allow single input text for some choices on Search Bar 

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1179]
For example:

![gv-entry-creator](https://user-images.githubusercontent.com/1222472/48136482-ea590e00-e286-11e8-8a96-7b102e42555a.jpg)

Entry creator, doesn't allow us to select "Text", so we can look for a name or part of an email.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995544725277960)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/702362636/17526/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/707522894/17622

**Comment by soulseekah** [comment]
Documented here: https://secure.helpscout.net/docs/566dfabbc6979143615564bf/article/5bec9aa104286304a71c4883

**Comment by soulseekah** [comment]
Backend support was definitely available since 16315491d

Probably just a matter of adding Text as a valid input. Needs a quick test.

**Comment by jlgrisham** [comment]
Text option for Entry Creator available now. Full and partial text searches working as expected.

**Comment by rafaehlers** [comment]
@soulseekah I don't have any special request for those at this moment.  What're the current criteria for picking which input types are available/can be done for each field?

**Comment by zackkatz** [comment]
@rafaehlers https://github.com/gravityview/GravityView/blob/a31172ea06ccab03b92c4f84834874ca37be4440/includes/widgets/search-widget/class-search-widget.php#L148-L176

**Comment by soulseekah** [comment]
Is this in a document somewhere? Doesn't seem to be in docs. Shall I throw something together?

**Comment by zackkatz** [comment]
@soulseekah Yes, please add a doc forthis

**Comment by soulseekah** [comment]
This is here https://secure.helpscout.net/docs/566dfabbc6979143615564bf/article/5df60b1d04286364bc92deac can be checked, finetuned and published. Thanks.

**Comment by zackkatz** [comment]
Nice article, @soulseekah ! Published.
