### ISSUE TITLE
check_entry_display does not account for strtotime support

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1185]
Moved from https://github.com/gravityview/Advanced-Filter/issues/58

It thinks that something like "last day of last month" is not valid and does not verify.

We have to fix and rid of check_entry_display for a more robust approach.

https://secure.helpscout.net/conversation/707220347/17613/

**Comment by soulseekah** [comment]
Actually everything for date fields (except date_created) was being checked as string. This fixes a handful of bugs with date fields.

No update to AF required.

**Comment by zackkatz** [comment]
Notified customer.
