### ISSUE TITLE
Survey Add-on: Support displaying Scoring values for Likert Fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1195]
At this moment in GravityView (version 2.1.1) there's no way to display the Scoring values for Likert field types:

![gv-survey-scoring](https://user-images.githubusercontent.com/1222472/49059925-5bd70d00-f1f2-11e8-8b24-e1ffd7bbc732.png)

Apparently, not even Gravity Forms has Merge Tag Modifiers for these fields: https://docs.gravityforms.com/survey/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995539800264349)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/716967130/17851/

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/GravityView/issues/1140

**Comment by soulseekah** [comment]
> Apparently, not even Gravity Forms has Merge Tag Modifiers for these fields

Seems like there are Merge Tags for this, just an FYI. But the issue still stands.

**Comment by pfkellogg** [comment]
Not sure if you are interested but here is link of rough video of my plugin that extracts glikerts for radar charting, line charting, disorder analysis and gauge scoring in a GravityView: https://www.youtube.com/watch?v=L1eNrvEUeMQ

**Comment by rafaelcabo** [comment]
> Not sure if you are interested but here is link of rough video of my plugin that extracts glikerts for radar charting, line charting, disorder analysis and gauge scoring in a GravityView: https://www.youtube.com/watch?v=L1eNrvEUeMQ

Hi, @pfkellogg  Could you please give info where to get your plugin, and an explanation about how the setting up works? Thanks in advance, Rafael

**Comment by pfkellogg** [comment]
Hi Rafael,

We are planning to release the plugin for sale this month, so I will make a
new video and keep you informed.

Thanks,
Patrick

**Comment by soulseekah** [comment]
I'm going to add something like "Show Score" setting for the field.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/65389254-e201a880-dd5c-11e9-86b3-cad05f07f5cf.png)

![image](https://user-images.githubusercontent.com/685880/65389260-fe054a00-dd5c-11e9-8d88-8d6c8898d69c.png)

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/998114679/23231

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1153583052/26753/

**Comment by zackkatz** [comment]
@bennemann There's a "show score" checkbox in the survey field

**Comment by bennemann** [comment]
The "show score" functionality doesn't work.

This [line](https://github.com/gravityview/GravityView/blob/d0aeec9798aa47b081600760312953c195905a9e/templates/fields/field-survey-html.php#L19) returns a meta value such as _glikertcol2691796c6_, so there's nothing to _explode_ and compare to the choices.

The score is displayed on the View as a letter of this meta value. 

Here's an example: 
[https://debug.gravityview.co/blog/view/test-survey-score/](https://debug.gravityview.co/blog/view/test-survey-score/)

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1512049842/34437/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1559561080/35512/
