### ISSUE TITLE
Convert search $_GET parameters to support Gravity Forms Web API format

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1200]
It doesn't make sense for GravityView and Gravity Forms to have competing URL parameter design.

There would be a back-compatibility layer, of course, to make sure our old queries still worked.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995539773940575)

**Comment by soulseekah** [comment]
One big issue: GF Web API does not allow to keep state for multiple views at a single endpoint, and multiple forms in a single view :) We need something more powerful. I'm thinking JSON-based. See #817
