### ISSUE TITLE
Unable to link to single entry when only one entry in a Multi_Entry

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1211]
If the Multi_Entry only has a single entry, the Single Entry screen will not render. The link will look like a single entry link, but GravityView knows that it's a Multi_Entry, so I doesn't know what to do.

This affects Edit Entry as well in #1210 

The issue is that `$request->is_single()` doesn't get triggered when all the forms requirements are not satisfied: https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-request.php#L121-L146

**Comment by soulseekah** [comment]
We also need to check:

- [ ] Delete Entry
- [ ] Notes
