### ISSUE TITLE
Add new 5.0 Custom Post Type labels

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1215]
> In WordPress 5.0, five additional labels have been made available for custom post types. These get passed in via the labels argument when using register_post_type(). The following labels are new:

item_published — The label used in the editor notice after publishing a post. Default “Post published.” / “Page published.”
item_published_privately — The label used in the editor notice after publishing a private post. Default “Post published privately.” / “Page published privately.”
item_reverted_to_draft — The label used in the editor notice after reverting a post to draft. Default “Post reverted to draft.” / “Page reverted to draft.”
item_scheduled — The label used in the editor notice after scheduling a post to be published at a later date. Default “Post scheduled.” / “Page scheduled.”
item_updated — The label used in the editor notice after updating a post. Default “Post updated.” / “Page updated.”

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995538252604293)

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/GravityView/issues/1268
