### ISSUE TITLE
Offer an option to redirect the user to a form when there are no entries

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1217]
At the moment, there's no appropriate way to achieve this functionality, unless creating a link to a page with the code provided here: https://docs.gravityview.co/article/51-modifying-the-text-displayed-when-there-are-no-entries

This is an old-time feature request from several users and a recurring one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995538261029163)

**Comment by soulseekah** [comment]
This can be solved with a link + javascript to do the redirection. We cannot output Location headers because we never know what Views are being output on the page upfront.

See the issues we had with After Edit Redirects, where we had to solve it by some JabbaScript magic.

**Comment by rafaehlers** [comment]
I was actually targetting displaying a form instead.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1285391847/29320

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1740361858/38817

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2151144139/46899
