### ISSUE TITLE
Support the official Gravity Forms Pipe Add-on

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1218]
This add-on lets you capture videos using your webcam, the problem is that GravityView doesn't output the video embed, just a link to the video file. Also, there's no way to create an oembed since that field Merge Tag does not return anything when used inside a Custom Content field.

https://www.gravityforms.com/add-ons/pipe-video-recording/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995538251082592)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/728177457/18129/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/846577493/20565/

**Comment by soulseekah** [comment]
Just so you know, Gravity Forms renders it as a link as well:

![image](https://user-images.githubusercontent.com/685880/65314331-ccdf1b00-db9e-11e9-820b-
b622ec75d510.png)

In progress.

**Comment by soulseekah** [comment]
Feel free to test and send feedback.
