### ISSUE TITLE
A Credit Card field set to "Force SSL" breaks Edit Entry on a non-https website

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1219]
Credit Card fields have an option to "Force SSL":

![gv-cc-ssl](https://user-images.githubusercontent.com/1222472/49899527-185fde00-fe43-11e8-9af6-b7bf1571f2b1.png)

When editing an entry in a View where the website is not HTTPS, an error occurs which breaks the whole page.

## Steps to reproduce
1) Install the Stripe add-on (attached) so you have access to the Credit Card field
[gravityformsstripe_2.5.4.zip ](https://github.com/gravityview/GravityView/files/2673563/gravityformsstripe_2.5.4.zip)

2) Import the form attached (remove the `.txt` extension)
[gravityforms-export-2018-12-12.json.txt ](https://github.com/gravityview/GravityView/files/2673566/gravityforms-export-2018-12-12.json.txt)

3) Create at least one record/entry. Here are test credit card numbers: https://stripe.com/docs/testing#cards

4) Create a very simple View with these two fields. Add a link to Edit Entry.

5) Access the View and click to Edit Entry on a non-SSL website.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995536788306336)

**Comment by soulseekah** [comment]
I don't think we should ever be displaying credit card fields in Edit mode.
Just like CAPTCHAs.

@zackkatz hmm?

**Comment by soulseekah** [comment]
The regular credit card fields are not editable. The Stripe addon is not editable either, you can only cancel a subscription via the Dashboard. https://docs.gravityforms.com/stripe-add-on/

We shouldn't display it on the edit fields.

P.S. Also, who the heck enables Force SSL on a non-HTTPS website? More importantly, who the heck uses a credit card form on a non-HTTPS website? :dancing_women:

**Comment by zackkatz** [comment]
@soulseekah can you add it to the field blacklist?
