### ISSUE TITLE
Potential header overflow with backlink cookies

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1221]
Backlink cookies linger for quite a while and on sites with many views the cookie header can become quite large hitting webserver configuration caps (Headers Too Large 494, 431 errors).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995536755476225)

**Comment by zackkatz** [comment]
Could be here: https://secure.helpscout.net/conversation/720282291/17960/

**Comment by rafaehlers** [comment]
Possible fix: https://gist.github.com/zackkatz/354a71dc47ffef072ed725706cf455ed
