### ISSUE TITLE
If the currently logged-in user edits the entry associated with his account he's logged out

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1225]
## Steps to reproduce
1. Create a form with a name, username, email and password fields.
2. Create a `Create User` feed in that form with the User Registration add-on
3. Create a simple View with a link to Edit Entry.
4. Embed that form and View into a page
5. Access that page while being logged-out
5. Register a new WordPress User within that form
6. Come back to that page to edit the entry

It doesn't matter if the Edit Entry page contains the password field or not, you'll be disconnected right after editing the entry.

Tested with:
GV 2.2.2
GF 2.4.3
UR 3.9.7

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995536741661454)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/730368375/18183

**Comment by soulseekah** [comment]
Closely related to https://github.com/gravityview/GravityView/issues/1175

**Comment by soulseekah** [comment]
I cannot reproduce. If the password field is not set nothing can log out out. Moreover, since output is already started (without extrinsic buffering) we cannot even log the user out really.

**Comment by soulseekah** [comment]
Client said it's working.
