### ISSUE TITLE
Add height / width setting to File Upload field settings

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1227]
When embedding an image on Multiple Entries, we set the size to be 250px (because of back-compat). Single entries have no size limit.

This requires lots of customization for what should be a simple thing: showing an image.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995535708411466)

**Comment by soulseekah** [comment]
Starting with width.

![image](https://user-images.githubusercontent.com/685880/66186018-d5991c00-e689-11e9-8eb7-c53604d2dbac.png)

Not confident regarding height, we don't have height as an attribute right now, do we add it?

**Comment by jlgrisham** [comment]
Custom width tested and working as expected.
