### ISSUE TITLE
\GV\Entry::from_field() seems wrong

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1228]
https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-entry.php#L226

This code doesn't make sense—it seems to be pointing to an old way of storing the entries.

This makes more sense to me:

```
return Utils::get( $this->entries, $field->form_id, Utils::get( $this->entries, $fallback, null ) );
```

And nowhere seems to use `$fallback` that I can see. Is it needed?

**Comment by soulseekah** [comment]
A `Multi_Entry` has array accessors that you access a specific entry by `form_id`.

https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-entry-multi.php#L116

There is no need to explicitly pick on `$this->entries` as the `offsetGet` methods will do it for us.

`$fallback` is needed to supply the main form for fields that don't have a form_id (think custom fields, etc.); the fallback is usually set to the main form in templates. Hope this makes sense.

What's the use case here? What did this come up in relation to?

**Comment by zackkatz** [comment]
@soulseekah Wouldn't the ancestors be accessed using `$entry->entries[ $form_id ]` rather than `$entry->{ $form_id }`?

I ran into this code while looking into why DataTables wasn't supporting Multiple Entries. I ended up fixing [it in the plugin](https://github.com/gravityview/DataTables/commit/8fdbd0c05108b6d2ad15e39a19de8a1b05c64e48), but I found this code and noticed $fallback isn't being used, and that the `$entry->entries` store doesn't appear to be used, either.

**Comment by soulseekah** [comment]
No, since implementations of `ArrayAccess` will get accessed as arrays inside `Utils::get`:

https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-utils.php#L80-L83

So that piece of code covered and tested and fine, overall. If you prefer to make it clearer I can do that, perhaps add some documentation for the future generations.
