### ISSUE TITLE
Combine Time field subfields into one for Sorting By

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1230]
When we have a time field on the form:

![gv-time-field](https://user-images.githubusercontent.com/1222472/50363154-9ada5300-0551-11e9-9d0b-7561cf6cc673.png)

We can't sort by the whole field:

![gv-time-fields-split](https://user-images.githubusercontent.com/1222472/50363399-93677980-0552-11e9-84e3-6743b3570e2e.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995535700909212)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/732265634/18225

**Comment by soulseekah** [comment]
As a sidenote, in the field selection field, these fields are being submitted as x.1, x.2, x.3. This is semantically invalid. This is a single field, it ends up just pulling the same single field, but with different formats. So sort of variations of the field.

But yes, sorting should definitely be done on the whole field, even if they're output as duplicates of a field with different formats. This is okay. Working on it.

**Comment by soulseekah** [comment]
The bad news is that Gravity Forms (GF_Query) does not sorting by time field at all. It won't even work for 24-hour formats. This is an upstream issue and requires work.

So while we can combine the field, it doesn't really work, test are failing.

Would you like me to work with GF on this, @zackkatz?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/836301381/20374

**Comment by rafaehlers** [comment]
The same is true for Date fields split in MM, DD and YY

**Comment by soulseekah** [comment]
> The same is true for Date fields split in MM, DD and YY

Are you sure? I'm pretty sure we do not split the dates at all, they're not stored in a split format either. Can you please send me a screenshot of what you mean?

**Comment by soulseekah** [comment]
I have the following prototype:

```sql
SELECT

	IF(
		EXISTS(SELECT v FROM meta AS m1 WHERE m1.k = '1.3' AND m1.v = 'pm' AND m1.e = m.e),
		-- We have PM, add 12 hours
		((SELECT v + 12 FROM meta AS m2 WHERE m2.k = '1.1' AND m2.e = m.e) * 60)
		+ (SELECT v FROM meta AS m2 WHERE m2.k = '1.2' AND m2.e = m.e),
		-- We have 24 hours, just add all the seconds
		((SELECT v FROM meta AS m2 WHERE m2.k = '1.1' AND m2.e = m.e) * 60)
		+ (SELECT v FROM meta AS m2 WHERE m2.k = '1.2' AND m2.e = m.e)
	) AS t

FROM meta AS m;
```

It will theoretically calculate the time value in seconds which we can then sort by. This will have to be integrated into GF_Query for time values when sorting.

**Comment by soulseekah** [comment]
Okay, so the above won't work as they're not kept separate. The query has to be different. `SUBSTRING_INDEX` incoming...

**Comment by soulseekah** [comment]
Okay, we now have merged timesort! The UI needs some fixing, though, I'll see if I can do this and we can test and close the issue :) this was very fun!

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/64255672-834dc980-cf2a-11e9-99ef-f6f180cb708f.png)

UI done as well I believe.

@rafaehlers can you please test and let me know how it goes? I'd like you to try out primary Date + secondary Time as well. It's going to be amazing!!!

**Comment by soulseekah** [comment]
Please test!

**Comment by zackkatz** [comment]
@gravityview/support Please test this
