### ISSUE TITLE
Possible issue with drop down fields that contain multiple items with same value

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1232]
Not sure if it's a bug exactly, but if you have a Drop Down field set up this way:

![gv-dropdown](https://user-images.githubusercontent.com/1222472/50489993-ec6f5b80-09f1-11e9-9c92-b501efb1dc13.png)

When editing an entry in GV, the selected choice will always be the latest one:

![gv-edit-entry](https://user-images.githubusercontent.com/1222472/50490058-3bb58c00-09f2-11e9-8654-8e2f582725c2.png)

Tested in GV 2.2.3

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/738604540/18334/

**Comment by soulseekah** [comment]
The values are the same. I'm almost sure that it's a browser choice. Let me put out this theory:

We have 4 label/value sets in the dropdown. We are going to render them now like this (pseudocode):

```python
for label, value in choices
    selected = 'selected="selected" if entry_value == value else ''
    print '<option value="%s" %s>%s</option>', value, selected, label
```

So two options end up having the `selected="selected"` HTML attribute. The browser's behavior is very probably undefined.

If the values are the same we'll never know which one was picked. Gravity Forms doesn't store the labels, just the values for a dropdown. So we never know.

Case in point: always use unique values, doh.

**Comment by rafaehlers** [comment]
The user contacted Gravity Forms' staff and they confirmed it's a Browser issue since they only store values.
