### ISSUE TITLE
Searching for Entry Date using Date Range on a Search Bar is no longer working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1233]
A Date Range search for any Date field work, but not for Entry Date: https://debug.gravityview.co/blog/view/date/?gv_start=12%2F27%2F2018&gv_end=12%2F29%2F2018&mode=all

Apparently started on GV 2.3.4

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/742079007/18369/

**Comment by soulseekah** [comment]
Broken in 5197a89c1 (2.2), fixed in 23e671ff
