### ISSUE TITLE
Gravity View Search Issue

### ISSUE THREAD

**Issue by pareshmithra** [gravityview/GravityView#1234]
Hi,
In gravity forms search there is a dropdown for Search, i.e contains and is. So if we enter half name of a user and search with the dropdown contains, it displays the entry.

But in gravity view there no option like "is" or "contains". There is only search everything option in the search bar. If we search the same way like gravity forms search, here it is not displaying the entry.

Can you please suggest me what to do?

**Comment by soulseekah** [comment]
Use the `gravityview_search_operator` filter for this.

```php
add_filter( 'gravityview_search_operator', 'my_gv_exact_search', 20, 2 );
function my_gv_exact_search( $operator, $field ) {
    if ( $field['key'] == '6' && $field['form_id'] == '1' ) {
        return 'is';
    }
    return $operator;
}
```

Cheers.

**Comment by pareshmithra** [comment]
No, I don't want exact search because currently, it shows the exact result only. I want liberal search like even if I search with the half word it should display the results.

**Comment by soulseekah** [comment]
'contains' is on by default. Please contact support at https://gravityview.co for further assistance.
