### ISSUE TITLE
REST API `.csv` is being output as JSON

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1235]
When accessing a View's output via the REST API endpoint and using `.csv`, it still outputs JSON.

See here: https://debug.gravityview.co/testing/wp-json/gravityview/v1/views/91/entries.csv

This doesn't happen when accessing the CSV from the `/csv/` endpoint: https://debug.gravityview.co/testing/view/products/csv/

This is likely because the JSON headers are already set.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995535657480599)

**Comment by soulseekah** [comment]
The output is CSV-formatted, but JSON-encoded. On the one hand this is an API, meant to be consumed by other programs, not meant to be downloaded. On the other hand, even though XML and JSON may be the standard ways to encode stuff, I think we can give ourselves some leeway here and output binary CSV with the correct headers. I don't think this will be harmful in any way.

**Comment by soulseekah** [comment]
We can further look at the Content-Type request header or something, or use the `?envelope` parameter to allow people who want JSON-encoded CSV payloads as we had.
