### ISSUE TITLE
Enhance [gvlogic] with date comparison

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1238]
At this moment, the `[gvlogic]` shortcode does not support date comparison: https://docs.gravityview.co/article/252-gvlogic-shortcode

In order to support Date comparison, we'll need to use the:
`greater_than`
`greater_than_or_is` or `greater_than_or_equals`
`less_than` 
`less_than_or_is` or `less_than_or_equals`

I believe we'll also need a `format` parameter to support the PHP Date Formats to prevent further issues when comparing dates in the format DD/MM/YYYY to MM/DD/YYYY like: 

`[gvlogic if="{Date Field:1}" greater_than="{Date Field 2:2}" format="d/m/y"]`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995535662518810)

**Comment by soulseekah** [comment]
I need more cases. This is not detailed enough. But I'm going to implement two-way field comparison. The format is not required for now as we can infer it from the fields themselves.

**Comment by soulseekah** [comment]
Wrote some tests and things are working fine with ISO formatted dates. Gonna check other formats, and cross formats.

**Comment by soulseekah** [comment]
Seems to work fine. Can you give me a case where this is NOT working, please? @rafaehlers

**Comment by zackkatz** [comment]
Closing, since there seems to not be a problem anymore!

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/1077833650/25203

**Comment by rafaehlers** [comment]
Definitely not working:

![image](https://user-images.githubusercontent.com/1222472/81450913-c1565980-9159-11ea-980d-95dbd4ad2ba9.png)


![image](https://user-images.githubusercontent.com/1222472/81450895-b26fa700-9159-11ea-9874-c0417a291db2.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1159906191/26867/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1233361281/28210/

**Comment by zackkatz** [comment]
@shamalisulakhe Can you please test this?

**Comment by Githubpowerusers** [comment]
Hi rafaehlers & zackkatz

Have you ever got this working? If so would you please post your solution?
This is not working!

[gvlogic if="{Date Field:1}" greater_than_or_equals="today"] ... [/gvlogic ]

Thank you

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/Advanced-Filter/pull/102

**Comment by zackkatz** [comment]
Note: update https://secure.helpscout.net/docs/566dfabbc6979143615564bf/article/5c91929c2c7d3a15446115f7 when addressed

**Comment by Githubpowerusers** [comment]
Thank you for the update: I can't open the link :(

Laszlo

**Comment by DanMuhl** [comment]
Is this working yet?  I REALLY need to be able to compare dates to "today" or something similar. Extremely important

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1386930240/31685/

**Comment by DanMuhl** [comment]
> https://secure.helpscout.net/conversation/1386930240/31685/

I can't open this because I don't have a helpscout account

**Comment by rafaehlers** [comment]
@DanMuhl that's for internal usage.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1439972037/32878/

**Comment by mojanoski** [comment]
Can we use -1 week inside [gvlogic]? Something like this below?

[gvlogic if="{Date:39:timestamp}" greater_than="-1 week {gv_now_timestamp}"]
Expiring in less than one week
[/gvlogic]

**Comment by zackkatz** [comment]
@rafaehlers @bennemann This works. If it doesn't, it's because of date formats.

Date formats can be forced when using Gravity Forms using the `:dmy` modifier. You can add that after any date field: `{Date:1:dmy}`. I have [updated the docs](https://docs.gravityview.co/article/252-gvlogic-shortcode#date-context-examples) with more examples showing this.

I have found this works consistently; I'm going to close this again.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1735339073/38794/ I can't make it work either.

**Comment by rafaehlers** [comment]
It seems that using the `:dmy` Merge Tag modifier on date field Merge Tags enables calculation:

```
[gvlogic if="{Event Date:7:dmy}" greater_than_or_equals="{date_dmy}"]
<a href="/events-calendar-new/rsvp?event={entry_id}">RSVP</a>
[/gvlogic]
```

**Comment by zackkatz** [comment]
@mrcasual Here's a link to the issue: https://debug.gravityview.co/blog/view/date-comparison/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1929898421/42111/
