### ISSUE TITLE
Optimize GravityView_Admin_Views::render_field_pickers

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1261]
The `GravityView_Admin_Views::render_field_pickers` outputs prerendered field pickers for all the forms in existence.

We have someone here with https://secure.helpscout.net/conversation/747489052/18443/ about 300 forms not too many fields, but across 3 configuration contexts it amounted to almost 25MB of data on the page.

We should look into not prerendering these for all the forms, there's no point. Let's do an AJAX request if the form is switched and prerender only the chosen ones. Don't forget about joined forms :(

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995532868663416)

**Comment by zackkatz** [comment]
Related to #1141

**Comment by soulseekah** [comment]
Bump. We need an action plan on this high priority issue that's almost a year old now :)
I believe @mrcasual is the right person for this task.

@zackkatz

**Comment by rafaehlers** [comment]
This is no longer an issue since the rewrite. Tested on GV 2.13.1
