### ISSUE TITLE
Do not display empty Product fields when Hide Empty Fields is checked

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1263]
That makes it difficult for our users to create reports and stuff.

Here's a good case when having Product fields with an empty (not filled) Quantity subfield are being problematic: https://secure.helpscout.net/conversation/749973482/18486/

![gv-products-1](https://user-images.githubusercontent.com/1222472/51217115-02e04700-190e-11e9-9e9c-1451ec48f79e.png)

If you don't fill the quantity field for both fields above, both fields will still show up on the Single Entry page:

![gv-products-2](https://user-images.githubusercontent.com/1222472/51217162-2efbc800-190e-11e9-8480-7b4d1f9ee002.png)

Which is odd!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995532833932202)

**Comment by soulseekah** [comment]
Are there any drawbacks to looking at the quantity field and if it's less than 1 to hide the whole product field? @zackkatz 

Can't think of any so this should be easy to fix, just need to make sure that this is a sane default for all? We can probably have a filter that we can provide to people who still want to display them, or maybe a filter that hides products with 0 quantities.

Thoughts?

**Comment by zackkatz** [comment]
@soulseekah We need to make sure that a quantity field exists for the product (it isn't required). If it _does_ exist and it is `0`, and it is connected to that specific product, then that should be okay.

**Comment by soulseekah** [comment]
Fixed with unit tests; please test and let me know if there are issues, Rafael. Thank you!
