### ISSUE TITLE
The Extensions page can't detect if Multiple Forms is already installed or active

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1264]
![gv-extensions-multiple](https://user-images.githubusercontent.com/1222472/51268077-4d150700-19a6-11e9-8475-9abc57de127c.png)

Tested on GV 2.2.4

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995532876381977)

**Comment by zackkatz** [comment]
Fixed—the issue is the textdomain of the plugin changed, but I didn't update the server with the next information.
