### ISSUE TITLE
WPML Endpoints Support is not compatible with entry endpoints

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1266]
All about the issue described in a memo here: https://secure.helpscout.net/conversation/723458750/18022

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995532868739211)

**Comment by soulseekah** [comment]
Tough one to debug.

The effect is caused by the `wpml-string-translation` plugin. It uses the core `WPML_Endpoints_Support` class to further alter the endpoint in a really weird way.

See the `wpml_ls_language_url` filter added in `WPML_Endpoints_Support`.
