### ISSUE TITLE
Changing Post title (View title) using the quick edit makes View loses adv filters set up

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1270]
![gv-filters](https://user-images.githubusercontent.com/1222472/51408419-c39c3b00-1b45-11e9-9a0e-16024c99f601.png)

To reproduce:
1) Specify any filter (advanced) on a View
2) Go back to the Views page and quick edit that View, change its name
3) Check back the View filters, they're gone!

Tested on GV 2.2.4

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/997775021033176)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/756322166/18615/

**Comment by soulseekah** [comment]
Fixed in https://github.com/gravityview/Advanced-Filter/issues/70
