### ISSUE TITLE
New Filter for Search Bar > Entry Creator > Show "username" instead of "Display Name"

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1272]
The Entry Creator field on the Search Bar show the user's `Display Name` which can be confusing for some large websites:

## Search Bar
![image](https://user-images.githubusercontent.com/1222472/51578374-879a0a80-1ea4-11e9-82cf-e5abb77d343b.png)

## View
![image](https://user-images.githubusercontent.com/1222472/51578454-c6c85b80-1ea4-11e9-89ac-999b15b28c11.png)

Here's a user feedback:

>Hi team, may I know if there's any way to set the search widget to filter the entry creator by username instead of current user display name? Because it's really confusing to search display name since some user might have quite similar names.

Implementing a filter there is enough.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1100685192186761)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/759903654/18717

**Comment by soulseekah** [comment]
I think this should be done with a filter instead. The use-case is too narrow to actually have a setting somewhere, other people might want an email, or some other meta field to be displayed there (prefix, for example).

Meet and enjoy `gravityview/search/created_by/text`
