### ISSUE TITLE
Mark entries as favorites

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1275]
The main feature of this is to allow logged-in users to mark an entry as a favorite, and then be able to see their favorites listed on their account. The logic has to support a special filter to display just the favourites.

Related to https://secure.helpscout.net/conversation/177197071/5123/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1105090050408676)

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/765335591/18871?folderId=408730

**Comment by soulseekah** [comment]
Would it be more appropriate as a separate extension? Or would you like to bundle it like we do with the approval extension?

**Comment by zackkatz** [comment]
This is definitely an extension; not many people want it.

**Comment by zackkatz** [comment]
This should be bumped.

**Comment by soulseekah** [comment]
Bumped from a cliff into the abyss? Or bumped higher up the priority staircase?

**Comment by zackkatz** [comment]
Bumped higher.

**Comment by zackkatz** [comment]
📈

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/966222040/22660/

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/65898146-8f0d9e00-e3b9-11e9-9825-e96a4093ae3c.png)

Work on this has commenced. I need an empty repository for the plugin.

**Comment by soulseekah** [comment]
I have an MVP that does displaying, setting/unsetting and filtering by favorites. Give me a repo @zackkatz, please and I'll push for your to play around.

**Comment by rafaehlers** [comment]
@soulseekah https://github.com/gravityview/Favorites

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1035896467/24031/
