### ISSUE TITLE
The option "Enable lightbox for images" is not working anymore for File Upload fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1277]
Images are being output as:

```<img src="http://localhost/gravity/index.php?gf-download=2019%2F02%2FImage2.jpg&amp;form-id=22&amp;field-id=2&amp;hash=52f82e37ce3d4ae830baa0681b95c43461af4838b81f11ee76cdfc0c64f6d104" width="250" alt="File" class="gv-image gv-field-id-2">```

So no specific classes for lightbox.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1003715482155835)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/770751312/18991/

**Comment by soulseekah** [comment]
Lightbox does not work for secure image URLs. This is a change that was done in 2.1.1 (October 2018):

```
* Limitation: "Enable lightbox for images" will not work on images when using Gravity Forms secure URL format. [Contact support](mailto:support@gravityview.co) for a work-around, or use a [different lightbox script](https://docs.gravityview.co/article/277-using-the-foobox-lightbox-plugin-instead-of-the-default).  
```

The secret workaround (DANGER! DANGER!) is to add `add_filter( 'gravityview/fields/fileupload/allow_insecure_lightbox', '__return_true' )` . This will DISABLE SECURE URLS in lightbox. Make sure the client is aware of the implications.
