### ISSUE TITLE
Create raw output for List, File fields in CSV, JSON

### ISSUE THREAD

**Issue by altoin** [gravityview/GravityView#1278]
**Describe the Issue**

HTML tags is being outputted when exporting data into CSV in TableView. 

https://secure.helpscout.net/conversation/770082258/18979/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1108749531780893)

**Comment by soulseekah** [comment]
Business hours field moved to https://github.com/gravityview/Gravity-Forms-Business-Hours/issues/13

**Comment by soulseekah** [comment]
Can be closed when merged. Thank you.

**Comment by rafaehlers** [comment]
Can we remove HTML for checkboxes fields and probably every other field that outputs HTML when exporting to CSV?

![image](https://user-images.githubusercontent.com/1222472/66443975-b26ac580-ea17-11e9-9d9e-1e9d57798547.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/975853180/22829/

**Comment by soulseekah** [comment]
Seems like the Paragraph field suffers from the same issues.
