### ISSUE TITLE
"Displayed list of users has been trimmed" showing when it shouldn't

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1279]
There are only a few users, and it's showing in Gravity Forms' Edit Entry screen:

![](https://share.gravityview.co/qMfpsa+)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1109353952824328)

**Comment by soulseekah** [comment]
Can't reproduce, you may have phantom users in the database or something? Can you send me a dump, please?
