### ISSUE TITLE
Month and Day subfields are inverted

### ISSUE THREAD

**Issue by altoin** [gravityview/GravityView#1280]
The `month` and `day` subfields of a date field are inverted. When adding only the `month` to the View, for example, the `day` field is the one that shows up instead.

![download 50](https://user-images.githubusercontent.com/8193486/53838792-30548300-3f96-11e9-979a-d4346fee7eaf.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1112790210152479)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/793596702/19482/

**Comment by soulseekah** [comment]
The day and month are switched in `GravityView_Field_Date::date_display()` for some reason. @zackkatz can we safely switch them over and write some tests? Or maybe you remember it working fine in 2016?

**Comment by zackkatz** [comment]
I don’t remember from 2016!
