### ISSUE TITLE
Consider moving testing to another provider, perhaps CircleCI

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1285]
TravisCI was acquired, and people say it's not going to be improving very much or rapidly.

[gennady](https://app.asana.com/0/974099000887566/) Any thoughts on this?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1114893597885771)

**Comment by soulseekah** [comment]
We can move to Circle completely once we have functionality tests going :)
Right now Travis is fine, unless they plan on becoming unreliable, expensive?

**Comment by soulseekah** [comment]
We need to write acceptance tests first, please. Can @mrcasual help with these?

**Comment by rafaehlers** [comment]
@mrcasual ☝️

**Comment by mrcasual** [comment]
Done and done.
