### ISSUE TITLE
UX issue when sending notifications for changing approval status

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1287]
User feedback:

>Here's the thing - you allow the option to send an email notification upon disapproval. I also have an email notification set to fire on approval. So, to disapprove, I have to click the same button twice and it fires off both email notifications. So, the person gets 2 emails immediately with approval and disapproval. 

>You should consider having an option for mutually exclusive approve/disapprove buttons considering the email notification features. 

<img width="433" alt="Screen Shot 2019-03-20 at 8 11 35 PM" src="https://user-images.githubusercontent.com/1222472/54728599-9415a900-4b5d-11e9-8914-63c285ba1635.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1115303957666267)

**Comment by soulseekah** [comment]
> I have to click the same button twice

Care to elaborate a bit? Why would they have to click the same button twice? What are they doing?

**Comment by rafaehlers** [comment]
@soulseekah the front-end approval button (Ajax) requires several clicks to cycle through all the statuses: 
![image](https://user-images.githubusercontent.com/1222472/54857859-4ffee180-4ce0-11e9-961f-672e413c52d8.png)

**Comment by zackkatz** [comment]
@rafaehlers I _just_ implemented a quick hack that adds disapprove (in #1288)

Now we have this:

- Control/Option+Click = Disapprove
- Shift+Option+Click = Unapprove

I would like to also have a hover-over feature where you hover over the approval box and all three icons become visible. That'd be way better, UX-wise.

Something like this:

![](http://share.gravityview.co/gHK9de+)

**Comment by rafaehlers** [comment]
@zackkatz loved the idea

**Comment by zackkatz** [comment]
Closed in favor of #1289
