### ISSUE TITLE
Add Approval status pop-over to make it easier to select a single status

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1289]
We have keyboard shortcuts when clicking statuses, but they aren't discoverable:

- Control/Option+Click = Unapprove
- Shift+Option+Click = Disapprove (added in #1288)

We should create a hover-over feature where you hover over the approval box and all three icons become visible. That'd be way better, UX-wise.

Something like this:

![](http://share.gravityview.co/gHK9de+)

See #1287  for the original issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1115616523896216)

**Comment by zackkatz** [comment]
Vlad ( https://app.asana.com/0/974099000887579/974099000887579 ) here’s some fun small project you can work on! Let me know if you need any guidance.

**Comment by zackkatz** [comment]
➤ Vlad commented:

Do you have preferred icons that you'd like to use? What about the popover library?

**Comment by zackkatz** [comment]
The icons should be reused from what we currently use, which is dashicons. Let’s use jQuery UI, since it’s bundled on sites anyway. Not very exciting, but standard?

**Comment by zackkatz** [comment]
Or what do you think?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/822938904/20103/
