### ISSUE TITLE
Hidden fields are shown for Subscribers

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1292]
# Form Editor

![image](https://user-images.githubusercontent.com/1222472/55366678-1be5a680-54c0-11e9-8f83-cfa826be9bd6.png)

# Form
![image](https://user-images.githubusercontent.com/1222472/55366639-fce71480-54bf-11e9-87f3-d5427ac04760.png)

# View

![image](https://user-images.githubusercontent.com/1222472/55366618-de811900-54bf-11e9-8dee-3ccb88cfee41.png)

GV 2.2.5

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1116790725149775)

**Comment by rafaehlers** [comment]
...and fields set as Visibility:Hidden (on Form Editor > Field Settings) are also displayed after the entry has been updated:

![image](https://user-images.githubusercontent.com/1222472/55367839-61f13900-54c5-11e9-8942-cecf81cd3021.png)

**Comment by rafaehlers** [comment]
exported form attached for test, just create a new View and don't add any fields to Edit Entry tab.

[gravityforms-export-2019-04-02.json.txt](https://github.com/gravityview/GravityView/files/3031849/gravityforms-export-2019-04-02.json.txt)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/814595512/19930/

**Comment by soulseekah** [comment]
Okay so hidden form fields will still be shown on edit and view screens unless they're explicitly hidden and restricted to a certain role from the View settings (not the Form settings). Can we agree on this?

It is important for anyone to be able to edit a hidden field if the View is setup to do so. I'll make some further testing but can we come up with a rigid specification for how hidden fields should work in all the views and different form, view and field settings?

**Comment by zackkatz** [comment]
Here's what I'm thinking:

- If Edit Entry fields are not configured (showing all fields): Hidden fields should remain hidden, but included in the form output.
- **If Edit Entry fields are configured**:  Hidden fields should be shown based on the ["Make visible only to logged-in users?" field setting](https://share.gravityview.co/VDggQ2).
- **Both** should still be overrideable using the `gravityview/edit_entry/reveal_hidden_field` filter.

@gravityview/core Does this make sense to you?

**Comment by soulseekah** [comment]
Makes a lot of sense to me, personally.

**Comment by zackkatz** [comment]
Okay, let's go with that outline, @soulseekah

**Comment by soulseekah** [comment]
We also have a *Hide empty fields* view setting. How will that affect the above?

**Comment by zackkatz** [comment]
It won't—that's for frontend, not Edit Entry.

**Comment by soulseekah** [comment]
Wording isn't really clear on that, is it? Are we sure?

**Comment by zackkatz** [comment]
Yes, I'm sure. That setting isn't shown in the Edit Entry field settings.

**Comment by soulseekah** [comment]
Okay, this is done. Please test accordingly.

**Comment by rafaehlers** [comment]
@soulseekah 

`add_filter( 'gravityview/edit_entry/reveal_hidden_field', '__return_true' );` doesn't work to display hidden fields on Edit Entry page when no fields are added (not set):

![image](https://user-images.githubusercontent.com/1222472/74213155-b84b0e80-4c76-11ea-9f64-e3205c8b4ce5.png)

As specified here: https://github.com/gravityview/GravityView/issues/1292#issuecomment-526263162

Tested on GV 2.5.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1073129860/25116

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1082874980/25292/
