### ISSUE TITLE
Custom content merge tag context for joins is missing

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1296]
The custom content field only knows about the main form, merge tag replacements are not possible for the other forms.

https://secure.helpscout.net/conversation/817542919/19991

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1117539662127833)

**Comment by rafaehlers** [comment]
Closed in favor of this: https://github.com/gravityview/Multiple-Forms/issues/20
