### ISSUE TITLE
Edit Entry regression in 2.3

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1300]
Some thing happened. Fields are doubled and the entry is not saved. We didn't have anything major done in regards to Edit Entry, I wonder what's going on...

https://secure.helpscout.net/conversation/824576191/20146/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1118418853774888)

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/824350265/20141?folderId=408730

https://secure.helpscout.net/conversation/823626394/20123?folderId=408730

**Comment by zackkatz** [comment]
It might be a Gravity Forms update.

**Comment by soulseekah** [comment]
Simple editing works fine, our tests work fine. Must be something special with conditions or something. Still investigating.

**Comment by soulseekah** [comment]
Reproduced, wow. 0a01c532ef1fc3b106096a26501c63f2ca3209c5 is the regression

**Comment by rafaehlers** [comment]
I'm pretty sure this is related as well: https://secure.helpscout.net/conversation/823269331/20114?folderId=408730

@soulseekah let me know when we have a patch, please.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/827872288/20215
