### ISSUE TITLE
Unlock the "Allow CSV Access" option to list all entries

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1306]
At this moment, this option paginates according to the number of records specified, which is not really useful for people in need of a CSV export:

![image](https://user-images.githubusercontent.com/1222472/56766719-7224cd00-6780-11e9-8e59-eddd1cfd4ed8.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1120086751713890)

**Comment by zackkatz** [comment]
It's not possible to turn on "unlimited" by default, since that'd be an easy way to crash a site, but we can definitely look at increasing the limit.

@soulseekah What's a sane limit to put here? 1000?

**Comment by rafaehlers** [comment]
Why not set a flag to remove the limit as well? Adding another limit will only partially solve this "need".

**Comment by zackkatz** [comment]
Sounds reasonable. @soulseekah ?

**Comment by soulseekah** [comment]
I need someone to hide the new `csv_nolimit` checkbox in JS. @zackkatz

**Comment by zackkatz** [comment]
@shamalisulakhe There’s a “requires” array key that enables a JS toggle for checkboxes and dependent fields. Please enable for this setting.

**Comment by shamalisulakhe** [comment]
@zackkatz Added 'requires' key
https://github.com/gravityview/GravityView/commit/84af8de85e7cba2132277c828aa86faaa6165456

**Comment by shamalisulakhe** [comment]
In addition, I found that (on multiple entries page) if an entry field is linked to single entry, it is exported along with the URL in the CSV file.

For e.g. Name linked to single entry is exported as 
<a href="http://site_url/view/test-form-view/entry/52/">John Doe</a>

**Comment by shamalisulakhe** [comment]
Solution - https://github.com/gravityview/GravityView/commit/1a3d7a8c9dffd3f4c5f6abdf0fcca84f098fcdd3
