### ISSUE TITLE
is_field_hidden caching with checkbox merge tags

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1307]
One of the weirdest issues I've ever seen.

https://secure.helpscout.net/conversation/811458088/19877/

`GF_Field_Checkbox::get_value_merge_tag` uses `GFFormsModel::is_field_hidden` which is cached for all entries. This is bad for us. As our users utilize merge tags across many entries on a page some checkboxes are hidden and cached as hidden. If the first entry has the checkbox hidden then all the following merge tags for the checkbox are empty. That is, the hidden logic is cached.

The only hack we came up with is to manually delete the cache key for the field (`GFCache::delete( 'GFFormsModel::is_field_hidden_' ...`) before every new entry. This is not a scalable solution for us.

@stevehenty any thoughts?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1120621225607355)

**Comment by soulseekah** [comment]
I suspect that we can reproduce this outside of a View even, across pages (single entry views in the backed). I'll try to investigate deeper and provide more information.

**Comment by zackkatz** [comment]
It looks like this may also be this issue: https://secure.helpscout.net/conversation/844464396/20533/

**Comment by mantasmacenas** [comment]
Hello guys, I'm the "lucky" guy who found this. Any luck with updating or fixing this? It does have a big impact on the product that we are developing...

**Comment by soulseekah** [comment]
> Hello guys, I'm the "lucky" guy who found this. Any luck with updating or fixing this? It does have a big impact on the product that we are developing...

This is going to be an upstream fix in Gravity Forms, I believe.

**Comment by soulseekah** [comment]
@mantasmacenas do you think you can help test the following patch?
Make sure you remove the fix I sent in your support ticket (the filter with the delete cache call).

```patch
diff --git a/forms_model.php b/forms_model.php
index d70bdf91..07652415 100644
--- a/forms_model.php
+++ b/forms_model.php
@@ -3157,6 +3157,13 @@ class GFFormsModel {
                }

                $cache_key = 'GFFormsModel::is_field_hidden_' . $form['id'] . '_' . $field->id;
+
+               if ( ! empty( $lead ) && isset( $lead['id'] ) ) {
+                       // Make sure that we cache field visiblity on a per-entry basis
+                       // https://github.com/gravityview/GravityView/issues/1307
+                       $cache_key = $cache_key . '_' . $lead['id'];
+               }
+
                $display   = GFCache::get( $cache_key, $is_hit, false );
                if ( $display !== false ) {
                        return $display;
```

We've submitted it upstream.

**Comment by soulseekah** [comment]
https://github.com/gravityforms/gravityforms/pull/661

**Comment by mantasmacenas** [comment]
I have inserted the code and I think from what I can see now it does the trick. I've commented the code out from the fix in functions.php and the information is still there. Therefor I would conclude that this fixes it.

**Comment by soulseekah** [comment]
Patch has been merged into Gravity Forms master. Will be released with next minor.
