### ISSUE TITLE
The combination of Search Everything (S. Bar) and Any Form Field contains return no entries

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1311]
## Search Bar
![image](https://user-images.githubusercontent.com/1222472/57119725-bdbc1580-6d42-11e9-8ae2-1e56f1cc4951.png)

## Advanced Filters

![image](https://user-images.githubusercontent.com/1222472/57119727-c6145080-6d42-11e9-8e7f-9952c5fdfad7.png)

## Table Output
![image](https://user-images.githubusercontent.com/1222472/57119750-e0e6c500-6d42-11e9-9d7b-c0dede6a4bbc.png)

Makes the search useless. No entries are returned.

## After searching

![image](https://user-images.githubusercontent.com/1222472/57119755-efcd7780-6d42-11e9-82f3-73c1a546a6a1.png)

GV 2.3.1
AF 1.3

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1121009992145801)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/842927656/20493/

**Comment by soulseekah** [comment]
Works okay on `develop`:

![image](https://user-images.githubusercontent.com/685880/65105756-a96d7200-d9de-11e9-8117-ec0b36558644.png)

![image](https://user-images.githubusercontent.com/685880/65105771-b4c09d80-d9de-11e9-84b6-b410589a6b5c.png)

Please confirm.

**Comment by rafaehlers** [comment]
Works fine on GV 2.9.1
