### ISSUE TITLE
Embedded entry differs from single entry view

### ISSUE THREAD

**Issue by jlgrisham** [gravityview/GravityView#1314]
When embedding an entry into a post or page, not all fields from the single entry view are displayed. The fields that are missing don't appear whether the entry was created before or after the fields were added to the view.

Single entry view:

![image](https://user-images.githubusercontent.com/48255575/57163810-3ad9a000-6dc0-11e9-9a15-98e791f745d8.png)

Embedded in post:

![image](https://user-images.githubusercontent.com/48255575/57163874-5ba1f580-6dc0-11e9-9c8c-6c19e78420c7.png)

To replicate, add a field to a single entry view then embed an existing entry

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1121135240543067)

**Comment by zackkatz** [comment]
@jlgrisham Can you be more specific regarding the fields that are missing?

Seems like the List field and Delete Entry field? 

The reason that's helpful to know is because it might be an issue with those specific fields.

**Comment by zackkatz** [comment]
@jlgrisham Also, it'd be helpful to have more details in the replication steps. For example, did you embed with oEmbed or with the `[gventry]` shortcode? The more details, the better.

**Comment by jlgrisham** [comment]
The fields that are missing are a single column list field that accepts multiple values, a multi column list field, and the Delete Entry field.

The entry was embedded by creating a new post and pasting the entry URL.

**Comment by soulseekah** [comment]
Is there a database dump I can get for this? A HelpScout ticket perhaps? @jlgrisham
