### ISSUE TITLE
Require `unfiltered_html` capability to edit Views

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1319]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1125167416572003)

**Comment by soulseekah** [comment]
This is a major breaking change. Unfiltered HTML has to be given to non-administrators in single-site mode and to non-superadministrators in multisite mode in order to access the Views menu.

This is very important to understand: @rafaehlers @jlgrisham @zackkatz

**Comment by soulseekah** [comment]
Use the `gravityview/security/require_unfiltered_html` filter to disable this feature.

`add_filter( 'gravityview/security/require_unfiltered_html', '__return_false' ); // Kittens died`

**Comment by zackkatz** [comment]
We need to write a doc about this:

- How does this affect users who already have `edit_gravityview` capabilities?
- What is the best way to add `unfiltered_html` capability for a user?
- Anything else?

**Comment by soulseekah** [comment]
I need this retested properly.

1. As admin - edit any views.
2. As editor, contributor, author - can't edit views.
3. Use some User Role Editor plugin, give 'unfiltered_html' cap to one of the above - be able to edit own views.
3. `add_filter( 'gravityview/security/require_unfiltered_html', '__return_false' )` - anyone above edit own views.

**Comment by zackkatz** [comment]
@shamalisulakhe can you please test, confirm, and close after testing:
https://github.com/gravityview/GravityView/issues/1319#issuecomment-545655492

**Comment by shamalisulakhe** [comment]
@zackkatz I tested this and found the following - 

- [x] As admin - edit any views
- [x] As editor, contributor, author - can't edit views.
- [ ] Use some User Role Editor plugin, give 'unfiltered_html' cap to one of the above - be able to edit own views.
- [ ] add_filter( 'gravityview/security/require_unfiltered_html', '__return_false' ) - anyone above edit own views.

Point 3 - Tested with editor user, can't edit own views even after having 'unfiltered_html' cap.
Point 4 - Can't edit own views, even after adding the filter.

In addition, observed an issue when creating a view. An editor can add a new view. When he adds and saves it, the view gets published, but user gets redirected to 'All Posts' page and the view data is not saved (such as view type, form, etc)

**Comment by shamalisulakhe** [comment]
Issue occurred when an editor creates a view - 
![Uploading editor-created-view-issue.gif…]()

**Comment by shamalisulakhe** [comment]
Added above the issue found when an editor adds a new view

**Comment by zackkatz** [comment]
This was not working because the user lacked the `gravityforms_create_form` capability. Updated docs to reflect this requirement.
