### ISSUE TITLE
Widgets are not being translated

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1322]
![image](https://user-images.githubusercontent.com/1222472/59315695-33e06000-8c91-11e9-973f-b76534c69a4f.png)

Even though these strings are properly translated into our .po/.mo file.

wp-content\plugins\gravityview\includes\widgets\class-gravityview-widget-pagination-info.php:

```   
57: $output = '<div class="gv-widget-pagination '.$class.'"><p>'. sprintf(__( 'Displaying %1$s - %2$s of %3$s', 'gravityview' ), number_format_i18n( $first ), number_format_i18n( $last ), number_format_i18n( $total ) ) . '</p></div>';
```

Tested on GV 2.3.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/876289458/21092/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/889916628/21328/

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/63935048-5fd7da00-ca65-11e9-92ee-cae4633a3534.png)

It's looking good for me. Which language are you testing?

**Comment by rafaehlers** [comment]
@soulseekah es_ES

**Comment by soulseekah** [comment]
es_ES is not translated as far as I can see. All the strings in the .po file are empty.

**Comment by soulseekah** [comment]
@zackkatz this one is for you, can you please check our build/translate process. es_ES seems to be missing a lot.
