### ISSUE TITLE
The Page Size widget breaks the Search Bar results

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1324]
## Pre-search:

![image](https://user-images.githubusercontent.com/1222472/59651122-05fe8e00-915f-11e9-9827-c9b7d8cd593d.png)

## After searching:

![image](https://user-images.githubusercontent.com/1222472/59651076-d2bbff00-915e-11e9-99d9-a37ae7dc335e.png)

## Changing the page size to 50:

![image](https://user-images.githubusercontent.com/1222472/59651094-e5cecf00-915e-11e9-883d-7a14cd58b480.png)

Tested on GV 2.3.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/880697424/21174

**Comment by soulseekah** [comment]
I was unable to reproduce in `develop`, can we please run a retest (@jlgrisham @rafaehlers)?

My search is behaving pretty well, apart from it resetting the `page_size` dropdown to the default value. Which is a bug this could issue could become.

**Comment by soulseekah** [comment]
Okay, this can be tested @jlgrisham @rafaehlers

I've also fixed the search button resetting the Page Size widget values!

**Comment by jlgrisham** [comment]
Working as expected now.
