### ISSUE TITLE
Bad time with Gravity Forms deactivated

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1326]
Lot's of issues in all our plugins if Gravity Forms is deactivated all of a sudden.

**Comment by zackkatz** [comment]
What do you mean "deactivated all of a sudden"?

**Comment by soulseekah** [comment]
Activate GF.
Activate GV.
Deactivate GF.
WSOD.

**Comment by zackkatz** [comment]
That only fixed one error. Still a big problem. Seems to go back to 8ad7c928c077a453ec75de2ae95fcc15e72d3e1b

**Comment by soulseekah** [comment]
I don't think we should even be loading core at all. All of our extensions should be checking for GV and WSODing. That would be the correct way to go about this. I'm still experimenting.

**Comment by zackkatz** [comment]
Yes, except not WSODing. Failing with a message saying that they require GV, as it used to.

**Comment by soulseekah** [comment]
Yes, that's what I mean sorry. Right now I can't reproduce the issue, your fix seems to have done it. Which extension fails?

**Comment by soulseekah** [comment]
DataTables still fails with WSOD. We need to test all extensions with GV active and GF inactive.
