### ISSUE TITLE
GV is not recognizing the license level

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1328]
Even after typing the correct license, GV can't identify the level, therefore you won't be able to install the plugins.

### User report:
>Hi, I've just signed up for the Core + Extensions license. But when I go to the Extensions tab, I see a message below the Advanced Filtering extension saying "Upgrade to Core + Extensions for Access". How do I fix this?

### Affected:
https://secure.helpscout.net/conversation/887511526/21286/
https://secure.helpscout.net/conversation/887399621/21284/
https://secure.helpscout.net/conversation/886693612/21272/

**Comment by zackkatz** [comment]
Wasn't able to reproduce.

I think this is likely a caching issue—can you have them de-activate and re-activate the license key?

**Comment by zackkatz** [comment]
Seems this is no longer happening.
