### ISSUE TITLE
Add front-end subscription cancellation functionality

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1329]
There is no easy way for users to cancel their Gravity Forms subscriptions from the front-end.

The code is available in `GFPaymentAddOn::ajax_cancel_subscription()`; we would need to make a GravityView field available for forms with subscriptions.

- Check if a form has a subscription payment configured
- Add the field if so
- In the field, generate an AJAX request
- Clone the `ajax_cancel_subscription()` so that it checks against the field existing in the View and the User being the same as the entry creator

**Comment by soulseekah** [comment]
> the User being the same as the entry creator

Or an admin? I'm going to give this a shot.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/65959117-d3507b00-e459-11e9-8fb8-03436d0a896b.png)

Almost there.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/66017515-d2fcc200-e4e3-11e9-990b-290bde2fe423.png)

Looks like it's working great. Tested with Stripe Addon.

**Comment by zackkatz** [comment]
Merged in core @ 2.5
