### ISSUE TITLE
{sequence} Merge Tag shouldn't increment when processed inside the same entry

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1330]
When adding `{sequence}` merge tag to the Custom CSS field setting, the value increments.

I don't know how to fix this—I tried! This is certainly related to 9156e4b6a and 5912776d8 and https://gravityview.slack.com/archives/G727B06MB/p1562872075384100?thread_ts=1562870707.372000&cid=G727B06MB

### The numbering is off.
![](https://share.gravityview.co/rWPpuo+)

### Why? The Custom CSS Class is set to `best-book-{sequence}`
![](https://share.gravityview.co/4HRFfr+)

**Comment by soulseekah** [comment]
I think I have an elegant fix that seems to work. Your tests pass without modifications.

**Comment by zackkatz** [comment]
I was wondering if that would work!! Thanks, @soulseekah

**Comment by zackkatz** [comment]
Now this is the problem: the View has two entries sometimes and three entries other times. 🤕

![](https://share.gravityview.co/t5HcYY+)

**Comment by zackkatz** [comment]
But that's a different issue—I believe the main bug is now fixed.
