### ISSUE TITLE
Add "Admin Label" to Custom Content fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1331]
When the user has several Custom Content fields on the View Editor and it doesn't use front-end labels, then it can be difficult to know, just from looking at the Editor, to identify which field that relates to:

![image](https://user-images.githubusercontent.com/1222472/61237901-e3d23e80-a711-11e9-95d7-912fe3ddfd6e.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/902561510/21531/

**Comment by JurriaanK** [comment]
+1!

**Comment by soulseekah** [comment]
Interesting. As a UI suggestion maybe we can output part of the internal custom content text in gray next to the label? None of our fields have an admin label setting or any sort.

Any thoughts @zackkatz?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/975437568/22818/

**Comment by soulseekah** [comment]
Okay let's give this a test, guys. Hopefully nothing broke. We don't have unit tests or acceptance tests for the backend so please please please test as rigorously as you can.

**Comment by jlgrisham** [comment]
@soulseekah In my testing the admin labels only appear after hitting the Update button on the Edit View page. With the other fields, if I enter a custom (not admin) label I can see the new label upon clicking Close from the field Options popup. Is that expected or is that maybe related to my test environment?

**Comment by soulseekah** [comment]
Thanks for testing, Jerry. Yes, that's expected. I can try to fiddle with the Javascript if everything else is okay. UX-wise I think it should change like the others, agreed.

**Comment by soulseekah** [comment]
Please retest. JavaScript has been written.

**Comment by soulseekah** [comment]
Please make sure you're running with `define( 'SCRIPT_DEBUG', true );`. As the changes are in the unminified scripts which were not rebuilt yet!

Let's try again, @jlgrisham

**Comment by jlgrisham** [comment]
That did the trick. Nice work!
