### ISSUE TITLE
Editing an entry tied to a User Registration create feed logs out the user

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1333]
It seems like this old issue is back , and now it's not related to the password field on the Edit Entry page.

## Steps to reproduce

1. Create a form and set a create feed on User Registration
2. Create a View tied to that form
3. Register a new WP user using that form
4. Log on the website
5. Edit any field from this user using the View
6. The user is logged out of the website

## Versions

GV 2.4
GF 2.4.11
UR 4.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/906562583/21610/

**Comment by rafaehlers** [comment]
According to one of our users:
>I have discovered setting the user feed to Auto generate a password rather than permit the user to enter a password upon registration does not generate this issue.

**Comment by endurtech** [comment]
[https://www.youtube.com/watch?v=VSfL8m4lUF0](https://www.youtube.com/watch?v=VSfL8m4lUF0)

**Comment by soulseekah** [comment]
Related to #1225

**Comment by soulseekah** [comment]
I'm unable to reproduce with UR 4.3, care to test @endurtech?

https://s19.aconvert.com/convert/p3r68-cdx67/wm0hz-fnfyg.gif

**Comment by endurtech** [comment]
Happy to give it a try. Will reply back after testing it later today. Thank you.

**Comment by endurtech** [comment]
Well done. Tested using the new User Reg Add-On v4.4 and Gravity Forms v2.4.14 and issue appears to have been resolved. Thanks again.
