### ISSUE TITLE
GP Populate Anything

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1335]
Does not work.

https://secure.helpscout.net/conversation/910830114/21686/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/923772406/21930

**Comment by soulseekah** [comment]
I've done a lot of testing and everything seems fine in a minimal setup GV + GPPA. So there must be something else.

**Comment by soulseekah** [comment]
I'm beginning to think this is a configuration issue. The original thread used the Populate Value Dynamically which works in a very very weird way to begin with, even outside GravityView. It sort of allows you to mix predefined Labels and dynamic Values in a mind-boggling way.

The Populate Choices Dynamically hides the predefined choices altogether and works absolutely well with Merge Tags etc.

Will wait to see what first client responds.

Second client seems to be unrelated. They seem to be expecting that a value reference has to be updated whenever they edit it (via the admin or GV), but there is no link between the target form field value and the source, it's a mere copy, just like renaming a choice dropdown in a form will not rename all the entry field values for the form.

**Comment by zackkatz** [comment]
Closing until reported again. David provided some fixes, which may have addressed other issues.
