### ISSUE TITLE
Detect if Gravity Forms is installed

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1337]
At this moment, this Fatal Error is thrown:
>Fatal error: Uncaught Error: Class 'GravityView_Admin' not found in /app/public/wp-content/plugins/gravityview/future/includes/class-gv-view.php on line 153

**Comment by zackkatz** [comment]
Frontend? Steps to reproduce please.

**Comment by rafaehlers** [comment]
Back end. Just trying to activate GravityView without Gravity Forms installed.
