### ISSUE TITLE
Number precision format is not working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1341]
This option:

![image](https://user-images.githubusercontent.com/1222472/64303513-f1ac7f00-cf5e-11e9-9a42-7f7de6806ef1.png)

doesn't work:

![image](https://user-images.githubusercontent.com/1222472/64303522-fa04ba00-cf5e-11e9-8f74-8e4ad6e377bf.png)

Tested on GV 2.4.1.1

**Comment by soulseekah** [comment]
The unit tests are passing well on this. Testing manually...

**Comment by soulseekah** [comment]
Okay, it doesn't work if Number Format is not set.

![image](https://user-images.githubusercontent.com/685880/64356812-288c9e80-d00c-11e9-94bd-71f22de76380.png)

Writing test.

**Comment by soulseekah** [comment]
Please test usability @rafaehlers @jlgrisham

**Comment by jlgrisham** [comment]
Tested and working even if Number Format isn't set.
