### ISSUE TITLE
Search All does not work with Joins

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1342]
https://secure.helpscout.net/conversation/901011478/21506/

**Comment by soulseekah** [comment]
No news from customer. Would be nice to get tests here.

**Comment by jlgrisham** [comment]
Not able to get this working in my testing. No feedback from the customer still, but I'm getting the same results she is.

I have 2 forms joined by Last Name. When I add the search bar with Search Everything then search for a last name, no results from the secondary form appear.

**Comment by soulseekah** [comment]
Are you sure you're doing this on `develop`, Jerry? It's working fine for me:

![image](https://user-images.githubusercontent.com/685880/69492974-18bd8180-0eba-11ea-92c9-66ccbc8ff14c.png)

![image](https://user-images.githubusercontent.com/685880/69492981-296df780-0eba-11ea-956c-2260b0d7a1b6.png)

![image](https://user-images.githubusercontent.com/685880/69492985-312d9c00-0eba-11ea-8ca6-1e252edd77ee.png)

What am I missing?

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/1024140698/23788/ another similar instance but not exactly this.

**Comment by soulseekah** [comment]
There are complicated issues with GF_Query global search. We've been rolling it back and forth this year. Back when we had our own Search_Condition it seemed to work much better, with some disadvantages.

I'm taking a couple of extra stabs at it.

**Comment by soulseekah** [comment]
> https://secure.helpscout.net/conversation/1024140698/23788/ another similar instance but not exactly this.

This is actually https://github.com/gravityview/Multiple-Forms/issues/37 which we're in dire need to implement.

**Comment by soulseekah** [comment]
> > https://secure.helpscout.net/conversation/1024140698/23788/ another similar instance but not exactly this.
> 
> This is actually [gravityview/Multiple-Forms#37](https://github.com/gravityview/Multiple-Forms/issues/37) which we're in dire need to implement.

And it's actually not! So confusing. I now firmly believe that it's actually this issue! And I know how to reproduce it. Search mode has to be "all". That's how it breaks. Confirmed.

P.S. On a related security note do we allow mode changes without enforcing them? i.e. if a form is set to "any" changing the URL to "all", should that be allowed? Right now it is. @zackkatz

**Comment by soulseekah** [comment]
The generated SQL inside a joined form for a global condition (`{{ANY META FIELD}}`) will combine different form statements with the `mode` (`OR` or `AND`), when in fact it should always be an `OR`. This is a GF_Query issue actually.

**Comment by soulseekah** [comment]
I have identified the exact issue. It's in `GravityView_Widget_Search::gf_query_filter`. We are looking at mode and doing this.

We are relying on `GF_Query::get_global_condition`, though, which sometimes generated really weird search conditions (especially for checkboxes, it seems).

I'll have a fix for our part shortly. But GF_Query is in dire need of attention for the global search, especially with joins (i.e. no form_id supplied for meta vs. form_id supplied, etc.). Complicated stuff.
