### ISSUE TITLE
Pagination is not working properly when filtered by date

### ISSUE THREAD

**Issue by pareshmithra** [gravityview/GravityView#1343]
**Describe the Issue**
When I filter the entries by date it shows the number of pages. But when you click on the second page of entries it is actually not going to the second page of filtered entries, it is going to the second page of full entries.

Please help.

--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [x] View
- [ ] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[replace me]`

**Are Advanced Filter filters configured for the View?**

- [x] Yes
- [ ] No

**If yes, please drag a screenshot below:**

**Comment by soulseekah** [comment]
Thanks for the report. Have you tried contacting support@gravityview.com for assistance with debugging the issue?

**Comment by pareshmithra** [comment]
No. Not tried yet.

**Comment by pareshmithra** [comment]
Tried reaching support@gravityview.com but the mail is not delivering to that email id. It says 
"The response from the remote server was:
554 5.7.1 <support@gravityview.com>: Relay access denied"
