### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1345]
Lots of permissions failures, about 10 tests are failing.

**Comment by soulseekah** [comment]
Bisect shows 1803ef7878b33cd09bdb00469939149f7898e3d9 as one of the culprits.

**Comment by soulseekah** [comment]
6 fails to go.

**Comment by soulseekah** [comment]
5.

**Comment by soulseekah** [comment]
4.

**Comment by soulseekah** [comment]
3.

**Comment by soulseekah** [comment]
`GravityView_Edit_Entry_Test::test_field_visibility_and_editability_caps`'s success depends on the number of forms that have been created... weirdest thing I've ever seen.

I modify the create_many call in `GVCommon_Test::test_get_forms` from 5 to 3 and it works. 1 and 2 works as well, anything over 5 stops working.

...It's like it fails unless there are more than 100 forms present.

I literally do a `--filter GravityView_Edit_Entry_Test::test_field_visibility_and_editability_caps --repeat 20`, it works for the first 4 times, then it stops working for 5 times, and then works for 11 times!

I'm stumped.

**Comment by soulseekah** [comment]
`input_1` is contained in `for="input_17_2"`... doh

2 to go :checkered_flag:

**Comment by soulseekah** [comment]
0?

**Comment by soulseekah** [comment]
3.

**Comment by soulseekah** [comment]
2 :smile:

**Comment by soulseekah** [comment]
0. But not on all versions:

![image](https://user-images.githubusercontent.com/685880/67500397-429d4180-f68b-11e9-8a6d-45ce72424739.png)

ugh

**Comment by soulseekah** [comment]
A regression in WordPress nightly:

https://core.trac.wordpress.org/ticket/28636

**Comment by zackkatz** [comment]
@soulseekah I thought the nightlies wouldn't show as errors in the build?

```
allow_failures:
      - php: nightly
```

**Comment by soulseekah** [comment]
See: https://core.trac.wordpress.org/ticket/28636#comment:34

**Comment by soulseekah** [comment]
> See: https://core.trac.wordpress.org/ticket/28636#comment:34

`nightly` should be fine.

**Comment by soulseekah** [comment]
`Errors: 1, Failures: 1`... continuing the battle.

The error is from #877 d04c10a20c42a333b9936e5bae71dac2ec37c7c2 which is a good thing, strangely (and hopefully). It should be failing but for other reasons.

The failure is being worked on.

**Comment by soulseekah** [comment]
Bah, I don't know... it's soooooo bad:

![image](https://user-images.githubusercontent.com/685880/67787597-e74fc280-fa81-11e9-822c-f4038bb41331.png)

But we're almost there: https://travis-ci.org/gravityview/GravityView/builds/604386137

**Comment by soulseekah** [comment]
There seems to be a bug in latest. `GravityView_Merge_Tags_Test::test_replace_date_updated` human time diff stuff. I would love to look into it if no update is released in a week or two, after handling more pressing matters. Okay?

**Comment by zackkatz** [comment]
@soulseekah Yep, sounds good.

**Comment by soulseekah** [comment]
Seems to have helped locally:

![image](https://user-images.githubusercontent.com/685880/67834917-b8753300-faf9-11e9-8247-c7894f6650e2.png)
