### ISSUE TITLE
Back link cookie snowball

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1346]
We need to figure out a way to prevent this from happening.

![image](https://user-images.githubusercontent.com/685880/65119557-0c6a0380-d9f5-11e9-92e1-46a9123e00de.png)

https://secure.helpscout.net/conversation/956932119/22495?folderId=1210164

Some ideas:

1. Set just one cookie as a JSON array.
2. The URLs do not need to include the domain.
3. We should unset links that will not be used in the next request.

Temporary solution: https://gist.github.com/zackkatz/354a71dc47ffef072ed725706cf455ed

**Comment by zackkatz** [comment]
@soulseekah What about using localStorage instead? Cookies have more problems.

**Comment by soulseekah** [comment]
localStorage is a great idea, but JavaScript is required for it to work

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/66137053-2a468380-e605-11e9-8106-4101d66cb25e.png)

Problem is that `#gravityview_back_link` is not something that exists...

Our cookies aren't even working :rofl: the element that has to be replaced does not exist in the repository. Our back links are output with `.gv-back-link` class even on single entries. Not even in version 1.19.x

The function was touched last and worked back in 123da47b. Back then `gravityview_back_link()` did output the id:

![image](https://user-images.githubusercontent.com/685880/66137727-2cf5a880-e606-11e9-8804-328122b9deda.png)

This was changed to a link that has no id in 1d53e41f74377c8b3f6059557463cb8327b533fc :)

We've not been using cookies since Sat Jan 31 16:27:06 2015.

Proposal: remove cookies.
Reason: they have not been used, nobody complained about wrong backlinks
