### ISSUE TITLE
`unset_hidden_field_values` does not always work

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1349]
I doesn't work with Calculations as far as we can see.

https://secure.helpscout.net/conversation/971262667/22746?folderId=1210164

Discovery phase in https://github.com/gravityview/GravityView/issues/941

**Comment by soulseekah** [comment]
:heavy_check_mark: Works fine with non-calculation Number fields.

:x: Does not work with calculation Number fields. Calculations are redone regardless of them being hidden. That `get_value_save_entry` bit in:

![image](https://user-images.githubusercontent.com/685880/66349143-e20ac680-e960-11e9-9bca-e4793461ed1f.png)

...redoes the calculation and returns a non-empty value.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/66349591-e2579180-e961-11e9-9b66-56bf3dffb820.png)

This simple thing does not work... they must be getting recalculated later.

**Comment by rafaehlers** [comment]
Confirmed it's working: https://secure.helpscout.net/conversation/1006040708/23375
