### ISSUE TITLE
Race condition during save form

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1350]
Initially reported here https://secure.helpscout.net/conversation/852334104/20674/

I manged to reproduce by calling /wp-admin/update-core.php?force-check=1 in a loop while manually saving a View. Took about 10 tries to get the fields erased.

No idea why it's happening, static code analysis doesn't provide anything useful. Will try to debug in the coming days.

**Comment by soulseekah** [comment]
Hmm, after some further trials updates don't seem to be the issue. I'm able to reset the fields pretty easily just by hitting Update a bunch of times, clicking the button in a crazy way. I think it happens when the fields' `gv_fields` input hasn't been populated by the JS yet and you can hit Update to erase everything.

@rafaehlers @jlgrisham @zackkatz can you please test?

Here's a video https://www.youtube.com/watch?v=ywnnMPwTmmE

**Comment by rafaehlers** [comment]
@soulseekah This user reported this before: https://secure.helpscout.net/conversation/960462831/22564/

**Comment by zackkatz** [comment]
@mrcasual please add checks to make sure the field configuration is fully loaded before saving takes place.

**Comment by soulseekah** [comment]
> @mrcasual please add checks to make sure the field configuration is fully loaded before saving takes place.

@zackkatz let's not do this in JS. If JS breaks then the saving will still take place. Let me try and fix this the correct way of outputting the hidden input in the HTML with the existing fields in there.

**Comment by soulseekah** [comment]
I'd like everyone to test with 1e5e9bf7 and without it.

It's behaving pretty stably for me. See if you can break it.

**Comment by mrcasual** [comment]
@soulseekah I am able to [reproduce the issue](https://www.dropbox.com/s/pdj37bozamclsxf/2019-10-09_20-37-42.mp4?dl=0) on `1e5e9bf` by clicking update button 2-3 times before it's disabled.

**Comment by soulseekah** [comment]
> @soulseekah I am able to [reproduce the issue](https://www.dropbox.com/s/be6wx3fbxs823gx/IMG_5847.MOV?dl=0) on `1e5e9bf` by clicking update button 2-3 times before it's disabled. Assets compiled, cache cleared.

Thanks. Reproduced as well.

This is a JS issue. Pretty sure that `serializeForm` function is hit several times, but it deletes the fields the first time the form is serialized. I'll try to add a mutex into it.

**Comment by soulseekah** [comment]
Check out `4830a15` and see if you can break it. I added some caching during submission.

Clickers be clicking'.

Good find @mrcasual 

Anyone else wanna try and break it?

**Comment by zackkatz** [comment]
No breaky-breaky! Nice job!
