### ISSUE TITLE
Add support for "visual tokens" in search

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1355]
It could use Merge Tag JS to identify possible  search fields.

![](https://i.gravityview.co/OwE2fP+)

![](https://github.com/ashubham/tokenizer.js/raw/master/assets/tokenizer.gif)

### Existing Libraries

- http://documentcloud.github.io/visualsearch/ ([repo here](https://github.com/documentcloud/visualsearch))
- https://github.com/ashubham/tokenizer.js ([see blog article about it](https://codeburst.io/supercharge-your-search-with-tokenization-32321a87f309))

**Comment by soulseekah** [comment]
Jesus.
