### ISSUE TITLE
Add a Gravity Forms search widget

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1357]
Gravity Forms' javascript search UI could be used out of the box, with customizations to support our own URL scheme #1174 or implement Gravity Forms' URL scheme #1200

**Comment by soulseekah** [comment]
I'm guessing GravityWiz changes everything. When will the plugin be shared with us?

Some initial thoughts:

1. How will configuration work? Or shall we output everything we can (UI could get clunky)
2. Where will the widget be output? On the Entries list in the backend?

**Comment by zackkatz** [comment]
Closed in favor of adding a new search bar instead.
