### ISSUE TITLE
Update default widgets when creating a new View

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1358]
### When creating a new View, add these widgets to the View Configuration by default:

**Above:**

- Search Bar with "search everything" selected by default
- Show Pagination Info on left
- Page Links on right (default config)

![](https://i.gravityview.co/pifQ8R+)

**Below:**

- Page Links on right (default config)

![](https://i.gravityview.co/A904Yx+)

**Comment by zackkatz** [comment]
@soulseekah Can you give this a whirl and see how much work it'll be?

**Comment by soulseekah** [comment]
I'm almost certain that this is mostly a JavaScript thing. The server is not touched on the /wp-admin/post-new.php?post_type=gravityview screen up until the Update button is hit for the first time.

Users might hit the Update button from the get go, before the widgets are populated, so we need to make sure they're there on pageload I guess. Which is where the backend side of things comes in.

Investigating.

**Comment by zackkatz** [comment]
@soulseekah Configuration is pulled in via AJAX regardless of if it's a new or existing View.

**Comment by soulseekah** [comment]
> @soulseekah Configuration is pulled in via AJAX regardless of if it's a new or existing View.

There is also static output which we should also be handling, I believe:

![image](https://user-images.githubusercontent.com/685880/67027771-d498cd80-f112-11e9-9589-5762b3a9a312.png)

**Comment by soulseekah** [comment]
Let's get this tested, please. I'm sure there are some edge cases that I didn't click through :)

**Comment by zackkatz** [comment]
@soulseekah It doesn't render on the front-end for me.

It looks good when added:
![](https://i.gravityview.co/MEr7Iv+)

But when clicking into the Search Bar settings, it shows as unconfigured:
![](https://i.gravityview.co/ex3KMy+)

And on the front-end, the Search Bar doesn't show:
![](https://i.gravityview.co/hERYNZ+)

**Comment by soulseekah** [comment]
It seems to work some of the times... rarely, but it does. Investigating.

**Comment by soulseekah** [comment]
I've found the culprit to be this piece of code:

![image](https://user-images.githubusercontent.com/685880/67225760-76365c80-f43c-11e9-99df-c47909404c3c.png)

Any ideas on how to deal with it? Search All is universal so perhaps we can leave Search All fields?

**Comment by zackkatz** [comment]
@soulseekah good idea. I can implement.

**Comment by soulseekah** [comment]
> @soulseekah good idea. I can implement.

Absolutely, sure. Let me know.
