### ISSUE TITLE
Improve WPML compatibility

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1361]
Let’s get WPML working very well with GV 💯

Add comments below with checkboxes for items that should work better. Use this format:

`- [ ] Example item`

**Comment by zackkatz** [comment]
- [ ] Table header (field labels) are not translated
http://gravityview.compatibility.wpml.org/gravityview1/?lang=sr

![](https://i.gravityview.co/M7fXZr+)

We need to get translations applied to field label
when rendered on frontend.

Is this place on code where filters should be applied?

```
\gravityview_get_field
@uses \GFFormsModel::get_field
```

Or there is better place to filter field label?

**Comment by zackkatz** [comment]
- [ ] Entries in all languages are listed (not filtered)
http://gravityview.compatibility.wpml.org/gravityview1/

![](https://i.gravityview.co/IFqrXy+)

Maybe we should filter query and have only entries in current language translated?

Is this correct place in code to check if filters can be applied?

```
\gravityview_get_entries
@uses \GFAPI::get_entries
```

**Comment by soulseekah** [comment]
What's the priority on this?

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/1005572817/23367

**Comment by soulseekah** [comment]
https://secure.helpscout.net/docs/566dfabbc6979143615564bf/article/5841070c903360069817599c/

https://docs.gravityview.co/article/395-wpml

**Comment by soulseekah** [comment]
> Can we get the latest versions of all the relevant plugins (core, string translation, gf-multilingual, translation-management, etc.), please? @zackkatz

Bump. Also needs a priority.

https://secure.helpscout.net/conversation/1005572817/23367/
