### ISSUE TITLE
Hide Edit Entry and Delete Entry columns if current user has no cap

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1364]
If the current user or even a not-logged-in website visitor has no capabilities to edit any entries, then don't show these two columns:

![image](https://user-images.githubusercontent.com/1222472/67444521-d6193880-f5df-11e9-8fd0-e913f9add069.png)

Tested on GV 2.4.1.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/987726177/23041/

**Comment by soulseekah** [comment]
The only way to do this would be to scan ALL the entries before outputting them and check the caps for each entry, if any of the entries is editable - show the column, otherwise - hide it.

Same for our duplicate thing #1360

**Comment by soulseekah** [comment]
We should definitely hide them if user has no cap to edit / delete based on View settings (allow user edit).

**Comment by soulseekah** [comment]
WIP on the `feature/delete-edit-hide-linkage` if anyone wants to play around with it. It looks pretty good but needs unit-tests and manual tests.

**Comment by soulseekah** [comment]
- [ ] Also do duplicate entry
- [ ] Unit tests

**Comment by soulseekah** [comment]
This is merged into `master`. We still need tests, duplicate entry and approval etc.

**Comment by zackkatz** [comment]
@shamalisulakhe Please also make this happen for 

- [ ] Duplicate entry field
- [ ] Approval link field

https://github.com/gravityview/GravityView/issues/1364#issuecomment-554603806

**Comment by shamalisulakhe** [comment]
@zackkatz  Checked for both.

Approval link column is not available if the user has no access to approve any of the entries.
Did changes to hide duplicate link column.
