### ISSUE TITLE
When old Gravity Forms is running (<2.3), causes fatal error

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1370]
This admin notice runs earlier than `GravityView_Admin_Notices` is loaded, and also `\GV\Utils` doesn't exist yet because `Core::init()` hasn't run yet. 

![](https://i.gravityview.co/uRWjMG+)

- Install Gravity Forms
- Install and activate GV
- "This site is experiencing technical issues"

This was on Multisite with "directory" structure, not subdomains.

@soulseekah Please fix asap.

**Comment by soulseekah** [comment]
I've allowed more of core to load when not compatible. This includes \GV\Utils. Should work well, please verify. Thank you.
