### ISSUE TITLE
Fix enqueued scripts and styles when embedded in ACF fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1373]
> If the shortcode is in the standard content editor, the default css is included (table-view.css, gv-default.css). When we switch the page to use a page builder powered by ACF, the CSS is not included. We love the idea of the CSS only being included on pages where it's required but, if it's only checking "the_content()" this is going to be an issue. Is there any way around this other than manually enqueueing the files globally?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1005303316/23364/

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/1011097552/23489

**Comment by soulseekah** [comment]
As a note: this seems like the same issue we have with people using `do_shortcode` in their themes, calling a a shortcode in a template. I can't find the related issue on GitHub, maybe we never created it.

**Comment by soulseekah** [comment]
I wonder which page builder is being used.

**Comment by soulseekah** [comment]
Related https://github.com/gravityview/GravityView/issues/1070

**Comment by zackkatz** [comment]
Closing in favor of #1070
