### ISSUE TITLE
Delete Entry not available for subscribers

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#1374]
![image](https://user-images.githubusercontent.com/685880/68953977-18472b80-07d4-11ea-802b-b7c8dcd68a55.png)

![image](https://user-images.githubusercontent.com/685880/68953986-1da47600-07d4-11ea-8c50-f57232c410df.png)

Edit Entry works, Delete Entry doesn't work.

`check_user_cap_delete_entry` returns false, even though the entry was created by the user

Discovered during work on #1364

**Comment by soulseekah** [comment]
Doh. User Delete is a separate setting.

Not intuitive at all. There are two settings one inside the field, the other inside the view.

**Comment by zackkatz** [comment]
@soulseekah when you experience things like that, please create a ticket for us to fix them. Let’s improve that!

**Comment by soulseekah** [comment]
We wanted to create a second setting in edit view, I think we had a ticket somewhere for granular edit permissions as well on a per-field basis. I'll try to find it :D
