### ISSUE TITLE
Write unit tests for Duplicate Entry

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1377]
> Needs tests, but only after #1345 is taken care. We want green.

Can you add some tests, regardless of the color?

_Originally posted by @zackkatz in https://github.com/gravityview/GravityView/pull/1360#issuecomment-554220719_

**Comment by soulseekah** [comment]
A todo of https://github.com/gravityview/GravityView/issues/930

**Comment by soulseekah** [comment]
And I'm done I think.
