### ISSUE TITLE
Add "Duplicate Entry" functionality to the Gravity Forms Entries screen

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1384]
It should be added as an "Entry action" link.

Questions: 

- Should there be an admin setting per-form?

**Comment by soulseekah** [comment]
> Should there be an admin setting per-form?

I don't think anyone would mind, but we can certainly have a filter for the one time someone wants the action gone.

**Comment by soulseekah** [comment]
Can be disabled with the `gravityview/duplicate/backend/enable` filter.

Example:

```php
add_filter( 'gravityview/duplicate/backend/enable', function( $enable, $form_id ) {
    if ( $form_id == MY_FORM_ID ) {
        return false;
    }
    return $enable;
} );
```

**Comment by soulseekah** [comment]
Initial functionality pushed. Needs feedback.
Needs tests.
