### ISSUE TITLE
Edit Entry link not working with [gventry] first and last ID values

### ISSUE THREAD

**Issue by ghost** [gravityview/GravityView#1390]
When using the [gventry] shortcode with id="first" or id="last" in a post or page like so:

[gventry entry_id="last" view_id="8"]

The Edit Entry link on the Single Entry View reloads the entry rather than loading the Edit Entry View.

To reproduce,:

### 1. Create or edit a View that includes the Edit Entry link on the Single Entry View:

![image](https://user-images.githubusercontent.com/48255575/70458728-b602e300-1a80-11ea-9941-184175e124e1.png)

### 2. Create a post or page using the [gventry] shortcode with either "first" or "last" as the value for the entry_id parameter:

![image](https://user-images.githubusercontent.com/48255575/70458884-0e39e500-1a81-11ea-8994-26c241d6fc4d.png)

### 3. Save the post then view it in your browser:

![image](https://user-images.githubusercontent.com/48255575/70458985-43463780-1a81-11ea-9c5b-070928266c19.png)

### 4. Click the Edit Entry link:

![image](https://user-images.githubusercontent.com/48255575/70459069-6670e700-1a81-11ea-91ae-28a2c5a27d5a.png)

### The post will reload the single entry View:

![image](https://user-images.githubusercontent.com/48255575/70459631-966cba00-1a82-11ea-87f6-9c21047ea4fb.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1026165459/23839/

**Comment by soulseekah** [comment]
This wouldn't work with any ID actually. We barely implemented editing mode in #850 

We should be able to implement edit detection by URL and nonce on [gventry] usage without `edit="true"`...

Needs priority.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1305681927/29682

**Comment by verysiberian** [comment]
Hello! I hope that this gets fixed soon. I had a support ticket back in October 2020 about it. Thank you.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1890574347/41365
