### ISSUE TITLE
[gvlogic] Allow "and", "or", and "xor" conditions in the shortcode

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1397]
From [UserVoice](https://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/17908231-allow-and-condition-on-gvlogic-please), and also requested via email by a customer.

### Proposal

Add three new attributes to the `gvlogic` shortcode:

- `and`
- `or`
- [`xor`](https://en.wikipedia.org/wiki/Exclusive_or)

### Possible structure

Each new attribute would be used as the prefix for existing logical operators:

- `and` => `and_is`, `and_isnot`, `and_greater_than`, etc.
- `or` => `or_is`, `or_isnot`, `or_greater_than`, etc.
- `xor` => `xor_is`, `xor_isnot`, `xor_greater_than`, etc.

This would allow for complex logic:

```[gvlogic if="Microsoft" is="{Company:1}" or="XBox" or_is="{Company:1}" and="{Revenue:2}" and_greater_than="1000000"]```

This doesn't scale to multiple "or"s or "and"s, but it's much more.

---------

Note: I had a much nicer issue in the works, and then I lost it 🤦‍♂

**Comment by soulseekah** [comment]
...heh.. the idea is great, the proposed implementation is weird.

1. Only two conditions. What if we want 3 conditions? or_or? or_or_equals? etc.?

2. What about nesting and grouping?

The way to do complex server-side user logic right now is to register a custom merge tag and check it instead: `[gvlogic if="{custom_check}" is="1"]do it[/gvlogic]`. And do all the logic checks inside the merge tag replacement logic to output either "1" or "(empty)" .

It's near impossible to provide for 1 and 2 and keep the shortcode user-friendly. An option is to create a shortcode constructor that has a visual builder (think AF-style?) that generates an advanced JSON-based but base-encoded (we don't want [ ] characters to mess up our parser and the WordPress parser) query that is not meant for human editing and consumption directly in the shortcode.

Needs some serious thoughts. Maybe a document on how to achieve advanced logic using a tiny bit of code as explained above?

P.S. nobody uses xor :)

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1283258397/29271/
