### ISSUE TITLE
The "Use a form preset" button is not working on version 2.5.1

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1398]
![image](https://user-images.githubusercontent.com/1222472/71148467-caba4600-21f9-11ea-939e-f1e3565066c5.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1036570496/24053

**Comment by soulseekah** [comment]
This is probably part of #1392 somehow

**Comment by zackkatz** [comment]
I think it might be related to the accessibility stuff. @soulseekah changes in JS without HTML changes? I’ll check.

**Comment by soulseekah** [comment]
c43b8f2d0d08ecfdc99c764506e274ca881e8043 is the first bad commit according to bisect.

**Comment by soulseekah** [comment]
Fixed in latest.

**Comment by jlgrisham** [comment]
Tested with dev build. Form presets are back and working as expected.
