### ISSUE TITLE
Improve View editor loading time

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1407]
When adding multiple fields in a sequence to the View editor, it takes time for fields to be added. There's some sort of sluggish there in the Javascript action.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1041333314/24147?folderId=408730
https://secure.helpscout.net/conversation/1046428449/24378?folderId=408730
https://secure.helpscout.net/conversation/1045570217/24348?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers are all these customers with lots of forms? Commonalities?

**Comment by soulseekah** [comment]
Might be related to https://github.com/gravityview/GravityView/pull/1141

**Comment by rafaehlers** [comment]
@mrcasual That PR definitely worked for me! 👍

**Comment by jlgrisham** [comment]
Much, much faster.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2060727870/44631

**Comment by rafaehlers** [comment]
Reopening because that PR was never merged, we are still experiencing slowness with large forms.
