### ISSUE TITLE
Allow other users than the entry creator to edit an entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1430]
We had to requests today for the same feature with different use cases:

1) The first user wanted to assign the entry to a second user which will have the power to edit one field. (sort of like the "claim your entry" functionality, but not quite).

2) The second one wants two people to have control over the data of one entry.

Not sure how that'll be done, just writing this down for the future.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1100155411/25675/

**Comment by rafaehlers** [comment]
Related: https://gist.github.com/bennemann/21772eeb4457e70dd38404032ca27a4e

**Comment by zackkatz** [comment]
The Gist is likely enough for now; in the future, perhaps we can expose these types of permissions in the future.

@rafaehlers, please write a doc with the gist.
