### ISSUE TITLE
Single Entry Title is no longer working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1435]
As of GV 2.7.1 the Single Entry Title field doesn't work anymore:

![image](https://user-images.githubusercontent.com/1222472/77793065-378a7b00-7048-11ea-8b46-cb364a1f0914.png)

Tested with several WP default themes.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1120493215/26053/

**Comment by karlemilnikka** [comment]
Are there situations where this issue persist or should I file a new bug report since I experience exactly this issue? The chosen title is displayed when editing the single entry but not when viewing the single entry.
