### ISSUE TITLE
Wrong country variation on the names of the Danish language translation files 

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1438]
The Danish translation for GravityView isn't using the right country variation on the .po and .mo files.

They are currently named "gravityview-da"[.po/.mo] when they should be named "gravityview-da_DK"[.po/.mo]

**Comment by zackkatz** [comment]
Note: To fix, you add a language in Transifex https://www.transifex.com/katzwebservices/teams/18775/da_DK/
