### ISSUE TITLE
Editing an entry that used to be a partial entry, duplicates that entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1447]
How to reproduce:

1) Open a form with Partial Entries enable. Start filling it;
2) Wait until that entry turns into a Partial entry;
3) Once the partial is created, complete the rest of the form and submit it;
4) Go to GravityView and edit that entry.

![image](https://user-images.githubusercontent.com/1222472/80048031-61b74780-84e5-11ea-8735-2909dce70f7b.png)

Video: https://take.ms/9m3Wf
Tested on GV 2.8

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1143787087/26533

**Comment by trankevin** [comment]
@rafaehlers Just wondering if there's a solution for this?

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1176395900/27158?folderId=408730

**Comment by trankevin** [comment]
@bennemann sorry how do I access those links?

**Comment by rafaehlers** [comment]
@trankevin those are internal links, meant for our team only. There's no solution yet for this.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1203642212/27693/
