### ISSUE TITLE
Search Bar: add an anchor to the resulting URL in order to scroll to the results

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1459]
From a user:

>I am using a Gravity View that appears about half way down my page.
>
>When users search the View, the page reloads and returns to the top of the page, forcing users to scroll back down to the view to see the results of their search.
>
>Is there any way to stop this happening?

This is a recurring question.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1176059834/27152/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1459814289/33349/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1478834571/33747

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1603506806/36393/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1603506806/36393/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1792267958/39745

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2003112298/43354
