### ISSUE TITLE
Logged in user conditions

### ISSUE THREAD

**Issue by mfitzz10** [gravityview/GravityView#1462]
Is there a merge tag available to use for logged in users? 
For example: 
'Include results if **Any** match: 
Created by: **Logged in User** - OK
Supervisor [field]: **Logged in User** - Not available

**Comment by rafaehlers** [comment]
@mfitzz10 for support questions, please contact us at: https://gravityview.co/support/

**Comment by mfitzz10** [comment]
I’m working on a client’s site in which I do not have access to their gravity view account to log in to ask the support question

Please advise if possible

**Comment by zackkatz** [comment]
@mfitzz10 you can email support@gravityview.co
