### ISSUE TITLE
Modify [gravityview] shortcode to allow embedding edit entry directly.

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1463]
This is possible with oEmbed, but not with the shortcode, now that I'm looking at the code.

**Comment by arthurgloer** [comment]
Are there any plans to fix the shortcode?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1592827512/36207/

**Comment by zackkatz** [comment]
Ehlers says this is much more common than represented here.
