### ISSUE TITLE
Guest access to Edit. 

### ISSUE THREAD

**Issue by sugarfunk** [gravityview/GravityView#1465]
Maybe the functionality is there, but I can't figure it out. Is it possible to allow non-logged in users to submit edits on the front end that still require approval?

**Comment by sugarfunk** [comment]
https://gist.github.com/zackkatz/c0cc890ee311bab9893f47288e358b05 resolves

**Comment by sugarfunk** [comment]
Okay, so I can get non-logged in users access to edit, but it bypasses approval requirements and publishes without review. Can I have my cake and eat it too?

**Comment by rafaehlers** [comment]
FYI: https://www.gravitykit.com/announcing-gravityview-magic-links/
