### ISSUE TITLE
DataTables pagination doesn't work in GravityView v2.9

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1467]
When you try to change page the ajax call always returns the same dataset. 

This was also confirmed by @rafaehlers who made a video illustrating the issue:
https://monosnap.com/direct/CE8RXzeRHeUbRA6zpd1RwBgkSREiPz

It doesn't happen when using the Table layout but when downgrading GV to v2.8.1, DataTables pagination works as expected, so definitely a GV v2.9 issue and not a specific DataTables extension issue.

**Comment by zackkatz** [comment]
@soulseekah please investigate! This is due to the GF_Query moving PR.

**Comment by zackkatz** [comment]
Moving `GF_Query` was reverted, so it's "fixed".
