### ISSUE TITLE
View Settings > add option to redirect after deleting 

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1468]
Similar to what we have for after editing an entry:

![image](https://user-images.githubusercontent.com/1222472/85078315-8c96e280-b19a-11ea-90ca-97008414c6f2.png)

- Add a new Delete Entry tab to the View settings
- Add a new setting called `delete_redirect` based on `edit_redirect` https://github.com/gravityview/GravityView/blob/main/future/includes/class-gv-settings-view.php#L382-L394
- Clone https://github.com/gravityview/GravityView/blob/main/includes/admin/metaboxes/views/edit-entry.php (Update strings in the settings as needed)
- Replicate the [edit entry method](https://github.com/gravityview/GravityView/blob/main/includes/extensions/edit-entry/class-edit-entry-admin.php#L47) in [delete entry](https://github.com/gravityview/GravityView/tree/main/includes/extensions/delete-entry)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1199100107/27587

**Comment by shamalisulakhe** [comment]
Resolved https://github.com/gravityview/GravityView/tree/issue/1468-delete-entry-redirect

Added options for delete redirect - 
1. Redirect to multiple entries
2. Redirect to URL
