### ISSUE TITLE
Multisite update issues

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1471]
It seems that the updater class is not properly working on multisite environments. 2 clients reported already.

Related: https://github.com/gravityview/GravityView/issues/989 and https://github.com/gravityview/GravityView/issues/258

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1211916264/27812/

**Comment by zackkatz** [comment]
`#ZackClose` — this'll be addressed in Foundation.
