### ISSUE TITLE
All filter to control if Show Label is set by default

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1476]
A filter might do:

![DKWoJKu](https://user-images.githubusercontent.com/1222472/87830084-b8b78900-c856-11ea-8dec-59054a3e7dfd.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1228509576/28092

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1544585209/35213

**Comment by zackkatz** [comment]
This filter exists. @rafaehlers @bennemann.

Can one of you write a quick doc for this?

https://gist.github.com/zackkatz/80233bcc4aed12809205e9f22fb090cf
