### ISSUE TITLE
404 Errors from tippy.min.js.map files

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1482]
>DevTools failed to load SourceMap: Could not load content for https://xxxx.com/wp-content/plugins/gravityview/assets/lib/tippy/tippy.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

![image](https://user-images.githubusercontent.com/1222472/88750481-01f7ba80-d12c-11ea-9b05-ec272badd514.png)

**Comment by bennemann** [comment]
Same as [#1454](https://github.com/gravityview/GravityView/issues/1454)

**Comment by zackkatz** [comment]
Closed as duplicate
