### ISSUE TITLE
Add a "Bulk Action" field

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1483]
Edit by Zack: I've moved this issue [to its own repo](https://github.com/gravityview/Bulk-Actions)

**Comment by zackkatz** [comment]
@shamalisulakhe Please review and then let's discuss. 

Note: I planned for @mrcasual to handle the MySQL side in the "Processing entries" section. If you feel comfortable with that part, go ahead.

**Comment by rafaehlers** [comment]
For reference: https://secure.helpscout.net/conversation/1305736380/29684

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1295792584/29510/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1313738711/29829

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1363799662/31261

**Comment by mrcasual** [comment]
https://secure.helpscout.net/conversation/1378417762/31550
