### ISSUE TITLE
search bar match all fields

### ISSUE THREAD

**Issue by torkamanmahdi** [gravityview/GravityView#1501]
hi, in gravityview search bar with match all fields not working ! if you check match all fields or any just match any its worked.
i want work like this => **input text 1**  and   **input text 2**
see blow image: 
https://pasteboard.co/Jv0XhYz.png

**Comment by zackkatz** [comment]
Please check out this doc: 

And if that doesn't work for you, please try `add_filter( 'gravityview/search-all-split-words', '__return_false' );` and see if that works.
