### ISSUE TITLE
Password protection is not working

### ISSUE THREAD

**Issue by wordinvestor** [gravityview/GravityView#1519]
**Describe the Issue**
I add password protection on gravityview but when embed it to page and enter my password then it refresh page and ask for password again.
Sometime it show content in incognito windows without password.

--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [x] View
- [x] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[replace me]`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [ ] No

**If yes, please drag a screenshot below:**

**Comment by rafaehlers** [comment]
@wordinvestor the password should be set on the page where the [gravityview] shortcode is embedded, not on the View itself. For support issues, please use this form instead: https://gravityview.co/support/

**Comment by wordinvestor** [comment]
> @wordinvestor the password should be set on the page where the [gravityview] shortcode is embedded, not on the View itself. For support issues, please use this form instead: https://gravityview.co/support/

so how to prevent unauthorize views if google or any other search engine which do not obey noindex nofollow crawl that entry?

**Comment by rafaehlers** [comment]
@wordinvestor https://docs.gravityview.co/article/522-preventing-views-and-entries-from-being-by-the-google-crawler-bot
