### ISSUE TITLE
Improve membership plugin support

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1524]
I believe these are all related:

- [ ] #1451
- [ ] #939 
- [x] #1373
- [x] #946
- [x] #1070
- [x] #1526

We need to better support GravityView embedded inside random stuff.

Single entry context doesn't work in [LifterLMS branch](https://github.com/gravityview/GravityView/tree/feature/lifterlms) or gravityview/Admin-Views#5. I believe this is related to #1437: the context isn't being set early enough for things to render.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1329023618/30117

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1337077734/30255

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1383058226/31631/
