### ISSUE TITLE
Field dashicons showing up on the front-end View

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1529]
When adding a field to the View editor that contains a dashicon, upon saving the View, that icon shows up on the View:

![image](https://user-images.githubusercontent.com/1222472/98988544-941ea580-2506-11eb-9160-5d02b91cbadd.png)

and that icon is rendered this way on the View editor:

![image](https://user-images.githubusercontent.com/1222472/98988616-a993cf80-2506-11eb-9fc4-5cb40bdc7f8e.png)

Tested on GV 2.9.2.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1333275542/30187

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1349961206/30929

**Comment by rafaehlers** [comment]
![image](https://user-images.githubusercontent.com/1222472/101084268-7b952e80-358c-11eb-90ba-9bce84f1b72e.png)

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1361221744/31216

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1367005306/31314/
