### ISSUE TITLE
Search Bar: support Gravity Flow special fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1530]
At this moment, our search bar can't search on Gravity Flow fields.

Tested with GV 2.9.2.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1337706958/30277

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1515573100/34500/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1613147792/0/

**Comment by zackkatz** [comment]
Closing in favor of #1635
