### ISSUE TITLE
Custom redirect for go back, cancel, delete actions

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1556]
All of those are possible right now with filters, let's add them to the screen.

In Edit Entry settings tab:

- [x] Setting to change label for Edit Entry Link
- [x] Setting to change label for Cancel Link
- [x] Setting to change label for Delete
- [x] #1618

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1347149932/30854

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1381257940/31597

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1383168944/31633

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1407392440/32165

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1470164970/33561

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1490512520/0/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1540539919/35136/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1540547417/35137/
