### ISSUE TITLE
Add a Last Modified column to the View CPT list on Dashboard

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1566]
![image](https://user-images.githubusercontent.com/1222472/106812954-25f20680-664f-11eb-8e95-c0a762cac24e.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1415422977/32357?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers The Date column shows "Last Modified" for Views that have been modified since being published. If it's not been modified after being published, it shows the publish date.

See here:

![](https://i.gravityview.co/5DqlcB+)
