### ISSUE TITLE
Two levels of Conditional Logic are not respected in Edit Entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1568]
If you have a 3rd level of fields which visibility is based on a conditional logic from a 2nd level, modifying the 1st level won't hide the 3rd level. 

![image](https://user-images.githubusercontent.com/1222472/108291630-4c489380-7171-11eb-89c4-2ad1d00a642d.png)

The video explains it better: 

https://user-images.githubusercontent.com/1222472/108291802-9cbff100-7171-11eb-9308-b749af0bfd99.mp4

**Comment by rafaehlers** [comment]
A workaround is to add additional conditional logic to the third level to only show up if the 1st choice is also selected.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1420409817/32454

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1937208007/42274
