### ISSUE TITLE
When a License isn't Available, Like a Development Environment, this Line Doesn't have Proper Error Handling

### ISSUE THREAD

**Issue by timnolte** [gravityview/GravityView#1575]
https://github.com/gravityview/GravityView/blob/e9e8411f364badb778cc437f56c5f57dfb2cbd93/includes/presets/register-default-templates.php#L106

> Notice: Undefined index: price_id in wp-content/plugins/gravityview/includes/presets/register-default-templates.php on line 106

**Comment by zackkatz** [comment]
The for the report! We'll get this fixed.

**Comment by zackkatz** [comment]
@timnolte Thanks again. This is fixed in 2.10.2, just released.
