### ISSUE TITLE
Not possible to sort by entry ID

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1581]
Since 2.10 clicking on the link to sort by Entry ID no longer works:

![image](https://user-images.githubusercontent.com/1222472/111550537-150fd700-875d-11eb-8f21-961ff26f30ef.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1456345553/33261/

**Comment by zackkatz** [comment]
@rafaehlers are you sure this worked in 2.9?

**Comment by zackkatz** [comment]
Sorting works in `2.9.4` but not in `2.10`.

```
WordPress database error: [Unknown error 1054]
SELECT SQL_CALC_FOUND_ROWS DISTINCT `t1`.`id` FROM `wp_gf_entry` AS `t1` WHERE (`t1`.`form_id` IN (19) AND `t1`.`status` = 'active') ORDER BY `t1`.`id` ASC, CAST(`c2`.`id` AS DECIMAL(65, 6)) ASC LIMIT 25
```
