### ISSUE TITLE
"Change Entry Creator" selectWoo assets are only loaded when site language is set to English

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1583]
The selectWoo library and the admin-entry-creator.js files are only loaded when the site language is set to English.

It seems we expect `$current_screen->base` to be 'forms_page_gf_entries' to enqueue these assets, but that value changes with the language (e.g. 'formulare_page_gf_entries' for German).

https://github.com/gravityview/GravityView/blob/e9e8411f364badb778cc437f56c5f57dfb2cbd93/includes/class-gravityview-change-entry-creator.php#L61

**Comment by zackkatz** [comment]
Nice catch, @bennemann !!

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1462396794/33405
