### ISSUE TITLE
Option to "Open link in a new tab or window?" not available since v2.10

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1587]
User request:

> On the multiple entries layout, when making a column a link to the single entry, we used to have the option to open the single entry in a new tab. That option is no longer there. It was nice to just have a check box to make it so.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1472711049/33613

**Comment by zackkatz** [comment]
Sorry, @bennemann! Closed with 7e153f84.
