### ISSUE TITLE
The gform_after_submission hook doesn't trigger Zapier feeds anymore

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1598]
It seems like the latest version of the Zapier add-on was updated and our code here: https://docs.gravityview.co/article/534-trigger-feeds-edit-entry doesn't work anymore.

Message from a user:

> I know they updated gravity forms and zapier add on to trigger gravitys REST API instead of a feed.

Here's the latest changelog:

```
### 4.0 | 2021-02-23
- Added support for the Gravity Forms Integration App on Zapier v2.0.
- Added an add-on setting to toggle the display of Zapier Feeds in the form settings. On sites with legacy feeds created for the Zapier v1.0 integration, this setting is enabled by default, displaying all the feeds. On sites with no legacy feeds, this setting is off by default so the feeds will not be displayed.
- Fixed compatibility issues in PHP 8.
- Updated the feed settings to restrict editing of feeds created in the Zapier v2.0 integration to Admin Labels and Conditional Logic.
- Updated the add-on to use the Gravity Forms Add-On Framework.
```

Tested with GF 2.5 and GV 2.10.2.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1499516617/34160/

**Comment by zackkatz** [comment]
@mrcasual Let's fix this tomorrow

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1511288821/34409

**Comment by rafaehlers** [comment]
@mrcasual FYI it seems the Webhooks add-on isn't working either. Might be related: https://www.gravityforms.com/add-ons/webhooks/

Ref: https://secure.helpscout.net/conversation/1516176590/34515/

**Comment by rafaehlers** [comment]
New code samples can be found here: https://docs.gravityview.co/article/534-trigger-feeds-edit-entry
