### ISSUE TITLE
Approve an entry with a link sent via an email notification

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1603]
In GravityView, there’s a concept of [entry approval](https://docs.gravitykit.com/article/88-approving-or-rejecting-entries-in-gravityview). Customers want an easy way to approve an entry from the confirmation email. This ticket is designed to accomplish that.

Check out how Gravity Flow implements this. Use that as a starting point.

- Requires logged-in by _default_, with an option in the merge tag to allow anyone to approve entries (public).
  - Add site-wide GravityView setting to enable `public` modifier, since this is a potential security risk. **Disabled by default.**
  - Add per-form setting to enable `public` modifier. This setting should use the site-wide default by default.
- The link should go to the Gravity Forms "Entries" table for the form by default
  - Add per-form setting to override the redirect URL
- Make link valid for 24 hours by default.
  - Add Merge Tag modifier to adjust timeframe
- Use a nonce
- Store values in options table (not transients), check against time
- Add a salt constant when generating links that can be changed (rotated) if there is a security issue.
- Make sure to verify that the approval request is valid

### Merge Tags

- `{gv_approve_entry}` Link to approve an entry
- `{gv_disapprove_entry}` Link to *dis*approve an entry
- `{gv_unapprove_entry}` Link to *un*approve an entry (reset approval) 

### Modifiers

- `:[\d+d|h|m|s]` Number followed by unit (`d` day, `h` hour, `m` minute, `s` second) of hours the approval link is valid for. `24h` by default.
- `:public` Make the link clickable by anyone, even users who are logged-out. (Requires either site-wide or per-form setting to be enabled).

#### Example usage

  - `{gv_approve_entry}` - Valid for default (24 hours). Private.
  - `{gv_approve_entry:48h}` - Valid for 48 hours. Private.
  - `{gv_approve_entry:20m}` - valid for 10 minutes. Private.
  - `{gv_approve_entry:public}` - Valid for default (24 hours), public
  - `{gv_approve_entry:2h:public}` - valid for 2 hours, public
  - `{gv_approve_entry:20m:public}` - valid for 20 minutes, public

The same modifers will be available for `{gv_disapprove_entry}` and `{gv_unapprove_entry}`.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1520777665/34633/

**Comment by zackkatz** [comment]
This is more like a medium/small ;-) 👕

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2129159026/46397/
