### ISSUE TITLE
Field Picker is not pulling string translations

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1610]
![image](https://user-images.githubusercontent.com/1222472/122111359-084f5d80-cdf6-11eb-9509-221a8d92fde1.png)

Tested with GV 2.10.3.2 and GF 2.5.5.1 and language nl_NL

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1544109602/35195

**Comment by zackkatz** [comment]
We were hooking to `init`, but we were already at `init`. For some reason, this wasn't working…

This has been fixed with 0e05354ad

![](https://i.gravityview.co/uPZMcs+)
