### ISSUE TITLE
[gravityview detail="total_entries"] doesn't work when [gravityview] is embedded

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1612]
Whether it's on a page or on a post, when the View is embedded, the [gravityview detail="total_entries"]  doesn't work:

![image](https://user-images.githubusercontent.com/1222472/122290460-22f30680-ceca-11eb-98b2-258a39b91155.png)

It only works when accessing the View directly:

![image](https://user-images.githubusercontent.com/1222472/122290625-546bd200-ceca-11eb-8a89-5f149b19e9c4.png)

Tested with GV 2.10.3.2 and GF 2.5.5

ps.: Adding the View ID in the id attribute makes it work: `[gravityview id="8" detail="total_entries"]`

For reference: https://docs.gravityview.co/article/73-using-the-shortcode

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1544366761/35207/

**Comment by mrcasual** [comment]
Not a bug. I've updated [our documentation](https://docs.gravityview.co/article/73-using-the-shortcode) and informed the customer.
