### ISSUE TITLE
Gravity Forms 2.5.6.4 vanished with the delete button for file upload fields on Edit Entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1619]
## Gravity Forms 2.5.6.4

![image](https://user-images.githubusercontent.com/1222472/125524476-a7dfc7a2-c428-418c-aea8-3bc44b4059d0.png)

## Gravity Forms 2.5.6.3

![image](https://user-images.githubusercontent.com/1222472/125524621-917a7245-215c-4dc7-af24-8873e38dbbec.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1569339937/35706

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1569972866/35720

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1571573825/35750

**Comment by zackkatz** [comment]
I responded to the customers.
