### ISSUE TITLE
Switch check mark dashicon to check mark emoji so it appears when printing

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1623]
When using the Print button of DataTables, default check marks (dashicons) don't show up:

![image](https://user-images.githubusercontent.com/1222472/125644268-0136fa07-281c-437e-a290-d5b279850079.png)

## Print

![image](https://user-images.githubusercontent.com/1222472/125644355-ee5ab832-c88e-4471-aaa9-aa58a962bba0.png)

The current solution is to use this filter and switch the check mark to an emoji:

```
add_filter( 'gravityview_field_tick', 'gv_modify_field_tick', 10, 4);
function gv_modify_field_tick(  $output, $entry, $field, $gravityview  ) {
	$output = '✔️';
	return $output;
}
```

**Comment by zackkatz** [comment]
Released in DT.
