### ISSUE TITLE
State / Province field set up as dropdown show up as simple input on front-end search bar

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1626]
State / Province field on Search Bar as Select (dropdown) 

![image](https://user-images.githubusercontent.com/1222472/126843470-ea899111-4959-46d8-a44a-d4867748e7eb.png)

...now shows up on the front-end as a simple input:

![image](https://user-images.githubusercontent.com/1222472/126843447-1614e51a-cb5f-474b-8241-eb4e33dd0730.png)

Reproducible: https://try.gravityview.co/demo/view/map/
Tested with GV 2.11 and GF 2.5.7

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1580135372/35936

**Comment by zackkatz** [comment]
This is likely because the field Address Type is set to International.

[See the doc here](https://docs.gravityview.co/article/818-search-bar-why-is-the-state-input-is-showing-as-a-text-field)
