### ISSUE TITLE
Fancybox Gallery: Items are duplicated when the File Upload field is hidden by DataTables Responsive Mode

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1627]
Here's the issue reproduced:
https://debug.gravityview.co/blog/view/fancybox-test/

There are only three images uploaded but once an image is clicked, Fancybox thinks there are six.

It only happens if the field starts out hidden behind the (+) sign from DataTables responsive mode.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1582227598/35972

**Comment by rafaehlers** [comment]
Similar to all these other issues related to the Responsive Mode of DT:
https://github.com/gravityview/DataTables/issues/144
https://github.com/gravityview/DataTables/issues/126
https://github.com/gravityview/DataTables/issues/142
