### ISSUE TITLE
File Upload fiels when hidden by conditional logic on Edit Entry don't delete their values

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1628]
When editing an entry, if you choose an option that hides a file upload field already filled, the field keeps the information.

https://user-images.githubusercontent.com/1222472/127050187-ba321095-3bba-45da-a55a-d7de71985218.mp4

Tested on GF 2.5.7 and GV 2.11
[gravityforms-export-2021-07-26.zip](https://github.com/gravityview/GravityView/files/6880823/gravityforms-export-2021-07-26.zip)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1580831025/35950

**Comment by mrcasual** [comment]
That's how GF works; just updating the conditional field value is not enough and files need to be explicitly deleted. I responded to the customer with an explanation and provided a possible workaround.
