### ISSUE TITLE
Updating entry may erase previously uploaded files

### ISSUE THREAD

**Issue by mrcasual** [gravityview/GravityView#1629]
Happens when the following conditions are met:

1) GF 2.5.8 is used
2) Form has a file upload field w/"multiple files" option enabled
3) Entry is saved without making any changes to the file upload field

Related [HS ticket](https://secure.helpscout.net/conversation/1570448572/35727/).

**Comment by rafaehlers** [comment]
>Hi guys,
after a GF update 2.5.8 I have problems with the uploaded images again.
I have on 2021/7/15 ever had a problem with it that you fixed.
>
>I'm trying to explain it so you can understand :
>1. Edit entry: upload a image and save the entry:
Result: Single view display the image and edit entry show the existing image - everything is ok
>
>Now
>2. Edit the same entry and save it.
Result: Single view display the image but edit entry dont show the existing image
Problem: User cant see that there is a existing image in edit mode and other problems with conditional logic in single view
I look in developer tools and I see there are no files in container for preview_existing_files 

>Gravity Forms has introduced some changes in the latest (2.5.8) release that result in the previously uploaded files being erased when updating the entry.
