### ISSUE TITLE
Search Bar: Have the ability to search phone numbers even without spaces or parentheses ()

### ISSUE THREAD

**Issue by jonaaa26** [gravityview/GravityView#1661]
At the moment, when you search a phone number without spaces or parentheses () using the Search Bar, it will return a "no results found."

However, adding spaces or parentheses () similar to the phone number format when you perform your search will successfully return results.

The customer would like to have the ability to search phone numbers even without spaces or parentheses ()

**Comment by mrcasual** [comment]
@jonaaa26 are the phone numbers that are saved in the database formatted the same way (e.g., using GF's `(###) ###-####` format)?

**Comment by jonaaa26** [comment]
@mrcasual In my test site, the test phone numbers I used are saved based on Gravity Forms format for phone numbers. - https://share.getcloudapp.com/yAukWyQG

**Comment by mrcasual** [comment]
@jonaaa26 since you're using a predefined format, I can offer the following solution:

```php
add_filter( 'gravityview_fe_search_criteria', function ( $search_criteria ) {
	if ( empty( $search_criteria['field_filters'] ) ) {
		return $search_criteria;
	}

	foreach ( $search_criteria['field_filters'] as &$filter ) {
		if ( !is_array($filter) || '1' !== $filter['key'] ) { // Replace 1 with your phone field ID
			continue;
		}
		
		$phone = preg_replace( '/\D+/', '', $filter['value'] );

		if ( 10 === strlen( $phone ) ) { // 
			$filter['value'] = preg_replace( '/(\d{3})(\d{3})(\d{4})/', '($1) $2-$3', $phone );
		}
	}

	return $search_criteria;
} );
```

This will strip all non-numeric characters from the search value and then reformat the string using the `(###) ###-####`, which should match the value stored in the database. You should now be able to use various search terms, such as `1112223344`, `111-222-3344` or `(111) 222-33-44`.
