### ISSUE TITLE
"Open in new tab/window" checkbox is missing from Link to Single Entry and Link to Edit Entry links

### ISSUE THREAD

**Issue by courtneyhuber** [gravityview/GravityView#1667]
This issue was supposedly resolved in the 2.10.2 release: https://github.com/gravityview/GravityView/pull/1591

HOWEVER, I'm currently running 2.14 and am no longer seeing this option. I've got a previously set up GravityView that is opening in a new tab on the first tab of the table, but any subsequent tabs duplicated from the original are not and there is no option to select to make them open in a new tab.

![Screen Shot 2021-12-30 at 7 37 19 AM](https://user-images.githubusercontent.com/96789309/147756884-6dc0718f-9c42-4039-a9bb-4be32d8e4e1c.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1742557219/38857/
