### ISSUE TITLE
The Gravity Forms widget loses reference of the source form after saving the View

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1681]
Steps to reproduce:

1) Add a Gravity Forms widget to any widget zone
2) Pick a form
3) Save the View
4) Upon reload of the View Editor, the reference of the source form is gone:

![image](https://user-images.githubusercontent.com/1222472/153080564-77586388-400d-4b08-a3f6-e975937618cd.png)

### Video

https://user-images.githubusercontent.com/1222472/153080678-8e62f47f-33f6-49d9-a098-fcfc6f9876ae.mp4

Tested on GV 2.14.1 and GF 2.5.16

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1780201619/39576

**Comment by rafaehlers** [comment]
Somewhat similar: https://github.com/gravityview/GravityView/issues/1634

**Comment by mrcasual** [comment]
Fixed by 6c536f472109cdc6b1e428e7466f11ca9387bdb1. Customer notified.
