### ISSUE TITLE
Search Bar breaks in 2.14.2 - Limiting results

### ISSUE THREAD

**Issue by endymion0000** [gravityview/GravityView#1689]
My Search Bar on a View page is set to Match All Fields.

Before one could enter in / select option for a couple of choices and leave the rest blank and you would get results that match what was entered / selected.

With the 2.14.2 update, it appears that it's looking for the blank search fields to match as blank in the entries which gives me limited to no results for searches because many entries are not blank for those search fields.

In the attached screen shot I used to be able to set Service to just Crew or Support to get a complete list of results. Now selecting Support returns no results.

Reverting to 2.14.1 works as expected.
<img width="1162" alt="Screen Shot 2022-03-11 at 4 19 58 AM" src="https://user-images.githubusercontent.com/7957532/157838739-ff62b313-ab72-4caa-b04b-9d1702706da1.png">

**Comment by mrcasual** [comment]
@endymion0000 thank you for bringing this to our attention; we released [v2.14.2.1 ](https://github.com/gravityview/GravityView/releases/tag/v2.14.2.1) with the fix.
