### ISSUE TITLE
AJAX 403 Error issue when trying to dele a file upload in Edit Entry page

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1702]
It appears that Gravity Forms changed something in version 2.6.1 that is now requiring the `Delete Entry` capability in order for non-admins to delete a file uploaded inside Gravity View's Edit Entry page. 

The problem when adding that capability is that the Delete button now shows up on the page regardless if this is allowed in the View Settings or not.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1835607490/40579

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1829119377/40475

**Comment by amuhareb** [comment]
yep! i'm having this issue too. we've had to disable file uploading as a result. i'd love to disable entry deletion while still allowing users to delete/replace photos they upload.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1843757710/40712/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1844691892/40730

**Comment by amuhareb** [comment]
awesome! thanks so much

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1847169951/40772

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1847171083/40773/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1861839240/40934
