### ISSUE TITLE
GF 2.6.x styling issue with Merge Tag dropdowns

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1703]
If GravityView's No-Conflict mode is activated, these won't show at all. Disabling the No-Conflict mode makes them appear but with styling issues:

![image](https://user-images.githubusercontent.com/1222472/162485014-ef20370c-cda0-45f6-add1-cb3846dbb959.png)

Tested on GF 2.6.1 and GV 2.14.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1840345045/40681

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1842765519/40702
