### ISSUE TITLE
Search Bar Widget: Can't add fields properly

### ISSUE THREAD

**Issue by bennemann** [gravityview/GravityView#1717]
Once the user adds any field and saves the View, it'll actually add the next field in the fields' dropdown that wasn't added yet. 

For example, in the image below, if a user tries to add the "Business Name" field, the field that's actually added once the View is saved is the "Search Everything" field. 

![image](https://user-images.githubusercontent.com/5726194/168628979-0c62880d-9c7d-4954-915d-cf3b95a8db35.png)

If the process is repeated, and the user tries to add the "Business Name" field again, it will actually add the "Entry Date" field (since "Search Everything" is already added).

Then it will add "Entry ID", "Entry Creator", and so on. 

Here's a quick video:
https://monosnap.com/direct/gwcg3av4PEMqMkSFjS0qJ6VafLkJAq

This issue only affects our latest release (v2.14.5) and can be reproduced here:
https://debug.gravityview.co/wp-admin/post.php?post=530&action=edit

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1891135758/41376/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1892237783/41389/
