### ISSUE TITLE
It is not displaying properly in the front page

### ISSUE THREAD

**Issue by Reniel80** [gravityview/GravityView#1724]
**Describe the Issue**

I'm using xampp 8.1.6 , wordpress 6 and i only have Gravity Forms 2.6.3 and gravityview 2.14.5 plugins installed... gravityviews is showing a blank page in frontend. 
--------

### Additional information

**This issue happens in the following settings:**

Even with Table View or Listing View.... I've used shortcodes and also editing it.. i can't see a preview with the View link.

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [x] View
- [x] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

[gravityview id='6'] 

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

**If yes, please drag a screenshot below:**

**Comment by rafaehlers** [comment]
Hi @Reniel80 this might be related to PHP 8.1, please downgrade to PHP 8.0 (or older versions) on your local XAMPP install and GravityView will work. 

We are still working on support for PHP 8.1

**Comment by zackkatz** [comment]
@Reniel80 This is fixed in [GravityView 2.15](https://github.com/gravityview/GravityView/releases/tag/v2.15). Thank you for reporting!
