### ISSUE TITLE
Allow custom ALT attribute for File Upload fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1741]
If a file upload field contains an image, allow the option to customize its ALT attribute. If possible by using Merge Tags as well.

![image](https://user-images.githubusercontent.com/1222472/186271748-96ecf372-ceda-4bae-9e24-9c62fd8163e2.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1986243753/43071

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1986243753/43071

**Comment by harmsway14** [comment]
I second this, thank you!

**Comment by harmsway14** [comment]
Thank you!

**Comment by zackkatz** [comment]
@rafaehlers How do you suggest this would work with Multiple File Upload?

Or would it only show for a single image?

**Comment by harmsway14** [comment]
@zackkatz - isn't the image field a separate field housing only one photo? 

An alternative option would be to write a function much like the URL rewrite slug function (https://docs.gravitykit.com/article/57-customizing-urls) that would pull the entry from a certain field that describes the image.

**Comment by zackkatz** [comment]
@harmsway14 This is coming in the next release. Thanks for the suggestion!

This also is overrideable using the `gravityview/fields/fileupload/image_atts` filter. But having this in the UI makes sense.
