### ISSUE TITLE
Edit Entry breaks Poll results displayed on the backend

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1748]
When updating a choice in a Poll field via Edit Entry, the new choice/value is correctly stored, but when visualizing the entry on the Entries page, the graph is not updated.

https://user-images.githubusercontent.com/1222472/190827669-f86f705c-dc11-4426-bce5-c2190c86e237.mp4

View to test: https://debug.gravityview.co/view/polls/

Tested with GV 2.14.7 and Polls 3.7

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2011964557/43571/

**Comment by zackkatz** [comment]
Closed with 88a7760fedea2df4bf971f03f53058247ea44f6b
