### ISSUE TITLE
Edit mode of the `[gventry]` shortcode doesn't parse field merge tags

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1756]
If we add a custom content field to the Edit Entry page of a View and use any field Merge Tags inside, there's no output when displaying the edit form using the `[gventry edit="1"]` shortcode.

![image](https://user-images.githubusercontent.com/1222472/192904011-5dcaf3ea-1f29-4482-8604-e02331838898.png)

Example: https://debug.gravityview.co/gventry-edit-merge-tag/
This page has this shortcode: `[gventry view_id="2452" entry_id="last" edit="1"]` 

![image](https://user-images.githubusercontent.com/1222472/192904035-f6f2c2cb-2af2-49a2-8775-69f549baf9ad.png)

Accessing the Edit Entry page directly on the View:

![image](https://user-images.githubusercontent.com/1222472/192904125-8b96413d-56b0-402b-abad-f5a007df17fe.png)

Tested on GV 2.15
Related: [Embedding the Edit Entry form into a Page or Post](https://docs.gravitykit.com/article/845-embedding-the-edit-entry-form-into-a-page-or-post)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2022113473/43830

**Comment by zackkatz** [comment]
The issue: `GravityView_Field_Custom::show_field_in_edit_entry()` doesn't know we're inside Edit Entry. 

`\GV\Request::is_edit_entry()` doesn't have filters that work; it needs both `is_entry()` and the `gravityview_is_edit_entry` filter to be `true`.
