### ISSUE TITLE
"Form is not defined" JS error when creating a new View w/GF 2.6+

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1763]
Using GF 2.7 beta with any version of GV:

1. Go to "New View" screen
2. Check the error console: "Can't find variable form"
3. Select a form in the Data Sourec dropdown
4. Save the View
5. Refresh the page
6. The error is gone

![](https://i.gravitykit.com/i/YmeRi3+)

**Comment by zackkatz** [comment]
The issue is somehow related to `GFCommon::gf_vars()`, which is called from `GravityView_Admin_Metaboxes::render_merge_tags_scripts()`.

**Comment by mrcasual** [comment]
@zackkatz this error has been happening since GF 2.6
