### ISSUE TITLE
search url in homepage

### ISSUE THREAD

**Issue by donnison** [gravityview/GravityView#1765]
I have a view shortcode attached in a profile page, which has a date search bar, but whenever I press search the url with the parameters opens the home page not the page I have the shortcode embedded in.

**Comment by zackkatz** [comment]
Hi @donnison, please set the `post_id` parameter in the shortcode to the ID of the profile page. That should fix it. If not, please reach out to support@gravitykit.com!

```
// This shows how to embed using form ID #5 and page ID #123. Replace with your values!
[gravityview id="5" post_id="123" /]
```
