### ISSUE TITLE
Multi-file upload doesn't work

### ISSUE THREAD

**Issue by omarkasem** [gravityview/GravityView#1766]
#https://github.com/gravityview/GravityEdit/issues/204

**Comment by zackkatz** [comment]
@omarkasem Can you please test with this build of GravityView? https://www.dropbox.com/s/hkfzn8ygtmm5q0m/gravityview-2.16-634fdf458.zip?dl=1

**Comment by omarkasem** [comment]
@zackkatz I tried that build but it still showed the same fatal error.
