### ISSUE TITLE
Warnings in php8

### ISSUE THREAD

**Issue by Chandru-developer** [gravityview/GravityView#1774]
Hi Team,

We are facing the following errors after updating our site to php8.

1) Required parameter $object_id follows optional parameter $value
wp-content/plugins/social-sharing/includes/services/jetpack.php:90
2) Required parameter $post_id follows optional parameter $is_open
wp-content/plugins/gravityview-ratings-reviews/includes/class-review.php:758
3) Required parameter $property_value follows optional parameter $entry_id
wp-content/plugins/gravityview-ratings-reviews/includes/class-review.php:206
4) Required parameter $form_id follows optional parameter $parameters
wp-content/plugins/gravityview-featured-entries/class-gravityview-featured-entries.php:284
5) Required parameter $property_value follows optional parameter $entry_id
wp-content/plugins/gravityview-ratings-reviews/includes/class-review.php:206
6) Required parameter $form_id follows optional parameter $args
wp-content/plugins/gravityview-featured-entries/class-gravityview-featured-entries.php:183

Can you guys please take a look on it.

Thanks.

**Comment by zackkatz** [comment]
>>> Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in [...]/gravityview/future/includes/class-gv-plugin.php on line 726

@mrcasual Can you see how to fix this one in 2.16? There's some logic I'm unclear on.

**Comment by mrcasual** [comment]
@zackkatz fixed in https://github.com/gravityview/GravityView/commit/e3b6053393e861ac701faac529356d581e54a560
