### ISSUE TITLE
DatePicker (edit entry) doesn't work on 2022 and 2023 WP themes

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1786]
![image](https://user-images.githubusercontent.com/1222472/205752214-6c31ea7e-d71d-4e0d-97e3-f0754e8e6d9c.png)

For some reason, in these two themes, jQuery loads outside the `<head>` tag, thus generating these errors:

![image](https://user-images.githubusercontent.com/1222472/205751885-4163a5b8-0ded-4ade-b4e0-1acf40553cd9.png)

![image](https://user-images.githubusercontent.com/1222472/205752098-a8aea9d7-e44a-4500-994c-9762a0878d5b.png)

Tested with GV 2.16.0.2 and GF 2.6.8

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2087872870/45519/

**Comment by mrcasual** [comment]
Fixed in https://github.com/gravityview/GravityView/commit/48fbfb151f10d5758b68b1bafb862d4947d818d2
