### ISSUE TITLE
GV styles not loaded for logged-in users from a subsite

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1793]
This Multisite Network has two websites: Main and Sub. https://fish-shrew-liga.try.gravitykit.com/wp-admin/network/sites.php

The View is located on the Main website: https://fish-shrew-liga.try.gravitykit.com/blog/view/test/

There are two users on this network: The `Network Admin` and the `sub` user assigned to the `Sub` website: https://fish-shrew-liga.try.gravitykit.com/wp-admin/network/users.php

If you log in with the `sub` user, and visit that View, GV default styles won't load, but if you access that View while non-logged-in, the View styles are correctly loaded.

Video: https://www.loom.com/share/f36917e4374245239795adc4910048b7

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2103606969/45886/

**Comment by zackkatz** [comment]
Resolved in 24f576b1f629549e0314e63b3d6507e44e8ac1d3
