### ISSUE TITLE
gventry edit="1" doesn't work for non-admin roles

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1803]
Trying to use the `[gventry edit="1"]` to display the edit entry page for non-admin roles results in the message below:

>You do not have permission to edit this entry. [Go back.](http://gravitykit.local/gventry/#)

Video: https://www.loom.com/share/daed3fbbfce2491e85bb99880cba7023

## Steps to reproduce:

1) Create a simple form with just one field;
2) Submit two entries, one as an administrator and another as a subscriber;
3) Create one simple View for this form;
4) Add `created by - currently logged-in user`  filter to that View
5) Create a new page and type the `[gventry view_id="x" edit="1" entry_id="first"]` shortcode inside;

## Outcome expected:

When users visit that page, you'll see the edit entry page for that View. As described here: https://docs.gravitykit.com/article/845-embedding-the-edit-entry-form-into-a-page-or-post

## What's happening:

The administrator can see the Edit Entry page, but the Subscriber cannot.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2132401975/46474

**Comment by mrcasual** [comment]
This is an incompatibility issue with the [Canvas theme](https://themes.woocommerce.com/canvas/). Related to #1437. No solution.
