### ISSUE TITLE
Add "No Entries Behavior" option to hide the View

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#1817]
[This doc shouldn't be necessary](https://docs.gravitykit.com/article/410-hiding-the-no-entries-match-your-request-message).

> What happens in the event that lets say there are no entries for one of them, is there any way to make the entire view hidden unless there is an entry? Otherwise it will look funny with just a title and nothing under it.

See customer request here: https://secure.helpscout.net/conversation/2149120650/46838?folderId=408730

**Comment by rafaehlers** [comment]
In that case, the table was hidden with CSS but the "title" was an `<h2>` inside a Custom Content **Widget** and widgets aren't hidden by that CSS mentioned in that doc.

I had to use: 

`.gv-widgets-no-results div.gv-widget-custom-content { display: none; }`
