### ISSUE TITLE
Select all entries Bulk Approval not working

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#182]
In Gravity Forms, you check the box to select all visible entries and it gives an option to check all boxes. When bulk approval is processed, only visible are processed, not all entries.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995598102257631)

**Comment by soulseekah** [comment]
Did this break?

**Comment by zackkatz** [comment]
I tried last night and it didn’t work. Just first page for reset approval.

**Comment by soulseekah** [comment]
Works okay for me. Make sure you're clicking the "Select All" notice that pops up.

![image](https://user-images.githubusercontent.com/685880/52795865-810e4580-3094-11e9-8603-f357241a1151.png)

Please confirm? Seems like a JS issue if it is an issue. Backend-wise it's working okay.

**Comment by zackkatz** [comment]
Yep, this works for me again.
