### ISSUE TITLE
Double icon showing up on field settings modal window (the X button)

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#438]
![double-x](https://cloud.githubusercontent.com/assets/1222472/9097018/3e78e342-3b97-11e5-999d-6ea59b022f09.png)

WordPress version 4.2.4
GV Version 1.11.2
GF Version 1.9.12.12
No-Conflict Mode Off for both GF and GV
No other plugins installed

**Comment by m-e-h** [comment]
I'm getting this too.

Basically Wordpress is using Dashicons
https://github.com/WordPress/WordPress/blob/master/wp-includes/css/jquery-ui-dialog.css#L308-L318

and 

GV is using an image
https://github.com/katzwebservices/GravityView/blob/master/assets/css/admin-datepicker.css#L12

GV could instead do the following and over-ride jquery-ui-dialog.css
```
.ui-state-default .ui-icon:before {
	font: normal 20px/1 'dashicons';
	vertical-align: top;
	speak: none;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	line-height: 36px;
	width: 36px;
	height: 36px;
	content: '\f158';
}
```
Really, it doesn't look like there's anything in that particular sprite image that couldn't be handled by Dashicons anyway.

I'm happy to help do pulls or whatever if you wanna switch to Dashicons.

**Comment by zackkatz** [comment]
@m-e-h A PR would be great, thanks! If you want, you can just do a PR [on admin-tooltips.scss](https://github.com/katzwebservices/GravityView/blob/master/assets/css/scss/admin-tooltips.scss) and we'll build the CSS file.

Thanks!

**Comment by m-e-h** [comment]
That PR is definitely just a quick fix to get rid of the double x. I'm not that familiar with GV yet so I didn't want to do anything with the images. 
Personally, I'd probably try to use all Dashicons and get rid of the sprites. Though that could be tedious :hourglass:
Btw, what branch do you prefer PRs?

**Comment by zackkatz** [comment]
@m-e-h Thank you for submitting a fix! It'll be in the next release.

Do you mind doing another PR on the `develop` branch? That's where all PRs should take place.
