### ISSUE TITLE
The `desc` admin field setting key gets converted to tooltip

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#487]
It should be displayed using `GravityView_FieldType->get_field_desc()` but it gets converted to a tooltip for some reason.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995620855936552)

**Comment by zackkatz** [comment]
Turns out it wasn't a bug, it was a feature. To be fixed soon.

**Comment by zackkatz** [comment]
![Not a bug, it's a feature](https://cloud.githubusercontent.com/assets/870979/9673829/988701c2-5265-11e5-86cc-ab55d30ef2a7.jpg)

**Comment by rafaehlers** [comment]
Not an issue anymore after the refactor of the View editor.
