### ISSUE TITLE
JS Error - "GForm is not defined" when using date search fields

### ISSUE THREAD

**Issue by Idealien** [gravityview/GravityView#544]
"ReferenceError: gform is not defined
optionsObj = gform.applyFilters('gform_datepicker_options_pre_init', optionsObj,..."

The file /wp-content/plugins/gravityforms/js/datepicker.js?ver=1.3.9 is loaded successfully

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995626339219184)

**Comment by zackkatz** [comment]
@Idealien Thanks for reporting!

**Comment by zackkatz** [comment]
@rafaehlers I've not been able to reproduce, have you?

**Comment by zackkatz** [comment]
Closing due to how old this is.

**Comment by SuchiMehta26** [comment]
I m facing the same issue , anyone pls tell me how to solve this

**Comment by rafaehlers** [comment]
@SuchiMehta26 please contact our support so we can check this for you: https://www.gravitykit.com/support/
