### ISSUE TITLE
Switch labels for "Clear" and "Reset" in search bar

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#553]
Consider switching the text labels: 
- Clear should be clear all values.
- Reset should be restore original values.

See https://secure.helpscout.net/conversation/125704342/3506/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995627295253312)

**Comment by soulseekah** [comment]
Restore to what? We don't support non-empty defaults in our search filters.

**Comment by zackkatz** [comment]
Reset to "original values" meaning any pre-filled fields that were set due to an existing search result.

**Comment by soulseekah** [comment]
> Reset to "original values" meaning any pre-filled fields that were set due to an existing search result.

Makes sense, thanks for the clarification.

**Comment by rafaehlers** [comment]
Fixed with: https://github.com/gravityview/GravityView/pull/1624
