### ISSUE TITLE
Search may not work in shortcode when passing search attributes

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#572]
> ...you can only search the field that is being used to generate the View

Two fields: City and Business Name

1. Create a View using Advanced Filter that limits visibility to specific City: `[gravityview id="19" search_field="1" search_value="Los Angeles"]`
2. Use the Search Bar to search for a Business Name inside those results
3. Search doesn't work

[As reported here](https://secure.helpscout.net/conversation/132769070/3871/) and [here](https://secure.helpscout.net/conversation/147226111/4403/)

**Comment by luistinygod** [comment]
I'm not able to reproduce..

**Comment by zackkatz** [comment]
Fixed in https://github.com/katzwebservices/GravityView-DataTables-Extension/commit/ea5c78919f6e8669afd29059e8b96bc936b84888
