### ISSUE TITLE
gravityview_widget_search_bar shortcode doesn't work

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#574]
See https://secure.helpscout.net/conversation/135874796/4031/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995633024399071)

**Comment by rafaehlers** [comment]
Related: http://docs.gravityview.co/article/123-widget-shortcodes

**Comment by zackkatz** [comment]
`[search_bar]` seems to on a client's site!

**Comment by soulseekah** [comment]
The shortcode was removed in 2014: d3b581249a8e1df9fac73cfdf7864174001d3e64

Do we want one back?

**Comment by rafaehlers** [comment]
I usually suggest this to our clients: https://wordpress.org/plugins/widget-shortcode/
