### ISSUE TITLE
The combination of Advanced Filter ANY with Search Widget ALL won't work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#576]
Let's say we have the following table: 

First, Last, Email
Rafael, Ehlers, rafa@rafa.com
Rafael, Ehlers, rafael@rafael.com
Rafael, Katz, rafa@katz.com

On Advanced Filter (**ANY**) (you need to have at least two filters to reproduce this error):

![gv-search-bug-1](https://cloud.githubusercontent.com/assets/1222472/10983911/e3a45cfe-83fc-11e5-8f2a-bf68f1ee2963.jpg)

On Search Widget (**ALL**):

![gv-search-bug-2](https://cloud.githubusercontent.com/assets/1222472/10983937/10e547c8-83fd-11e5-9e48-f6bb4041f1c3.jpg)

Initial display:

![gv-search-bug-3](https://cloud.githubusercontent.com/assets/1222472/10984004/82cde0de-83fd-11e5-987b-c278489d2b5e.jpg)

Searching for "Katz" as last name:

![gv-search-bug-4](https://cloud.githubusercontent.com/assets/1222472/10984027/a9047d1c-83fd-11e5-8b7e-e35369b77bc7.jpg)

As we can see, those are the same results. The expectation was for the search to be performed inside the first filter defined on the Advanced Filter rules.

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/136052637/4043/

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/279678830/7488/?folderId=408730

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/279678830/7488/

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/314059022/8110/

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/224622096/6218/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/342743620/8735/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/694255567/17353/

**Comment by soulseekah** [comment]
This is possible with `GF_Query` now, but using a custom mapper for search_criteria. Right now the same old rules are applied and there's no way to nest the filters as they are being called now. They just overwrite one another.

This change would require fixes in both plugins. Rewriting the search_criteria part for GF_Query part. It should be simple. Shall I?

**Comment by zackkatz** [comment]
@soulseekah Yes, please!

**Comment by soulseekah** [comment]
Related #932 

Fixed in https://github.com/gravityview/Advanced-Filter/commit/abe6fa0a29ed14b4f86e52d6f949f135e8533b01
