### ISSUE TITLE
View Settings > Single Entry title option not working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#579]
A user reported:

![screen shot 2015-11-10 at 7 07 29 pm](https://cloud.githubusercontent.com/assets/1222472/11107367/6a3ee4d4-88c4-11e5-8bd2-ed6ed9b8431c.png)

And I can confirm, this is not working:

![gv-single-entry](https://cloud.githubusercontent.com/assets/1222472/11107355/513ffdc4-88c4-11e5-8d93-1d33483ac131.jpg)

Related: https://secure.helpscout.net/conversation/137987563/4160/

Tested on GV 1.15.1

**Comment by zackkatz** [comment]
This works properly for modifying the heading, just not the `<title>` tag; that's handled with the Sharing & SEO Extension.
