### ISSUE TITLE
Using a [gravityview] shortcode inside a Custom Content in Above Entries Widgets...

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#584]
...make the main View to not list its entries:

![gv-image013](https://cloud.githubusercontent.com/assets/1222472/11479660/4bd8aaba-977a-11e5-820b-563c84c90598.jpg)

However, if you use it only in the Below Entries Widgets, it does work:

![gv-image009](https://cloud.githubusercontent.com/assets/1222472/11479675/5959bc88-977a-11e5-9ebb-3bbe3a6077df.jpg)

GravityView 1.15.1
Gravity Forms 1.9.13.27

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/140448245/4218/

**Comment by zackkatz** [comment]
@luistinygod You want to tackle this one?

**Comment by zackkatz** [comment]
@soulseekah I have a feeling this is going to lead to some improvements to the code…

**Comment by zackkatz** [comment]
This now works in 2.0!
