### ISSUE TITLE
Include a {date_created} Merge Tag

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#591]
Gravity Forms doesn't include a {date_created} Merge Tag out of the box. 

The alternative solution meanwhile is using: the {entry_time} shortcode that Gravity Forms shows here: https://www.gravityhelp.com/documentation/article/gform_replace_merge_tags/#1-replace-a-custom-merge-tag

Related: https://secure.helpscout.net/conversation/142259908/4278/

**Comment by zackkatz** [comment]
Closed with #600
