### ISSUE TITLE
Edit Product Fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#592]
Make product fields editable, but **only if the form is not connected to a payment gateway**. This solves the issue with syncing with any remote service, and screwing up accounting.
- [x] Make fields editable
- [x] Add a View setting to allow editing product fields
- [ ] Add support for Product fields in the Search Bar (warning: option field could be changed to different field types. Example: Option field turned into Checkbox shows up as Input Text into Search Bar).

When completed, notify: https://secure.helpscout.net/conversation/149284311/4437/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995634500489381)

**Comment by rafaehlers** [comment]
Changing the scope of this issue.

**Comment by rafaehlers** [comment]
won't fix.

**Comment by luistinygod** [comment]
Also notify https://secure.helpscout.net/conversation/191808267/5530/
Total field is not updating when Product is type Calculation
![screen shot 2016-04-22 at 16 46 30](https://cloud.githubusercontent.com/assets/2511389/14746919/d55d0574-08a9-11e6-80eb-a366fd16e3cf.png)

**Comment by rafaehlers** [comment]
We still need the support for product fields.

Related: https://secure.helpscout.net/conversation/349013496/8904/?folderId=408730
