### ISSUE TITLE
Admin only fields are showing on the Edit Entry page

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#596]
I'm logged in as a Subscriber, I added 2 entries, this is my view:

![gv-issue-1](https://cloud.githubusercontent.com/assets/1222472/11946430/d10946b8-a841-11e5-85ca-4208e71bbd41.jpg)

After I click to edit the first entry, the admin-only field "Approved?" shows up:

![gv-subscriber-2](https://cloud.githubusercontent.com/assets/1222472/11946437/ec5803f0-a841-11e5-9987-dc4701621bfc.jpg)

After clicking on Update to change some fields on that entry, the admin-only field also shows up on the Edit Entry screen.

Tested with: 
Gravity Forms 1.9.15
GravityView 1.15.2

Related: https://secure.helpscout.net/conversation/147220393/4401/?folderId=571965

**Comment by zackkatz** [comment]
@rafaehlers I've not been able to reproduce. Are you sure it's actually Admin-Only, and not just that the *label* text says "Admin-Only"?
