### ISSUE TITLE
GravityView Search widget lacks search operator

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#597]
In the search bard widget:

![gv-match-all](https://cloud.githubusercontent.com/assets/1222472/11971364/85c7656c-a923-11e5-90ba-2c288fa39312.jpg)

In the GravityView Search widget:

![gv-gravityview-search](https://cloud.githubusercontent.com/assets/1222472/11971382/dbee8664-a923-11e5-8ec4-62a01ad1ea98.jpg)

GravityView 1.15.2
Related: https://secure.helpscout.net/conversation/150896109/4471/

**Comment by zackkatz** [comment]
@rafaehlers I made progress on this, but not quite there yet.
