### ISSUE TITLE
Product Field dropdown is operator doesn't work with Advanced Filter or Shortcode

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#599]
Trying to select the operator "is" doesn't work here (after clicking Save/Update the field goes back to blank):

![gv-is-missing-after-update](https://cloud.githubusercontent.com/assets/1222472/12023285/1c69bd94-ad7f-11e5-9e0b-2e5a42487a60.jpg)

Or here: ```[gravityview id='153731' search_field='9' search_value ='13u']```

With this kind of field:

![gv-key-value](https://cloud.githubusercontent.com/assets/1222472/12023297/3fb32baa-ad7f-11e5-80bc-6774ab04bf2f.jpg)

It works here thought:

![gv-filter-entries](https://cloud.githubusercontent.com/assets/1222472/12023320/76263fd8-ad7f-11e5-9a68-ae634141d069.jpg)

Tested on:
GravityView 1.15.2
Adv Filters: 1.0.11

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/152684281/4489/?folderId=408730

**Comment by luistinygod** [comment]
Fix https://github.com/katzwebservices/GravityView-Advanced-Filter-Extension/pull/22
