### ISSUE TITLE
possible to add custom css class to widget container?

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#615]
Looks like not, https://github.com/gravityview/GravityView/blob/master/includes/class-template.php#L827
unless I missed it somewhere...

Currently, to target the above entries area for styles, requires pseudo selector.

It's really not a big deal. Feel free to close this if I'm being a baby.

**Comment by zackkatz** [comment]
@m-e-h Haha, no, you're not being a baby! Not a problem.
