### ISSUE TITLE
Triggering conditional logic when editing an entry makes previous values go away

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#619]
The user made a video to illustrate this: https://www.youtube.com/watch?v=XyFwcEWtCfw

Tested on GV 1.16.1

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/165023488/4775/

**Comment by zackkatz** [comment]
Please check to see if 1.16.2 fixes this issue (Might be related to #620)
