### ISSUE TITLE
Shortcode to show field value

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#621]
Use `form`, `entry`, `field`, and `format` parameters.

Form: Form ID. Not required, but ideal.
Entry: Entry ID.
Field: Field ID or Meta ID

**Format:**
- `raw`
- `display` (default)
- `urlencode`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995635371364433)

**Comment by rafaehlers** [comment]
Achieved with: https://docs.gravityview.co/article/462-gvfield-embed-gravity-forms-field-values
