### ISSUE TITLE
Probable incompatibility with User Registration Add-On 3.x

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#623]
If you edit an entry that belongs to a form that can create users, these errors shows up:

![gv-already-created](https://cloud.githubusercontent.com/assets/1222472/12836827/5781ea68-cba3-11e5-8b8c-2723f58423fb.jpg)

Tested with:
Gravity Forms - Version 1.9.16
Gravity Forms User Registration Add-On - Version 3.1
GravityView - Version 1.16.1

Related: https://secure.helpscout.net/conversation/167908074/4864/?folderId=408730

**Comment by m-e-h** [comment]
This is true. I switched to "update" users and got the same result.

**Comment by m-e-h** [comment]
Actually, I was wrong. Sorry. The "update" setting doesn't trigger the alert. But of course no meta gets saved.
Must've been a caching thing or something else the first time I tried.
