### ISSUE TITLE
Quiz add-on fields doesn't have Merge Tags

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#627]
If we had them we could use inside a Custom Content field or even compare them using [gvlogic]

Related: https://secure.helpscout.net/conversation/150873271/4470/?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers Please test on current `develop` branch.

**Comment by rafaehlers** [comment]
These ones are now working: https://www.gravityhelp.com/documentation/article/quiz-add-on/#quiz-merge-tags 
I suspect that's what the customer wants. Waiting for his feedback on HS to close this ticket.
