### ISSUE TITLE
Search by date range is working as greater than and less than, no equal to

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#629]
It looks like the search by date range in the search bar widget is being done with GREATER THAN and LESS THAN instead of GREATER THAN OR EQUAL TO and LESS THAN OR EQUAL TO.

![gv-daterange](https://cloud.githubusercontent.com/assets/1222472/12938684/01427844-cf9e-11e5-8b3c-05c4e1191a65.jpg)

![gv-daterange-2](https://cloud.githubusercontent.com/assets/1222472/12938687/0390ef54-cf9e-11e5-8435-c6ee5b5aa1d8.jpg)

GravityView 1.16.1
Related: https://secure.helpscout.net/conversation/168604074/4884/?folderId=408730

**Comment by rafaehlers** [comment]
Please also check this for shortcode and advanced filter extension.

**Comment by luistinygod** [comment]
GF 1.9.16 doesn't contain operator `<=` as a valid operator.

forms_model.php line 5269:
```
public static function is_valid_operator( $operator ) {
		return in_array( strtolower( $operator ) , array( 'is', 'isnot', '<>', 'not in', 'in', '>', '<', 'contains', 'starts_with', 'ends_with', 'like', '>=' ) );
	}
```

**Comment by luistinygod** [comment]
Neither GF 1.9.16.7 :-(
