### ISSUE TITLE
View slowness perceived when multiple gvlogic conditions are used

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#633]
A client reported a perceived slowness when rendering a View that used many [gvlogic] shortcodes in a Custom Content field:

>But the problem I'm having now is that the view won't load after a while. My client's MAC just freezes up.
Probably has to do with cache.
I think that there are too many formulas in one column.
For now I have to leave it out of the view for it to load.

This is an example of a formula used by her:

>[gvlogic if="{Faculty : Research area:7}" contains="Ando"]Ando;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Bocarsly"]Bocarsly;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Car, Roberto"]Car;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Carey"]Carey;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Carrow"]Carrow;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Cava"]Cava;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Chirik"]Chirik;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Doyle"]Doyle;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Groves"]Groves;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Hecht"]Hecht;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Hyster"]Hyster;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Knowles"]Knowles;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="MacMillan"]MacMillan;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Muir"]Muir;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Petry"]Petry;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Rabinowitz"]Rabinowitz;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Rabitz"]Rabitz;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Scholes"]Scholes;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Selloni"]Selloni;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Sorensen"]Sorensen;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Seyedsayamdost"]Mo;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Torquato"]Torquato;[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Yang"]Yang[/gvlogic][gvlogic if="{Faculty : Research area:7}" contains="Carey"]Carey;[else][/gvlogic]

Tested with 1.16.1
Related: https://secure.helpscout.net/conversation/169352393/4903/?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers I wasn't able to reproduce this slowness. Is it only in DT or everywhere?

**Comment by rafaehlers** [comment]
@zackkatz the user is using DataTables. I haven't tested it with other View types.

**Comment by rafaehlers** [comment]
Let's close this for now as it's not relevant anymore.
