### ISSUE TITLE
Filter by current logged-in user by shortcode is not working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#634]
![is-logged-in](https://cloud.githubusercontent.com/assets/1222472/13030007/4f8d7aa2-d283-11e5-8b85-e7020d1960c1.jpg)

[gravityview id="81" search_field="{created_by:ID}" search_value="{user:ID}"]

Tested on GravityView 1.16.1
Related: https://secure.helpscout.net/conversation/168970598/4893/?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers - This will now work in 1.16.2 with the correct shortcode (the shortcode was wrong):

`[gravityview id="81" search_field="created_by" search_value="{user:ID}"]`
