### ISSUE TITLE
Placing a search on date range shows letter "A" on the search fields

### ISSUE THREAD

**Issue by luistinygod** [gravityview/GravityView#645]
And search results aren't right.

![screen shot 2016-02-21 at 17 24 57](https://cloud.githubusercontent.com/assets/2511389/13204139/273edefe-d8c0-11e5-910a-99e1dec97390.png)

Reported by https://secure.helpscout.net/conversation/173557197/5001/
Related with #629.

**Comment by zackkatz** [comment]
@luistinygod that is likely "Array"
