### ISSUE TITLE
Add option to show checkbox label instead of value

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#647]
See https://secure.helpscout.net/conversation/159449943/4611/

> Well, the check boxes by default display the value..
> 
> I.e. in my gravity forms i have
> 
> Name: CourseA, Value: 1
> Name: CourseB, Value: 2

> As of now, GravityView displays 1 or 2. There is no way for the view to display the actual name of the checkbox. The user doesn't need to know the value - and is useless for them unless they know the actual name of the checkbox.

**Comment by zackkatz** [comment]
This is possible with filters, but should be available in field settings.

**Comment by rafaehlers** [comment]
The same for radio labels is needed.

**Comment by zackkatz** [comment]
Fixed in https://github.com/gravityview/GravityView/commit/f033aae28add70980450daf0b1d6460b5a155cc6
