### ISSUE TITLE
State dropdown field should allow to search for its options

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#649]
![gv-address-state](https://cloud.githubusercontent.com/assets/1222472/13308973/2537a0ac-db57-11e5-8318-17eb0414f221.jpg)

Related: https://secure.helpscout.net/conversation/167908074/4864/?folderId=571965

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995638093232264)

**Comment by rafaehlers** [comment]
Another one: https://secure.helpscout.net/conversation/206291289/5875/?folderId=408730

**Comment by zackkatz** [comment]
Added in 1.19.2 362b57c4445bd3ff24874fc3c2cb5ab6e95460a7

**Comment by rafaehlers** [comment]
Not working anymore on 1.21.4

**Comment by zackkatz** [comment]
@rafaehlers Can you reproduce this not working anymore? It appears to work for me ![State dropdown](http://share.gravityview.co/bjJvSQ+)

**Comment by rafaehlers** [comment]
Even though it allows you to pick a Select field on the Input Type column, it displays a simple text input on the front-end:

![gv-state-bug](https://user-images.githubusercontent.com/1222472/43503072-15b4ca62-9534-11e8-859f-e246cc7c1aaa.jpg)

Tested on GV 2.0.14.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/631141450/16074/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/735614779/18280

**Comment by soulseekah** [comment]
When the form field is not currently a dropdown the input method will fallback to text. That is in Form Settings the address type has to be Canadian or United States for choices to be present. If it's a free-text input then the search input will fall back to text.

See `GravityView_Field_Address::search_field_filter`. What we can probably do is fetch and cache all the values that have been submitted for a form and present them for search selection in the dropdown, but only if the choices are empty and we're about to fallback to text mode.
