### ISSUE TITLE
Edit/Delete Link

### ISSUE THREAD

**Issue by kodeine** [gravityview/GravityView#657]
Hello,

I have a page with tabs, one of the tabs display the posts table, edit link takes to the same edit page, but since the query doesnt have a tab value, it shows a different tab. 

If we keep the query params and append to the links it would fix the issue. Or is there any filter/hook?

Thanks for this great plugin.

**Comment by rafaehlers** [comment]
You should add the query params into the links using the [gv_entry_link] shortode:  http://docs.gravityview.co/article/287-gv-entry-link

**Comment by daizprua** [comment]
Cannot see delete or edit if I´m not logged, can I show the links without login?
