### ISSUE TITLE
The & symbol doesn't work with search_value parameter in [gravityview]

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#661]
[gravityview id="81" search_field="2" search_value="Pride & Prejudice"] this won't return any results.

However, it works if we search for "Pride & Prejudice" in the GF's Entries page.

GV: 1.16.3
GF: 1.9.17.5
Related: https://secure.helpscout.net/conversation/169777543/4919/

**Comment by zackkatz** [comment]
It's working for me:

```
[gravityview id="16119" search_field="1" search_value="Amp & Amp"]
```

<img width="699" alt="screen shot 2016-03-18 at 4 15 24 pm" src="https://cloud.githubusercontent.com/assets/870979/13893528/a41cc27e-ed24-11e5-84cf-5a0f0ef23c08.png">

**Comment by rafaehlers** [comment]
@zackkatz tested again on 1.16.4.1 in a different machine:

![gv-select-search](https://cloud.githubusercontent.com/assets/1222472/14030539/e2373370-f1e6-11e5-9e81-f41ce2e691cc.jpg)

**Comment by zackkatz** [comment]
Okay so that's a different issue, that's Search Bar, not shortcode, correct?

**Comment by rafaehlers** [comment]
Status: Waiting for user credentials to replicate...

**Comment by zackkatz** [comment]
@rafaehlers I'm closing until we have another case. I've not been able to replicate.
