### ISSUE TITLE
edit own entry gravity view in combination limited user gravity form not working

### ISSUE THREAD

**Issue by bremskie** [gravityview/GravityView#667]
Hello,  i use gravity form with the ( GW_Submission_Limit) class. 
I limit the user by 'user_id' and 'limit' by 1 entry per user in this class. That's working.
But Its not possible that an user  edit his own entry (the feature given by gravity view ) because the limit value of the GW_Submission_Limit class is 1; 
Editing an excisting entry and update an new entry are two dfferent cases. 
So is there a solution for this?

**Comment by zackkatz** [comment]
Hi @bremski - 
You'll need to add some code to not modify the output if you're in Edit Entry screen. Here's an example of how we added the code to a similar issue: https://gist.github.com/zackkatz/d24dbb19398553cd38e882f424baf26e#file-dont-submit-same-form-twice-php-L13-L20

```
// If we're in GravityView's Edit Entry, don't modify form.
	if( function_exists( 'gravityview_get_context' ) ) {
		$context = gravityview_get_context();

		if( 'edit' === $context ) {
			return $form_string;
		}
	}
```

Hope that helps.

**Comment by bremskie** [comment]
Thanxx
