### ISSUE TITLE
excerpt text in edit form on front side not properly working

### ISSUE THREAD

**Issue by bremskie** [gravityview/GravityView#673]
Hi the excerpt text from my custom type page as postfield added in my form (gravityform) in edit entry (from formview) on front side not properly working. i miss the character limit indicator. From de normal text(long text) its ok.
EDIT sorry its otherwise character limit from post content its not vissible, so from the xcerpt its correct

**Comment by rafaehlers** [comment]
@bremskie can you send us a screenshot of this issue?
