### ISSUE TITLE
Improve Admin Bar menu

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#676]
It'd be nice to have all the relevant options for a View as a drop-down in the Admin Bar under "GravityView":

- Edit View
- Edit Entry
- Edit Form
- Form Entries
- Preview Form
- Etc.

I'm often finding myself on a View and wanting to create a new entry or edit the form.

**Comment by rafaehlers** [comment]
:+1: for that

**Comment by zackkatz** [comment]
Let's see how CodeMill works out! codemill$50

**Comment by zackkatz** [comment]
This has been crowd-sourced! Get paid for completing this task: http://codemill.io/task/570eacd840297603002e00d8

**Comment by CodeMillApp** [comment]
@zuernBernhard any progress or should we release this task back to the marketplace?

**Comment by zuernBernhard** [comment]
@CodeMillApp yes I#m on the job - will release results during the next 24 hours.

**Comment by zuernBernhard** [comment]
Is this the right place for the Dropdown ?

![auswahl_006](https://cloud.githubusercontent.com/assets/1442798/14664294/ec7b2bf0-06c9-11e6-9af8-2eee1285077a.png)

**Comment by zackkatz** [comment]
@zuernBernhard 

It should replace the "Edit View" and "Edit Entry" links with one "GravityView" main menu with the other submenus in the Toolbar:

![](https://www.evernote.com/l/AARa4Vu4fclFBLRBHYqkFcEv15puXd5GM4kB/image.png) 

The screenshot you posted didn't look right, but maybe it's a screenshot issue. Please create a Pull Request and I'll check it out.

**Comment by zackkatz** [comment]
@zuernBernhard Any update on this?

**Comment by zackkatz** [comment]
Sorry @zuernBernhard, you took too long.

**Comment by endurtech** [comment]
There is always that one other guy... who wants the opposite. How can we remove the GravityView completely from the Admin Bar? Thank you.

**Comment by soulseekah** [comment]
> There is always that one other guy... who wants the opposite. How can we remove the GravityView completely from the Admin Bar? Thank you.

Please contact support@gravityview.co with your current license key.

**Comment by endurtech** [comment]
Figured it out. Just add the following css: #wp-admin-bar-gravityview{display:none!important;}
