### ISSUE TITLE
Chrome bug showing listing

### ISSUE THREAD

**Issue by crouti** [gravityview/GravityView#680]
Works on Firefox, but on Chrome, browser console show error:

<img width="383" alt="capture d ecran 2016-04-07 a 13 51 53" src="https://cloud.githubusercontent.com/assets/10502063/14350701/388ed1da-fccb-11e5-9f8a-ed9e1ae5c68f.png">

and page display interrupted.

**Comment by rafaehlers** [comment]
@crouti could you provide us with more details, like what is your GravityView version and which particular screen this error message is happening

**Comment by crouti** [comment]
cannot reproduce problem now...
