### ISSUE TITLE
When editing a radio button field conditionally hidden, the saved choice doesn't show

### ISSUE THREAD

**Issue by luistinygod** [gravityview/GravityView#682]
Notify here: https://secure.helpscout.net/conversation/185679276/5339/?folderId=408730

**Comment by rafaehlers** [comment]
That's the thing. It works for me:

# Multiple Entries screen
![gv-radio-1](https://cloud.githubusercontent.com/assets/1222472/14368600/2b3692fa-fcf5-11e5-8466-25f369638ed1.jpg)

# Edit Entry screen:

![gv-radio-2](https://cloud.githubusercontent.com/assets/1222472/14368602/2ddaa1ae-fcf5-11e5-9abb-9178846708ff.jpg)

It looks like her issue is another one. Also, even if I use that Perk, it still work as expected.

**Comment by luistinygod** [comment]
I was able to reproduce the issue on my test installation. It is a pure GravityView issue (I already informed David it is not related with the Perks). 
To reproduce :
*create an entry with the option to display the second group of radios off, but choose one radio on this group
* then go to the view and edit that entry.
* when editing, you won't see the second group, so check the option to display it
* the radio is not checked

**Comment by luistinygod** [comment]
This is not working because Gravity Forms is handling the radio inputs (and the checkboxes) on Javascript.

**Comment by luistinygod** [comment]
From `conditional_logic.js` (Gravity Forms):
```
//checkboxes and radio buttons
	var elements = jQuery(targetId).find('input[type="radio"], input[type="checkbox"]:not(".copy_values_activated")');

	elements.each(function(){

		//is input currently checked?
		var isChecked = jQuery(this).is(':checked') ? true : false;

		//does input need to be marked as checked or unchecked?
		var doCheck = defaultValue ? jQuery.inArray(jQuery(this).attr('id'), defaultValue) > -1 : false;

		//if value changed, trigger click event
		if(isChecked != doCheck){
			//setting input as checked or unchecked appropriately

			if(jQuery(this).attr("type") == "checkbox"){
				jQuery(this).trigger('click');
			}
			else{
				jQuery(this).prop("checked", doCheck);

				//need to set the prop again after the click is triggered
				jQuery(this).trigger('click').prop('checked', doCheck);
			}

		}
	});
```

**Comment by luistinygod** [comment]
![screen shot 2016-04-11 at 18 37 43](https://cloud.githubusercontent.com/assets/2511389/14436828/55abf542-0016-11e6-8c99-ac0dc225cfda.png)
![screen shot 2016-04-11 at 18 37 48](https://cloud.githubusercontent.com/assets/2511389/14436827/55ab9750-0016-11e6-9615-49327eed591c.png)

**Comment by rafaehlers** [comment]
Same issue here: https://github.com/gravityview/GravityView/issues/619 (check YT video linked)

**Comment by zackkatz** [comment]
Sent an email to GF, with the following request

--------

Could you all add a filter to conditional_logic.js that overrides `gf_reset_to_default()`? I want the person's choices to remain when switching a field with conditional logic rules. 
 
It could look like this:

```
function gf_reset_to_default(targetId, defaultValue){

    if ( false === gform.applyFilters( 'gf_reset_to_default', true ) ) {
        return;
    }
```

or it could be added here instead:

```
var reset_to_default = gform.applyFilters( 'gf_reset_to_default', true );

//if field is not already hidden, reset its values to the default
var child = $target.children().first();
if (child.length > 0){
	if(!gformIsHidden(child) && reset_to_default){
		gf_reset_to_default(targetId, defaultValues);
	}
}
```
