### ISSUE TITLE
Featured Entries "Broken Dependencies"?

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#691]
I'm seeing the attached Query Monitor message on all pages.

![gv-featured](https://cloud.githubusercontent.com/assets/3585901/14787980/fa987ea0-0ad3-11e6-994a-5a060cab0971.png)

I have both extensions activated.

**Comment by zackkatz** [comment]
@m-e-h This is fixed in the next Featured Entries update, thanks!
