### ISSUE TITLE
Non-logged-in users of a multisite can see Views where logged-in (but without a role) can'tvb

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#699]
Consider the following scenario:

1) Websites
1.1) MainSite.com
1.2) subsite.MainSite.com

2) Users
2.1) GravityView (network admin)
2.2) Rafael (just a created user on the network, it is not associated with any subsite)

1. User GravityView creates a View on subsite.MainSite.com = you can obviously see the View perfectly
2. Grab the View URL and paste it on an anonymous browser window = you'll be able to see the view as a non-logged-in user.
3. Now login with the user **Rafael** on this subsite (or MainSite) and check the View URL = nothing shows up `That's the problem`

Related: https://secure.helpscout.net/conversation/200961331/5731/

**Comment by zackkatz** [comment]
@rafaehlers This was fixed in https://github.com/gravityview/GravityView/commit/0c3c606020e6b611163e36666d58aaaeb6f49d33 - can you please test?
