### ISSUE TITLE
Filter & Sort view settings clash with WP-Chosen plugin

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#702]
https://github.com/stuttter/wp-chosen
Produces this
![gv-chosen](https://cloud.githubusercontent.com/assets/3585901/15342392/d74c4896-1c62-11e6-8da3-4315dc5ca899.png)

I can look into the styles maybe tomorrow and do a PR either here or on that repo.

**Comment by rafaehlers** [comment]
@m-e-h Even if you have GravityView's No-Conflit mode activated?

**Comment by m-e-h** [comment]
I always forget about no-conflict. That takes care of it. Thanks! 
I'll let you close this.
