### ISSUE TITLE
Theme Conflict with Avada's Fusion Core version 2.0.2 

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#711]
If using the Fusion Core editor, the [gravityview] shortcode is base64 encoded like this: 
`[fusion_code]W2dyYXZpdHl2aWV3IGlkPScxNzY0J10=[/fusion_code]` 

If this code is used on the front page of the website, the link to Edit Entry or Single Entry page won't work (even if using our plugin for that).

The fix is quite simple, it's just a matter of changing to the Default (WordPress) Editor and replacing that section with the [gravityview] shortcode, like this:

![gv-fusion-bug](https://cloud.githubusercontent.com/assets/1222472/15762309/751c13de-28f3-11e6-9af3-7278cd82e233.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995645579013657)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/206137346/5869/

**Comment by soulseekah** [comment]
Is this still the case?

**Comment by rafaehlers** [comment]
No one has ever reported this anymore.
