### ISSUE TITLE
Filtering by Entry Date with modified DatePicker date format doesn't work.

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#724]
1) I have an entry created on `Submitted on: 2016/06/21 at 8:55 pm`

2) If I add a Date Range search on my Search Bar and search for:

![gv-mdy](https://cloud.githubusercontent.com/assets/1222472/16251990/faa08a3a-382a-11e6-8ba0-741e178c411f.jpg)

3) Now, if I use the code provided here: http://docs.gravityview.co/article/115-how-do-i-change-the-format-of-the-search-widgets-date-picker and change to: `$format = 'dmy';` the DatePicker will change, but the search won't work:

![gv-dmy](https://cloud.githubusercontent.com/assets/1222472/16252128/ea433614-382b-11e6-9dfa-390f8540abc6.jpg)

Related: https://secure.helpscout.net/conversation/214579752/6027/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/308802331/0/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/439913687/11251/?folderId=408730

**Comment by kangzj** [comment]
+1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/687921146/17225/

**Comment by soulseekah** [comment]
The code only solves half of the equation. The dates are passed and parsed incorrectly in other formats.

I'll provide a better fix which solves both parts in a bit. The old code will be pointless, though and will break. A new filter will be introduced. Meddling with the class like that wasn't a good idea either way, what if we switch pickers?

Stay tuned.

P.S. Also, that list of custom plugins is killing me :) We should make it a setting :)

**Comment by zackkatz** [comment]
@soulseekah any time you say “we should,” feel free to do it! 👍☑️

**Comment by soulseekah** [comment]
I won't be able to insert the setting as it requires some extra UI work in there. I'll just make sure all our variants work. Right now 2 of the 7 don't:

![image](https://user-images.githubusercontent.com/685880/47182127-57831e80-d32d-11e8-9d03-013d1cc8df7c.png)

We're using `strtotime`, we should go for `date_create_from_format`.
And I'll leave the identifiers in the filter as is for back-compatibility, and so that we don't have to rewrite much of the doc.

Tests ready. Fix will need some more time.

**Comment by kangzj** [comment]
awesome

**Comment by kangzj** [comment]
@soulseekah That's fantastic! Sorry for the late update. 
Tested entry date filter and it works like charm while I guess the formatting for Date field is not fixed which located in class-search-widget.php function prepare_field_filter. Does that make any sense?
Many thanks.
J

**Comment by soulseekah** [comment]
You're right, @kangzj. This fix only works for Entry Date, sorry.

The fix for all other date fields will be available in the next minor release.

**Comment by soulseekah** [comment]
@kangzj please test the develop branch and let us know if it works. Thanks for helping on the issue.

**Comment by kangzj** [comment]
@soulseekah Hi mate, it's working beautifully. Thank you so much. 👍
