### ISSUE TITLE
Approve/Reject Bulk actions are missing from Entries page where GF is 2.0

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#728]
Gravity Forms 1.9.19

![gv-approve-reject](https://cloud.githubusercontent.com/assets/1222472/16388147/041f7082-3c98-11e6-8008-f68d31c79489.jpg)

Gravity Forms 2.0.1

![gv-approve-2](https://cloud.githubusercontent.com/assets/1222472/16388186/3540729c-3c98-11e6-8a61-3ea22af5c19b.jpg)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/219894267/0/

**Comment by zackkatz** [comment]
Merging with #726
