### ISSUE TITLE
Hide View data until search is performed option hides View widgets as well

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#742]
A feedback/use-case from a user:

>When "Hide View data until search is performed" is enabled. We discovered that this option also hides a 'Custom Content' field. Which in our case is just located above the search bar.
>In our customers case its important to display the custom text in the custom field because it displays that only records between a certain period are available.

**Comment by zackkatz** [comment]
Closed because this is possible using this plugin: [GravityView Mod: Show Custom Content Before Search](https://github.com/gravityview/gv-snippets/tree/addon/6691-show-widget-before-search)
