### ISSUE TITLE
Support Survey fields on the Search Bar

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#745]
At this moment, it's impossible to search within a Survey field content with the search bar:

![gv-survey-search](https://cloud.githubusercontent.com/assets/1222472/17536548/1b213324-5e6c-11e6-9739-6395f4214355.jpg)

Here's how the search works on Entries page:

![gv-survey-gf-search](https://cloud.githubusercontent.com/assets/1222472/17536564/387dffba-5e6c-11e6-8b93-acea87e3b455.jpg)

**Comment by zackkatz** [comment]
Related #722
