### ISSUE TITLE
New field visibility option in GF: make sure to properly support it

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#750]
Related: https://gravityforms.slack.com/archives/general/p1472500124000002

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995646801716875)

**Comment by zackkatz** [comment]
Should probably be applied here: `GravityView_Edit_Entry_Render::filter_admin_only_fields()`

**Comment by soulseekah** [comment]
The Slack link no longer works.

Views have their own visibility settings. What behavior are we looking to get?

For Edit Entry, I agree, when Edit is unconfigured we should be hiding administrative fields. We have recently fixed this in #1292

Thoughts?

**Comment by soulseekah** [comment]
Bumpity bump.

**Comment by rafaehlers** [comment]
Let's close this for now. I think this was related to "administrative fields":

![image](https://user-images.githubusercontent.com/1222472/74212194-d95d3080-4c71-11ea-948f-67b9e2923859.png)
