### ISSUE TITLE
Field dependant on a Product Field (conditional logic) won't show up in the Edit Entry page

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#760]
Product fields don't show up in Edit Entry page, therefore, if you have a field that should appear based on these type of fields using Conditional Logic, your field won't show up for editing. Big problem!

Related: https://secure.helpscout.net/conversation/248793245/6864/?folderId=408730#thread-661891950

**Comment by zackkatz** [comment]
Closed with https://github.com/gravityview/GravityView/commit/37741a770969088677de31510088181c3269d836
