### ISSUE TITLE
CSS class missed

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#763]
>However I noticed in your CSS file you specify .gv-grid-col-1-4 but you don't have a .gv-grid-col-3-4 - is that an oversight or did I miss it? I can add it to my custom css, but wondering if it should be part of the GV css file?

It's true, we don't have a 3-4 class!

**Comment by zackkatz** [comment]
It's not used by any templates, so we don't need it currently…I don't think this needs to be addressed.
