### ISSUE TITLE
Only Post field values are saved if there are Post fields

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#764]
If there are Post fields in Edit Entry configuration, then non-Post fields aren't saved during Edit Entry.

✅ All Post fields: Works as expected
✅ All non-Post fields: Works as expected
✅ Form has Post fields, but not included in Edit Entry configuration

To reproduce:

1. Create a form 
2. Add non-Post fields
3. Edit an entry. It works.
2. Add a Post field
3. Edit the entry. Post values are updated, but non-Post field values are not.

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/251705514/6923/
