### ISSUE TITLE
Add option to display GF Survey Addon "Rating" field type as stars

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#774]
In the Survey field, there is a "Rating" field type that displays each of the choices as a star. 

Backend: Add a field setting to display the ouput as stars.

Frontend: Render the stars using Dashicon stars (`dashicons-star-filled` and `dashicons-star-empty`), since the GF stars are images.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995647746367081)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/268192715/7260/
