### ISSUE TITLE
Add :year :day and :month Merge Tag modifies for Date fields

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#779]
The :timestamp modifier won't help when trying to calculate a person's age based on a Date field.

Related: http://docs.gravityview.co/article/350-merge-tag-modifiers

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/263016573/7170/?folderId=408730

**Comment by zackkatz** [comment]
Did you know this already exists in GF? Neither did I!

- `{Date:1:year}: 2018`
- `{Date:1:month}: 04`
- `{Date:1:day}: 09`

https://docs.gravityforms.com/date/#modifiers
