### ISSUE TITLE
Custom Entry slug filter prevents the ajax approve/reject on backend

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#781]
We can't approve or reject an entry with this filter:
`add_filter( 'gravityview_custom_entry_slug', '__return_true' );`

On GV 1.18

Related: https://secure.helpscout.net/conversation/264181907/7193/?folderId=408730

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/265723407/7217/

**Comment by rafaehlers** [comment]
Both users notified.

**Comment by zackkatz** [comment]
Fixed here: https://github.com/gravityview/GravityView/commit/13ad5c29f058e7447a3ff8295079dd0d308f2e53
