### ISSUE TITLE
For custom slug filter you must choose, or id or a field as the slug, both won't work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#783]
You can't have these 2 filters working simultaneously, it's either one or the other:
`add_filter( 'gravityview_custom_entry_slug', '__return_true' );`
`add_filter( 'gravityview_custom_entry_slug_allow_id', '__return_true' );`

Here it says it works: http://docs.gravityview.co/article/57-customizing-urls

According to my investigations, this doesn't work since earlier versions of GV 1.17

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995650679495847)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/264537199/7199/?folderId=408730

**Comment by zackkatz** [comment]
@rafaehlers Please test on `develop`

**Comment by rafaehlers** [comment]
This now works:

```
add_filter('gravityview_entry_slug', 'gv_change_the_gravityview_entry_slug', 10, 3 );
function gv_change_the_gravityview_entry_slug( $slug, $id, $entry = array() ) {

	$form_id = $entry['form_id'];

	switch( $form_id ) {
 		case '213':
   			$slug = $entry['2']; // ID of the field for form 198
   		break;
   		case '181':
   			$slug = $entry['7']; // ID of the field for form 199
   		break;
 	}    
  
	return $slug;  
}
```
