### ISSUE TITLE
Can't edit a field where the parent one (conditional logic) is a Product Field

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#787]
Since, you can't add a Product Fields to the Edit Entry page, there's no way for a "child" field to be updated.

Since GV 1.18

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/268562204/7269/?folderId=408730

**Comment by zackkatz** [comment]
This should be fixed in #760 - let's check before release.

**Comment by zackkatz** [comment]
Confirmed this is fixed with https://github.com/gravityview/GravityView/commit/37741a770969088677de31510088181c3269d836
