### ISSUE TITLE
gravityview_go_back_url filter does not allow javascript in it

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#794]
The code is passed through `esc_js()`, which strips out inline javascript.

```
add_filter( 'gravityview_go_back_url','gv_modify_backlink');
function gv_modify_backlink(){
return 'javascript:history.back()';
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995650714131503)

**Comment by rafaehlers** [comment]
Temp solution for the record:

```
<script type="text/javascript">
(function($){
	$(document).ready(function(){
        $("p.gv-back-link a").attr("href", "javascript:history.back()");
	});
})(window.jQuery);
</script>
```

**Comment by soulseekah** [comment]
Can someone test the `gravityview/template/links/back/atts` filter with `onclick` in there, please?

Pretty sure we can do something like:

```php
add_filter( 'gravityview/template/links/back/atts', function( $atts ) {
    $atts['onclick'] = 'history.back()';
} );
```

Test with `$atts['onclick'] = 'alert(1);'`, it should work.

@jlgrisham @rafaehlers @zackkatz 

Doing javascript: is probably bad.

**Comment by rafaehlers** [comment]
@soulseekah which branch? this doesn't work on the current `master`.

**Comment by soulseekah** [comment]
Yes, @rafaehlers I may have forgotten a `return $atts;` line in the filter, sorry. Fixed above. Try again. I tested on `develop` it works. `master` should work as well.

**Comment by rafaehlers** [comment]
```
add_filter( 'gravityview/template/links/back/atts', function( $atts ) {
    $atts['onclick'] = 'window.history.go(-1); return false;';
    return $atts;
} );
```

Does the job!
