### ISSUE TITLE
gravityview_entry_slug filter should require a form id to avoid problems

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#795]
This can generate some problems with other forms. The custom slug will only work with one form this way.

```
add_filter('gravityview_entry_slug', 'change_the_gravityview_entry_slug', 10, 3 );    
/**   
  * Change the /entry/123/ URL piece to /entry/{company name}   
  * @param  string $slug Previous endpoint, default: the entry ID   
  * @return string           Change the new endpoint to the Company Name   
  */  
 function change_the_gravityview_entry_slug( $slug, $id, $entry = array() ) {        
     // WHEN USING THIS CODE, CHANGE THE VALUE TO THE CORRECT FIELD ID      
     $field_id = '2';        
     if( !empty( $entry[ $field_id ] ) ) {          
         $slug = $entry[ $field_id ];      
     }        
     return $slug;  
 }
```

Update later this one: http://docs.gravityview.co/article/57-customizing-urls

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995650716506051)

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/GravityView/issues/783

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/572713104/14363/

**Comment by soulseekah** [comment]
I'm pretty certain that the form_id can be had via `$entry['form_id']`. The `$id` parameter contains the entry ID, so do a `GFAPI::get_entry( $id )['form_id']` to get the form.

There is another problem, perhaps, we cannot get the View. This means that we cannot dynamically change the slug for an Entry based on the View.

Seems like not a big deal.

**Comment by zackkatz** [comment]
@rafaehlers I updated the doc to be clearer: https://docs.gravityview.co/article/57-customizing-urls
