### ISSUE TITLE
Enable HTML Field merge tags

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#796]
The HTML field merge tags should be replaced with the content of the field.

**Comment by zackkatz** [comment]
Let this be a lesson to future me: I need better-written issues! Screenshots, steps to reproduce, etc!

**Comment by rafaehlers** [comment]
The form:

![image](https://user-images.githubusercontent.com/1222472/135929927-88133ed2-41dd-485a-84b8-3d8e45a9de5d.png)

No Merge Tag available for that field:

![image](https://user-images.githubusercontent.com/1222472/135929943-783a7a5b-f012-40db-ac53-6230bbfd4d9c.png)
