### ISSUE TITLE
Avada theme conflict: when using the shortcode in a template file widgets are duplicated

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#800]
![screenshot](https://cloud.githubusercontent.com/assets/870979/20580400/59ea93f4-b18f-11e6-8189-791060d663b1.png)

The user was using `echo do_shortcode( '[gravityview id="74263"]' );` in a page template.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651417168993)

**Comment by soulseekah** [comment]
I would like a retest of this. @jlgrisham see if you can reproduce, please. Place the code into one of the templates.

Avada is pretty popular, users would have complained in the last 3 years. Fingers crossed.

**Comment by soulseekah** [comment]
Take a look at https://github.com/gravityview/GravityView/issues/711 as well.

**Comment by rafaehlers** [comment]
We haven't had any recent reports of this on support.
