### ISSUE TITLE
Filter & Sort tab not loading in Chrome

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#805]
Works in Safari.

<img width="809" alt="unknown" src="https://cloud.githubusercontent.com/assets/870979/20817234/b5b10a92-b7e3-11e6-8429-7aa01622cd79.png">

Reported here: https://secure.helpscout.net/conversation/285133290/7556/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651952480614)

**Comment by soulseekah** [comment]
A one-off fluke? Pretty sure we'd be hearing about this all over.. almost 3 years. Closing.
