### ISSUE TITLE
Idea: Add shortcode to show user's latest entry/ies

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#808]
Common request is to display one entry that the user has created. This is most often shown on a profile page. 

Most often, the goals are to display one of the following, for the one entry the user has created:

- The listing
- Edit Entry form
- Edit Entry link

------

Warning: thinking out loud here.

Shortcode attributes: 

- `view` - if set, use the View's search criteria
- `form` - if set, use all entries form a form
- `template` - if set, use PHP file as the layout source (?)

Maybe add a UI with a textarea that has the merge tag insertion, like the Recent Entries widget. That would make it easier to format.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651960701469)

**Comment by zackkatz** [comment]
Related: #850

https://gravityview.slack.com/archives/G0RA23YHE/p1497634832717902

**Comment by zackkatz** [comment]
This also would be good for GPDR use cases

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/835350642/20354?folderId=408730

**Comment by soulseekah** [comment]
This can be done by using the `[gventry]` shortcode, no? I think we even have examples of this being possible, especially with the new filters we support, and limit=1. Should be straightforward.

Someone has to try this, if not we should extend `[gventry]` to make this possible.

**Comment by rafaehlers** [comment]
@soulseekah yes, it can! And I've been suggesting it. Let's close this one.
