### ISSUE TITLE
User Field: Add Avatar as option for "User Format"

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#810]
- Under "User Format" dropdown, add an "Avatar" option.
- Add a Image Size number picker (in px)?
- Output Gravatar on frontend

As requested here: https://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/13851594-default-to-wp-avatar

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651970527345)

**Comment by soulseekah** [comment]
Context image:

![image](https://user-images.githubusercontent.com/685880/70724552-deead880-1d0b-11ea-837a-1e6bbfdaa564.png)

**Comment by soulseekah** [comment]
Proposing a more vast implementation:

![image](https://user-images.githubusercontent.com/685880/70725742-f75bf280-1d0d-11ea-9b25-51bc53c43d9d.png)

**Comment by soulseekah** [comment]
Also note that the `name_display` key is not limited to anything. When sending a POST request while saving the data it is possible to grab any userdata, pretty much. This needs to be fixed for minor security purposes.

**Comment by soulseekah** [comment]
- [ ] Needs some tests
- [ ] Needs a documentation piece

Filters:

 - `gravityview/field/created_by/name_display`
 - `gravityview/field/created_by/name_display/raw`
