### ISSUE TITLE
Add Testimonials template

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#813]
http://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/7002893-add-a-testimonials-template

The best part: we can use this on GravityView.co.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651983195704)

**Comment by soulseekah** [comment]
I think DIY addresses this pretty well: https://github.com/gravityview/diy
