### ISSUE TITLE
List field inputs not appearing in Edit Entry

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#814]
The list field column headers appear, but the inputs themselves don't render. I assume this is a JS conflict or issue.

See: 
https://secure.helpscout.net/conversation/295097913/7719/
https://secure.helpscout.net/conversation/273920587/7356/
https://secure.helpscout.net/conversation/275135032/7378/

---

*Update*: The issue may only happen when there is no pre-existing content for the List field.

**Comment by rafaehlers** [comment]
![-](https://cloud.githubusercontent.com/assets/1222472/21504206/ef781846-cc43-11e6-8089-72a1f73d6f03.jpg)


![-](https://cloud.githubusercontent.com/assets/1222472/21504208/f2b8c744-cc43-11e6-9e69-3fc6ee9eaddf.jpg)

**Comment by zackkatz** [comment]
Also here: https://secure.helpscout.net/conversation/275135032/7378/
