### ISSUE TITLE
WPML: Search Bar search fields don't get translated

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#820]
Should use the correct language drop-down options, instead of only the primary language options.

See https://secure.helpscout.net/conversation/285832163/7577/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995651954915336)

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/342729907/8733/?folderId=408736

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/343362009/8753/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/398921612/9940/

**Comment by soulseekah** [comment]
`gform_pre_render_` is very often used by plugins to alter the form fields before the form shows up. Since we never call it in the search bar the fields are not altered at all.

People do this manually.
WPML's Gravity Forms Multilingual does this.
GP's Populate Anything does this.

**Comment by soulseekah** [comment]
There's also the `gravityview_widget_search_filters` filter that we can probably utilize. It allows us to modify the field choices as needed along with their labels and value counterparts.

https://secure.helpscout.net/conversation/982966868/22952?folderId=408735

**Comment by soulseekah** [comment]
I need access to the whole WPML suite for this and #1361 @zackkatz thanks.

**Comment by zackkatz** [comment]
`#ZackClose`
