### ISSUE TITLE
Problem with search User field

### ISSUE THREAD

**Issue by kangzj** [gravityview/GravityView#821]
When searching on a workflow user field, GravityView is doing in user id search and the search is a fuzzy search which means even if the input is user id, the exact match on the field still can not be shown.

how to reproduce,
1. new a form with workflow user filed
2. insert an entry
3. new a view and add a user search bar
4. do the search

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995652703364562)

**Comment by soulseekah** [comment]
This should have been fixed since 16315491d landed. Can we have a retest on this, please?

**Comment by rafaehlers** [comment]
As of GravityView 2.13.1, the Gravity Flow specific fields: Assignee, Role, and User are no longer supported on the Search Bar, not even searching for them works.

![image](https://user-images.githubusercontent.com/1222472/135928545-71788ae9-890c-4023-a91d-c386892649bf.png)
