### ISSUE TITLE
Allow Delete Entry without Loggin

### ISSUE THREAD

**Issue by daizprua** [gravityview/GravityView#826]
I have a request report and I use gravityview to show in frontend. What I need allow delete entry without login, all in frontend.
Screenshot: http://prntscr.com/dwgbbd

Thanks

**Comment by soulseekah** [comment]
`GVCommon::has_cap` will always fail if a user is logged in, so this is currently impossible without patching either it or the Delete Entry extension (`GravityView_Delete_Entry::check_user_cap_delete_entry` and `GravityView_Delete_Entry::check_user_cap_delete_entry` methods) with some override filters.

But before this can be done, let's take a step back and consider that allowing anyone to delete any entry is dangerous. So why would you want to give anyone access to delete any entry? What's your particular use case?

**Comment by daizprua** [comment]
I see that and thanks for the reply, already create a form field in the page and resolve the problem.
