### ISSUE TITLE
It is possible bulk delete results?

### ISSUE THREAD

**Issue by daizprua** [gravityview/GravityView#831]
I need delete multiple entries instead one by one. It is possible?

Screenshot: http://prntscr.com/dzh1tw

Thanks

**Comment by rafaehlers** [comment]
@daizprua you can do that through the Entries menu from Gravity Forms:

![gv-bulk](https://cloud.githubusercontent.com/assets/1222472/22473947/9463579c-e7c1-11e6-81cf-7313f6721165.jpg)
