### ISSUE TITLE
Fix notices about User Registration Add-on

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#838]
To be determined...

```
Notice: Trying to get property of non-object in /home/dh_7pkgit/deaportal.dreamhosters.com/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-user-registration.php on line 187

Notice: Trying to get property of non-object in /home/dh_7pkgit/deaportal.dreamhosters.com/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-user-registration.php on line 188

Notice: Trying to get property of non-object in /home/dh_7pkgit/deaportal.dreamhosters.com/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-user-registration.php on line 163
```

**Comment by soulseekah** [comment]
Interesting, I wonder what the edge-case is here. I wrote a quick test for this and managed to reproduce it by giving the entry a non-existent user_id as "created_by". How can this happen in real life? Only way I could think of is the user got deleted after the entry was created? Any way we can get more info on this?

`GravityView_Edit_Entry_User_Registration::match_current_display_name` or its caller need to handle this gracefully then, output an error saying that this entry has no user associated with it or something.

Test case in 646cc1a98d6d21676c1f869d3b3e4e4e1c29199c on the fix-838 branch.

**Comment by zackkatz** [comment]
> user got deleted some time after the entry was created

Yep. I'm writing some tests.
