### ISSUE TITLE
Add a created_by parameter to the [gravityview] shortcode

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#844]
Since we're planning to integrate that Adv. Filter functionality into core one day (created by > logged in user), this might be handy to filter by other users by using dynamically populated user IDs (using the {get} Merge Tag for example).

At this moment, there's no way to target that entry meta with the shortcode or even using the Adv. Filter to capture a URL parameter using the {get} Merge Tag: 

![gv-adv-filter](https://cloud.githubusercontent.com/assets/1222472/23030039/b456b492-f453-11e6-9222-ed76f015f4cd.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653371956768)

**Comment by rafaehlers** [comment]
ps.: I noticed that can be done with the Search Bar:

![gv-search-bar](https://cloud.githubusercontent.com/assets/1222472/23030226/495a0f6c-f454-11e6-8ea7-bebb1126578c.jpg)

And the variable will be: http://gravityview.com.br/view/contact-form/**?gv_by=12**&mode=any

**Comment by morrisao** [comment]
any update for this issue ?

**Comment by morrisao** [comment]
no news...good news ?

**Comment by austinsparx** [comment]
Adding support for this issue - think it would be a really great addition to GV for lots of use cases... business directory, job listings, portfolio items etc.

**Comment by rafaehlers** [comment]
`[gravityview id="1696" search_field="created_by" search_value="6"]`  works

**Comment by austinsparx** [comment]
@rafaehlers Thanks that is a great solution!

**Comment by zackkatz** [comment]
I believe this works: `[gravityview id="12" search_field="created_by" search_value="{current_user:ID}"]`

**Comment by soulseekah** [comment]
Jerry, can you please confirm and close if that works? @jlgrisham

**Comment by jlgrisham** [comment]
Have not been able to get this working:

[gravityview id="8" search_field="created_by" search_value="{current_user:ID}"]

Not returning results for any of my logged in users who created entries.

**Comment by soulseekah** [comment]
Oh that's probably because merge tags are not processed as search values. We've had a customer report this in a ticket.

https://secure.helpscout.net/conversation/985577527/23005/

Converting to valid but then.

**Comment by jlgrisham** [comment]
Ok this works with `user` instead of `current_user:`

`[gravityview id="8" search_field="created_by" search_value="{user:ID}"]`

**Comment by zackkatz** [comment]
Crap, yep—it's `{user}` or `{created_by}`. Sorry 'bout that!

https://docs.gravityview.co/article/281-the-createdby-merge-tag
