### ISSUE TITLE
Run the_content filter on Custom Content field and or widgets

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#846]
![-](https://cloud.githubusercontent.com/assets/1222472/23308576/6646de7a-fa8a-11e6-8e98-2db97bfaee84.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653395588963)

**Comment by zackkatz** [comment]
Does this need a checkbox? What about adding:

```
add_filter('gravityview/fields/custom/content_before', 'gv_apply_the_content' );

function gv_apply_the_content( $content ) {
  return apply_filters( 'the_content', $content );
}
```

How many users have requested this, @rafaehlers ?

**Comment by rafaehlers** [comment]
@zackkatz Whenever someone asks for it on support, I had to reply with that code, so an option will definitely save us some replies.

**Comment by soulseekah** [comment]
I like this.

**Comment by soulseekah** [comment]
We're already running `wpautop` and `do_shortcodes` in there manually. What's the exact purpose of this?

Stats for when this pops up:

![image](https://user-images.githubusercontent.com/685880/67157797-f88a2800-f339-11e9-9917-f8dfde0c10f5.png)

It seems that the only issue is embed codes? Maybe we just have a do_embed?

Is this an [XY problem](http://xyproblem.info/) perhaps?

**Comment by rafaehlers** [comment]
We haven't had any problems with this for some time now.
