### ISSUE TITLE
Custom Content widget isn't displaying when View is embedded

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#847]
Only happens on some themes. 

Steps to reproduce:
1) Add a Custom Content widget to a View's widget area
2) Add any text or HTML content inside this widget
3) The widget will only display if accessing the View directly /view/
4) If trying embedding the View in a page, it won't display.

Related: https://secure.helpscout.net/conversation/321249393/8297/?folderId=408730

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653412775855)

**Comment by zackkatz** [comment]
More background: 

This issue is (likely) caused by the theme pre-processing the post content ([see the code here](https://github.com/gravityview/GravityView/blob/master/includes/class-template.php#L920-L926)). We need a better way of not processing the code until it's meant to be displayed.

**Comment by rafaehlers** [comment]
This issue never happened again.
