### ISSUE TITLE
Embed stand-alone Edit Entry form via [gravityview] shortcode

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#850]
It would be great if you could output just the `edit` context via the shortcode. It would be used to embed user profile forms on pages, for example.

Currently, this _is_ possible, but only with lots of work configuring a Gravity Forms form in a complex way.

I imagine something like the following: 

`[gravityview id="123" context="edit" entry=""]` 

The `entry` parameter is the biggest question…

This `context` shortcode attribute could also be used as the way to render the oEmbed links:

`[gravityview id="123" context="single" entry="456"]`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653430145048)

**Comment by soulseekah** [comment]
Just throwing this in: `entry="latest"` - output latest entry in this view for current user (for viewing or editing). Perfect for profiles.

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/341315933/8689/

**Comment by soulseekah** [comment]
We should just extend the `gventry` shortcode, doh. It has a `view_id` parameter already :)

Starting work on this, shouldn't be hard at all.

**Comment by soulseekah** [comment]
Whew. Okay, let's have some initial testing, team!

We already have `last` and `first` special IDs. So a user profile would look like this:

1. Create a View, setup the edit fields
2. Setup an Advanced Filter to filter the View to logged in user
3. Add the [gventry view_id="1" entry_id="first" edit="1"] shortcode

Write a nice documentation for this @jlgrisham :)

**Comment by zackkatz** [comment]
Question: Does `entry_id` accept merge tags (like our `{get}` Merge Tag)? That'd be helpful.

**Comment by soulseekah** [comment]
> Question: Does `entry_id` accept merge tags (like our `{get}` Merge Tag)? That'd be helpful.

It does not do that currently, no. We only accept "first", "last", and ID or a slug.

The {get} merge tag might open sites up to attacks perhaps, editing entries that they're not supposed to be able to edit. What's the use case? An example would be helpful.

What other merge tags would we want?

**Comment by rafaehlers** [comment]
This doesn't work on GV 2.14.4

![image](https://user-images.githubusercontent.com/1222472/167889089-52a3bee4-9686-4e2a-af68-e48a643bfd8c.png)

![image](https://user-images.githubusercontent.com/1222472/167889139-003db4e8-bc0e-402f-8774-b80dbfa43ec1.png)

Not even when specifying the entry id in the shortcode.

**Comment by rafaehlers** [comment]
Implemented in 2.14.6: https://docs.gravitykit.com/article/845-embedding-the-edit-entry-form-into-a-page-or-post
