### ISSUE TITLE
Totals broken with shortcode offsets

### ISSUE THREAD

**Issue by soulseekah** [gravityview/GravityView#860]
Continuation of:

https://github.com/gravityview/GravityView/issues/851#issuecomment-283001284

Tests have been written for this in the "future" branch.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653662660080)

**Comment by soulseekah** [comment]
https://travis-ci.org/gravityview/GravityView/jobs/209878878#L380

**Comment by soulseekah** [comment]
![image](https://cloud.githubusercontent.com/assets/685880/24003665/e64930f4-0a85-11e7-8aaa-d649cf70352f.png)

Should be 1-1 of 2

![image](https://cloud.githubusercontent.com/assets/685880/24003684/f5764864-0a85-11e7-9aef-474829ccc736.png)

Should be 2-2 of 2

However, the `$first` and `$last` parameters are not subtracting the manual offset from the query offset, and it doesn't have access to it either. Perhaps we should be looking at the page number global instead?

Relevant code is in includes/class-frontend-views.php `getPaginationCounts`. Tests in `test_getPaginationCounts` pass but never take into account the manual offset.

**Comment by soulseekah** [comment]
In order to get rid of the confusion between this manual/forced offset (set in the shortcode or in the view settings) and the query offset (used in the `$paging` parameter to `get_entries`) we should refer to it as "nudge" perhaps?

That way we can pass the nudge parameter around and subtract if from the offset as necessary for all calculations.

Thoughts?

`$nudge` :raised_hand_with_fingers_splayed:

**Comment by zackkatz** [comment]
If necessary, I prefer `$start` - nudge is a physical act to me, not code…

**Comment by soulseekah** [comment]
Or `$skip`, perhaps, we can return to this later; not critical right now.

**Comment by zackkatz** [comment]
This _must_ be fixed! Closing 😁
