### ISSUE TITLE
"Move Featured entries To Top" option conflicts with Advanced Filter ANY

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#862]
### The Form:

![gv-bug-form](https://cloud.githubusercontent.com/assets/1222472/24117226/21494842-0d88-11e7-807a-2633fe48ae7e.jpg)

### Test Entries:

![gv-bug-entries](https://cloud.githubusercontent.com/assets/1222472/24117260/48c2d17c-0d88-11e7-97c4-6527e27413d6.jpg)

### The initial View: 

![gv-bug-view-1](https://cloud.githubusercontent.com/assets/1222472/24117329/96a2fb24-0d88-11e7-9db2-877dd3ec31f2.jpg)

### Advanced Filter setup:

![gv-bug-advsetup](https://cloud.githubusercontent.com/assets/1222472/24117297/755b4002-0d88-11e7-9f48-954d4cb9d9fa.jpg)

### View with filters :ok_hand: :

![gv-bug-view-2](https://cloud.githubusercontent.com/assets/1222472/24117379/c4a0b016-0d88-11e7-82bc-988557b4456e.jpg)
 
### Enabling the "Move Featured entries To Top" option:

![gv-bug-move](https://cloud.githubusercontent.com/assets/1222472/24117440/00421790-0d89-11e7-958a-9c4d84f71584.jpg)

### Resulting View (with filters and move featured to top) :-1: :

![gv-bug-view-3](https://cloud.githubusercontent.com/assets/1222472/24117503/44bdfb46-0d89-11e7-85d4-2d43e0f2ce29.jpg)

Happened on GV 1.20.1 and AdvFilters 1.20

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653693203361)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/335549492/8578/?folderId=408730

**Comment by rafaehlers** [comment]
Also, "Move featured entries to top" option also breaks the pagination option "All" of DataTables.

**Comment by soulseekah** [comment]
Need a retest please with 2.x

**Comment by jlgrisham** [comment]
"Move featured entries to top" working as expected with the ANY Advanced Filter and with the All option for DataTables pagination.
