### ISSUE TITLE
[gvlogic] shortcode attribute fails when content contains quotes

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#864]
The shortcode attributes need to be sanitized, so that if the merge tag content contains double-quotes, it won't fail: `if="{Merge Tag:1}"` becomes `if="Value with "quotes""`, which will break.

We need to sanitize single and double quotes using `_wp_specialchars( $attr, ENT_QUOTES );`

HS#8627

**Comment by zackkatz** [comment]
See https://secure.helpscout.net/conversation/337742334/8627/

**Comment by soulseekah** [comment]
I am unable to reproduce this on `develop` or `2.0`, or `master` for that matter. Or even `1.9`.

![image](https://user-images.githubusercontent.com/685880/30476066-491ffc5e-9a22-11e7-92c7-1b8f29a7ecca.png)

![image](https://user-images.githubusercontent.com/685880/30476080-566d3958-9a22-11e7-9496-c7bc7347cb52.png)

No breakage seems to occur. What am I missing?

**Comment by soulseekah** [comment]
As stored in the database:

![image](https://user-images.githubusercontent.com/685880/30476398-52341464-9a23-11e7-99cf-675ac38ab23c.png)

As output:

![image](https://user-images.githubusercontent.com/685880/30476417-66d9209e-9a23-11e7-9164-d0c261b22b70.png)
