### ISSUE TITLE
Who's currently editing feature suggestion

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#877]
Here's a suggestion for the Edit Entry page from one of our users:

>When using gravity view with multiple editors, editing the same content, its critical to have the option to >display two kinds of messages to a user.
>1. Currently in edit mode by: "userid" (or any info from the user profile).
>2. Last edited by: "userid", on "last-modified-date".
>As V2 for the feature to have an option to limit access to the edit mode if the entry is currently being edited by specific roles.

Gravity Forms supports this with `GFEntryLocking`; add this to Edit Entry when an entry is being edited as well.

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/350738829/8946/

**Comment by zackkatz** [comment]
This would use Gravity Forms' built-in `GFAddonLocking` system.

**Comment by soulseekah** [comment]
Duplicate https://github.com/gravityview/GravityView/issues/950

**Comment by zackkatz** [comment]
Also requested by [HS#12546](https://secure.helpscout.net/conversation/486413067/12546?folderId=408730)

**Comment by soulseekah** [comment]
The Heartbeat API is also nice.

https://developer.wordpress.org/plugins/javascript/heartbeat-api/

**Comment by soulseekah** [comment]
Since we will have to synchronize with the edit backend we'll have to use GFEntryLocking for sure, piggyback off its functionality as suggested by Rafael.

**Comment by soulseekah** [comment]
![image](https://user-images.githubusercontent.com/685880/68662120-4109bf80-054d-11ea-8868-388c69ab74f2.png)

Almost there.

**Comment by soulseekah** [comment]
Jesus the whole heartbeat thing they have setup is pretty feeble. Breaks 50% of the time when testing the backend manually. Our thing will behave in a similar unreliable way :) for now.

**Comment by zackkatz** [comment]
@soulseekah it should also prevent non-admins from being able to edit at all. Can you write a doc with how it’s supposed to work, so we can test against that?

**Comment by soulseekah** [comment]
All edit locks are purely advisory and are JavaScript based. It's very simple to bypass them. Just like it's easy to bypass Post locks in WordPress. It has nothing to do with user permissions, @zackkatz. Let me know if I'm missing something, please.

**Comment by soulseekah** [comment]
This is ready to be tested. It's pretty raw but it should work overall. I've done a lot on my end but you guys might manage to break things :)

**Comment by soulseekah** [comment]
The AJAX heartbeat/lock refresh end of things have to be tested as well here.

**Comment by zackkatz** [comment]
Added in 2.6
