### ISSUE TITLE
Edit entry does not show value on few fields

### ISSUE THREAD

**Issue by rozkminiam** [gravityview/GravityView#882]
I have created form that is using multi select field. Choices are loaded from another form entries. I does work fine. Edit entry works in admin panel GF edit entry but when I edit this field in GV (gv_entry_link action="edit"/).  Field is empty. No choices are selected. I have tried use field_values="name=value" in link but didn't help. Create new form or entry didn't help too. Reinstall both plugins GF and GV didn't help either. What is bigger issue it does not concern all that type of fields. Same form is using this option in about 6 fields and most of them are working. Other fields are just normal drop down with predefined choices and randomly some of them are working some of them are blank in edit. 
After I select all choices AGAIN in edit entry and save it they are saved and can be display in GV but again when I edit them same fields are empty. 
I saw similar issue but they said it because GF conditional logic. Unfortunate even if there is no logic in form it  does the same

**Comment by soulseekah** [comment]
Thanks for the report. Is there any way for you to provide the smallest setup description possible? The shortest step-by-step guide to reproduce the issue, please?

Thanks.

**Comment by rozkminiam** [comment]
Problem is form and view I created some time ago and there were no issue. I found it 2 days ago. 
And as I said it is random issue. Once I create new form new drop down menu new view and it is working ok in edit. Other time I clone all steps and it does not working.
![edit first time](https://cloud.githubusercontent.com/assets/28226608/25566154/d5107a2c-2dcb-11e7-8d92-640f4fd1c4b4.jpg) this is first time edit. Field device should have selected choices but there ware empty(I add it)
![edit saved](https://cloud.githubusercontent.com/assets/28226608/25566164/efd4e5dc-2dcb-11e7-95cc-d888babf971f.jpg) here after update field does not save selected choice.
![edit reloaded](https://cloud.githubusercontent.com/assets/28226608/25566170/0df44490-2dcc-11e7-9183-ecc3be21bb0f.jpg) After reload edit fields are still empty. GV display changes in view and GF edit show this selected choices.
Field device loads choices from another form entries. But there is another 5 fields (eg service available in) that is doing the same and it does save and show them. Field "P & S type" is normal drop down with predefined choices (not dynamical)

**Comment by rozkminiam** [comment]
Choices from another from entries snippet:
class GW_Populate_Entries {
    public function __construct( $args = array() ) {
        // make sure we're running the required minimum version of Gravity Forms
        if( ! property_exists( 'GFCommon', 'version' ) || ! version_compare( GFCommon::$version, '1.8', '>=' ) )
            return;
        // set our default arguments, parse against the provided arguments, and store for use throughout the class
        $this->_args = wp_parse_args( $args, array(
            'target_form_id'  => false,
            'target_field_id' => false, // must be a choice-based field (drop down, radio, checkbox)
            'source_form_id'  => false,
            'value'           => false, // can be a field ID or a 'template' string with merge tag support
            'label'           => false, // can be a field ID or a 'template' string with merge tag support
            'query_args'      => array()
        ) );
        $this->_args['query_args'] = wp_parse_args( $this->_args['query_args'], array(
            'status'        => 'active',
            'order'         => 'asc',
            'order_by'      => 'date_created',
            'nopaging'      => true,
            'offset'        => 0,
            'page_size'     => 20,
            'field_id'      => false,
            'field_value'   => '',
            'field_filters' => array()
        ) );
        if( $this->_args['query_args']['field_id'] ) {
            $this->_args['query_args']['field_filters'] = array(
                array(
                    'key' => $this->_args['query_args']['field_id'],
                    'value' => $this->_args['query_args']['field_value']
                )
            );
        }
        $is_no_paging = $this->_args['query_args']['nopaging'] == true;
        $this->_args['paging'] = array(
            'offset'    => $is_no_paging ? 0 : $this->_args['query_args']['offset'],
            'page_size' => $is_no_paging ? 999 : $this->_args['query_args']['page_size']
        );
        $this->_args['sorting'] = array(
            'key'       => $this->_args['query_args']['order_by'],
            'direction' => $this->_args['query_args']['order']
        );
        // time for hooks
        add_action( "gform_pre_render_{$this->_args['target_form_id']}",            array( $this, 'populate' ) );
        add_action( "gform_admin_pre_render_{$this->_args['target_form_id']}",      array( $this, 'populate' ) );
        add_action( "gform_pre_submission_filter_{$this->_args['target_form_id']}", array( $this, 'populate' ) );
    }
    public function populate( $form ) {
        foreach( $form['fields'] as &$field ) {
            if( $field['id'] != $this->_args['target_field_id'] )
                continue;
            $entries = $this->get_entries_for_population( $this->_args['source_form_id'] );
            $choices = array();
            foreach( $entries as $entry ) {
                $value = $this->get_entry_value( $entry, $this->_args['value'] );
                $label = $this->_args['label'] ? $this->get_entry_value( $entry, $this->_args['label'] ) : $value;
                $choices[] = array(
                    'text' => $label,
                    'value' => $value
                );
            }
            if( empty( $choices ) ) {
                $choices[] = array(
                    'text' => __( 'There are no options available currently.' ),
                    'value' => ''
                );
            }
            $field['choices'] = $choices;
            if( GFFormsModel::get_input_type( $field ) != 'checkbox' )
                continue;
            $field['inputs'] = array();
            foreach( $choices as $id => $choice ) {
                $field['inputs'][] = array(
                    'id' => sprintf( '%d.%d', $field['id'], $id + 1 ),
                    'label' => $choice['text'],
                    'name' => ''
                );
            }
        }
        return $form;
    }
    public function get_entries_for_population( $form_id ) {
        return GFAPI::get_entries( $form_id, $this->_args['query_args'], $this->_args['sorting'], $this->_args['paging'] );
    }
    public function get_entry_value( $entry, $template ) {
        $field_id = intval( $template );
        if( $field_id )
            return rgar( $entry, $field_id );
        $form = GFAPI::get_form( $entry['form_id'] );
        $template = GFCommon::replace_variables( $template, $form, $entry, false, true, false, 'html' );
        return $template;
    }
}
# Configuration
new GW_Populate_Entries( array(
    'target_field_id' => 18,         // the field to be populated with entry data; must be a choice-based field (drop down, radio, checkbox)
    'target_form_id' => 21,        // the form that contains the field to be populated
    'source_form_id' => 12,        // the form from which entry data should be retrieved
    'value' => '{Brand:11} {model:2}',        // the id of the source field
    'label' => '{Brand:11} {model:2}',  // this is the label for the desired 'value'
    'query_args' => array(          // specifies which entries should be pulled for display
        'order' => 'asc',
        'order_by' => '2',
        'nopaging' => true
    )
) );

**Comment by soulseekah** [comment]
I setup a quick test. But I was unable to reproduce this, everything worked fine, see gif:

![out](https://cloud.githubusercontent.com/assets/685880/25566817/f00b56b0-2dfa-11e7-8b2b-ae132ae17149.gif)

GravityView 1.21.4
Gravity Forms 2.1.3.10
WordPress 4.7.3

Where did you paste your `GW_Populate_Entries` snippet? Are you sure it's not loading too early?

**Comment by rozkminiam** [comment]
even if I'm not using snippet it doesn't work. If you have some time just check yourself. I created account and necessary content to see it. Link include steps how to get there
[link](http://just-fixit.co.uk/edit-product-service-bug/)

**Comment by rozkminiam** [comment]
I can confirm Gravity View does not support multi select in edit entry Gravity Forms v 2.2.1.12 . I downgrade GF to 1.21.4 and it is working now

**Comment by soulseekah** [comment]
We'll leave this open and push out a fix for GF 2.2 support soon. Thank you for reporting the issue and helping to debug it.

**Comment by rafaehlers** [comment]
@rozkminiam Works fine for me with the same version of GF's version 2.2.1: http://take.ms/OpCv0

**Comment by zackkatz** [comment]
> I can confirm Gravity View does not support multi select in edit entry Gravity Forms v 2.2.1.12 . I downgrade GF to 1.21.4 and it is working now

We submitted a bug report to Gravity Forms and they fixed this issue in an update; it seems it's in 2.2.1.

**Comment by soulseekah** [comment]
Hey @rozkminiam can you please add the following to your functions.php

```php
add_filter( 'gravityview/edit_entry/field_value_multiselect', 'gv_patch_882_fix_multiselect_value_serialization', 10, 3 );
function gv_patch_882_fix_multiselect_value_serialization( $field_value, $field, $_this ) {

$maybe_json = @json_decode( $field_value, true );
if ( $maybe_json ) {
    return implode( ',', $maybe_json );
}
return $field_value;
}
```

And see if it works for you on GF 2.2, please? Thanks.

**Comment by rozkminiam** [comment]
Aw thanks for solution. But I decided do not update GF. to much problems for me. I afraid something else will stop working. Will do it someday when WP won't be compatible.
