### ISSUE TITLE
Rename "Multiple Entries" and "Single Entry"

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#884]
After talking with Juniper, the phrases "Multiple Entries" and "Single Entry" are confusing.

Instead, use "Entries" (what GF uses) and "Entry Details". 

Thoughts?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995655060391384)

**Comment by soulseekah** [comment]
Where are we at with this? :)
