### ISSUE TITLE
Autonumbering Rows

### ISSUE THREAD

**Issue by mTorkaman** [gravityview/GravityView#886]
greetings ,
how i can make like this ?
add auto numbers on columns

example : 💯 
![untitled](https://cloud.githubusercontent.com/assets/7404107/25847114/05eb34b6-34ca-11e7-81d4-8755c8782515.png)

**Comment by soulseekah** [comment]
You can do this with a custom content field, and your own shortcode or your own merge tag.

Here's an example with a very simple shortcode that you can create in your functions.php:

```php
add_shortcode( 'issues_886_numerics', function( $atts ) {
    static $counter = 1;
    return $counter++;
} );
```

![image](https://cloud.githubusercontent.com/assets/685880/25863699/3be9a386-3506-11e7-94b8-eaead9e97496.png)

![image](https://cloud.githubusercontent.com/assets/685880/25863764/7be255dc-3506-11e7-97b0-3e7fb88d285e.png)

Note that this is just an example and will need more fine-tuning if you are, for instance, displaying several views on a single page. It will also not work with pagination as is, so be careful.

Another option is to just output the Entry ID field which will be unique and never mix.

**Comment by mTorkaman** [comment]
really thank you mr soulseekah .
it was useful for me
