### ISSUE TITLE
Edit Entry Link Cache Problem

### ISSUE THREAD

**Issue by jakejackson1** [gravityview/GravityView#887]
If you embed a view on a page with an Edit Entry link and use it, then decide you want to make the page the "Front Page" the Edit Entry link incorrectly points to the original URL instead of the front page URL. 

The issue stems from the caching code `$link = wp_cache_get( 'gv_directory_link_'.$post_id );` in the `GravityView_API::directory_link()` method.

**Comment by zackkatz** [comment]
I'm pretty sure this will fix the problem—if not, please re-open!
