### ISSUE TITLE
How to use [else if="{another field:123}" is="example"] shortcode?

### ISSUE THREAD

**Issue by pareshmithra** [gravityview/GravityView#889]
I'm trying to use below shortcode in custom content field. But it is not working.

EX:
[gvlogic if="{abc:1}" isnot=""]
Display ABC
[else if="{xyz:2}" isnot=""]
Display XYZ
[else]

[/gvlogic]

Please help me.

**Comment by rafaehlers** [comment]
@pareshmithra "else if" is not yet supported: http://docs.gravityview.co/article/252-gvlogic-shortcode
