### ISSUE TITLE
Store the date-time when the entry was approved (or approval changed status)

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#890]
Also, allow it to trigger a notification.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/364419118/0/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/517706047/13183?folderId=408730

**Comment by zackkatz** [comment]
Notifications were added in 2.1, and Entry Revisions can handle the date-time.

**Comment by amuhareb** [comment]
this is not actually functioning.

wondering about utilizing this snippet as a temporary fix:
https://gist.github.com/13122310958/869111b85b844b0999328a9cb3073d59
