### ISSUE TITLE
When "Contact Form 7 Style" plugin is activated, Views are not rendered

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#892]
https://wordpress.org/plugins/contact-form-7-style/

I imagine it's a conflict with a `the_content` filter somehow.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995655081378988)

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/368919531/9376/

**Comment by rafaehlers** [comment]
>This plugin has been closed as of February 1, 2021 and is not available for download. Reason: Security Issue.
