### ISSUE TITLE
Add hook to disable Notes creation

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#894]
One of our users asked for this: https://secure.helpscout.net/conversation/342674635/8730/?folderId=408735

`add_filter( 'gravityview_disable_change_entry_creator_note', '__return_true' );`

@zackkatz want to complement?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/342674635/8730/?folderId=408735

**Comment by soulseekah** [comment]
It will be included in the next minor release:

https://github.com/gravityview/GravityView/blob/develop/includes/class-gravityview-change-entry-creator.php#L76

1.21.5. No ETA on its release, though.

But it's not in current 1.21.4

**Comment by zackkatz** [comment]
Added in 1.21.5
