### ISSUE TITLE
[gvlogic] inside [gvlogic]

### ISSUE THREAD

**Issue by rozkminiam** [gravityview/GravityView#897]
I had small issue to create 2 different answers depends on 2 different conditions.
```
[gvlogic if='{field:21}' isnot='Premium']<div style="display: none;">[/gvlogic][gvlogic if='{get:page}' is='']
[gravityview id='1207' search_field='44' search_value='{Business ID:7}'][/gvlogic]</div>[gvlogic if='{:21}' is='Premium']<div style="display: none;">[/gvlogic][gvlogic if='{get:page}' is='']
[gravityview id='[gravityview id='3145' page_size='1' search_field='44' search_value='{Business ID:7}'][/gvlogic]</div>
```
is there easier way to do it? such as `[gvlogic if={something} is='same' and if='something else' is='not same']display[/gvlogic]` or insert [gvlogic] inside [gvlogic]

**Comment by zackkatz** [comment]
Check this out; that'll work for you!: https://gist.github.com/zackkatz/e1f689c16238acfed76e
