### ISSUE TITLE
Check number sorting in Future

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#906]
Hey @soulseekah - can you please check number sorting? It seems we may have a regression here.

It's the old "count to 2" issue:

1
10
11
11
13
14
15
2
3
4
5
6

https://secure.helpscout.net/conversation/390280095/9777/

**Comment by soulseekah** [comment]
Number sorting on number fields is numeric, always.

He is sorting by a hidden field. Hidden, text, etc. fields are sorted by alpha. We do not have a setting in place to force sort by numeric or other custom sorting functions.

Thoughts?

**Comment by zackkatz** [comment]
Oh, I thought it was number field, not hidden field. There's a way to do this, by changing the search parameters using `is_numeric => 1`: https://gist.github.com/zackkatz/9e10d34c04fd3d22cd5aff192b9cc4de

This'll have to be customized for the user. I'll update them.
