### ISSUE TITLE
Update from 1.17 to Current - Information Disclosure bug

### ISSUE THREAD

**Issue by aedelgod** [gravityview/GravityView#910]
> [redacted] for possible security reasons. Will update once investigated.
> 
> \- Zack

**Comment by rozkminiam** [comment]
That is why I use double ways to hide users entries. Use gvlogic. If user is entry-creator. one of options fail still you have extra protection. To hide data from other users

**Comment by aedelgod** [comment]
Hi,

Would it be possible to share an example of this? I have never had myself or another client have a need for this and I have never used GF/GV. Thanks.

**Comment by zackkatz** [comment]
@aedelgod This was likely a patched issue, but please share details regarding how you would reproduce this issue with support@gravityview.co

It's definitely a good idea to have your clients maintain updated versions of the plugin!

**Comment by aedelgod** [comment]
In my DEV copy I made of the current site which had no plugins updates I updated all plugins to current releases with the exception of GravityView which was on 1.17. (Everything was working as it should still). I downloaded the current GravityView zip from GitHub > Deactivated 1.17 > uploaded version 1.21.5.3 and activated it. Checked on my devuser account I created and was able to see ALL entries from ALL users. The pages only include the default shortcode. I can view and clone all entries with devuser (subscriber). This is with and without the addition of: user_edit="1" in the shortcode. In 1.17 there were no other entries printed from shortcode that did not belong to the user, only user entries were printed in the list (table). Any upgraded version past 1.17 breaks this check and prints all data for that form.

**Comment by zackkatz** [comment]
@aedelgod Thank you for reporting; in the future please report any potential security issues to support@gravityview.co rather than posting on GitHub. I'm sharing with our team and we'll get back to you.

I will be updating this ticket for security purposes; the content will be removed.

**Comment by zackkatz** [comment]
@aedelgod It's likely that the Advanced Filtering extension got disabled. The other possibility is a theme's `functions.php` file got modified, which had been filtering entries.

If you're just displaying the plain shortcode, those are most likely the issue. The `user_edit=1` shortcode attribute is not related to entry visibility.

**Comment by aedelgod** [comment]
@zackkatz is there any way you could email or send a link to the extension for testing before we renew the license? Or would it be possible to provide a 7-14 day license for us to do this? The client's license expired June 16, 2017. They don't appear to have ever installed an Advance Filtering extension with GravityView 1.17. Thanks.

**Comment by zackkatz** [comment]
@aedelgod We'll respond via the support channel, chat there soon.

**Comment by aedelgod** [comment]
The issue was resolved by using the "Advance Filtering extension" Thanks again Gravity View!
