### ISSUE TITLE
WooCommerce support

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#912]
Basically we need to support "products" created with this add-on: https://woocommerce.com/products/gravity-forms-add-ons/ that will allow our users to edit them on the front-end of the website.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656545623641)

**Comment by soulseekah** [comment]
We'd need access to the latest version of the plugin if possible, @zackkatz. I have some old versions from GitHub, not sure we're sage using them.

**Comment by zackkatz** [comment]
@soulseekah We can use this for now, assuming it's updated. 

https://github.com/wp-premium/woocommerce-gravityforms-product-addons

**Comment by rafaehlers** [comment]
Just an FYI this hasn't been requested anymore.

**Comment by zackkatz** [comment]
@soulseekah Let's hold off on this. Closing for now until interest picks up.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1441497228/32910

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1469087654/33541/
