### ISSUE TITLE
Shortcodes in pure PHP

### ISSUE THREAD

**Issue by rozkminiam** [gravityview/GravityView#913]
I know this is not an issue but I need PHP code for [gravityview] shortcode. I would like to add View into page php and normal shortcode doesn't work there. (Probably because it is already inside another shortcode - not GV). It is like put static View in single.php but with extra search functions based on ACF fields.
I need a php that do the same what this shortcode  [gravityview id="1" search_field="1" search_value="value"]. Search value is technically <?php the_field('custom_field'); ?>

I  know I could use my gv support thing but here you replay quicker

**Comment by soulseekah** [comment]
Try the 2.0 branch, see if it works, since the short code was rewritten from scratch.

**Comment by rafaehlers** [comment]
@rozkminiam check this: http://docs.gravityview.co/article/411-how-to-filter-results-on-a-view

The only exception being the DataTables View Type, which doesn't work.
