### ISSUE TITLE
Inline Edit Filters 

### ISSUE THREAD

**Issue by rozkminiam** [gravityview/GravityView#915]
I do have a small problem with Inline Edit. I would like to give an access to normal user to just quick edit their entries however I can't. 
To make it work I have to give permission to **gravityforms_edit_entries**, **gravityview_edit_form_entries** **and gravityview_edit_entry**.
**gravityforms_edit_entries** - this means user has an access to edit all entries not even his own. 
**gravityview_edit_form_entries** - this will give an access but there is no button to disable quick edit and this means no any link is working (even after change cursor to default).
So this 3 rules are necessary. 

I could bypass it by using gvlogic and advanced filters but maybe there is a faster way to ignore gravityforms_edit_entries

**Comment by zackkatz** [comment]
You can modify the capabilities that are checked using the `gravityview-inline-edit/inline-edit-caps` filter.

But you can also use the `gravityview-inline-edit/user-can-edit-entry` filter to override the result. [Check out the docs](http://docs.gravityview.co/article/414-inline-edit-filters#toc_3).
