### ISSUE TITLE
Hard coding a license with DEFINE not always work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#917]
Related: http://docs.gravityview.co/article/54-how-can-i-hard-code-my-license-key

Feedback from a user:

>It appears that if a site had ever activated GV, causing gravityformsaddon_gravityview_app_settings to be an entry in the options table, and then a define was added to wp-config.php, the define is never used.
>
>To fix that, one must a) delete the old record from the DB and b) flush memcached.
>
>Shouldn't the logic be to check if the define is different from what's in the DB and provide the ability to use the define?
>
>And shouldn't the key be obscured, the way Gravity Forms itself does? Is there a way to obscure it?

**Comment by erikvanbeek** [comment]
I also have this problem on my multi-site (define( 'GRAVITYVIEW_LICENSE_KEY', 'YOUR_KEY_HERE' ); is added to wp-config.php, but I keep getting this big notice that I GV is not activated yet on every sub-site). But now I know how to fix it ;-)
