### ISSUE TITLE
User Registration Feed not working correctly

### ISSUE THREAD

**Issue by Koli14** [gravityview/GravityView#920]
I created a Gravityform with the User Registration Feed add-on. 
By all the entries there is a Note from GV: _Success: Assigned User ID #XY as the entry creator._
By most of the entries at the [Entry Creator](http://docs.gravityview.co/article/110-how-can-i-change-the-creator-of-an-entry-in-gravity-forms) it says No User, but by some it says the creator of the Entry 
(from 321 entry 20 times).
I can not figure it out, why did he sometimes assigned a User to an Entry, and why it did not by other times. 

I would like to create a View with the help of the Advanced Filter, where peoples can edit their own Entries, but at the moment it works for some users, and not works for many. 
(if a logged-in user was submitting a form, it was always working correctly)
Do you have any ideas, or suggestions?
![user_reg](https://user-images.githubusercontent.com/400223/30218530-89f761a4-94b9-11e7-8872-b5494f4b7b79.png)

**Comment by zackkatz** [comment]
This is likely an issue we fixed a while ago, where the user list doesn't include every user. Update to the latest and it should work.

If that's not it, please contact us via support.

**Comment by Koli14** [comment]
Dear @zackkatz,
All my plugins are the latest versions. But I do not have a license key, so I can not contact via support, and I also do not expect a support. But I did believed, its a bug, thats why I wrote here. But I tried it in a brand new website now,  and there it was working correctly.
Thx.
