### ISSUE TITLE
Editing an entry strips the labels from product calculation fields, nulls totals

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#924]
The labels get stripped from the receipt table after editing in Edit Entry; probably due to bad serialization?

Also look into whether it's the deleting of the entry meta on `GravityView_Field_Product::clear_product_info_cache()` method

![](http://share.gravityview.co/cIUn8M/2ZQVyAVw+)

See [HS#10931](https://secure.helpscout.net/conversation/430351819/10931/).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656589921776)

**Comment by soulseekah** [comment]
Several issues after editing on that particular form. 1 before edit. 2 after edit.

![image](https://user-images.githubusercontent.com/685880/30498708-229c7af4-9a71-11e7-921d-3d7778099c23.png)

**Comment by soulseekah** [comment]
Better, but we're still losing some of the numbers.

![image](https://user-images.githubusercontent.com/685880/30513936-c0bc46e2-9b25-11e7-92aa-3828cad7f476.png)

The "Secured" thing is an internal field from their theme's functions.php, so irrelevant to the bug.

**Comment by mashdun** [comment]
Hi Guys... I'm the one that reported the bug. Is it possible to just open the form back in the original window like this plugin does?
https://codecanyon.net/item/gravity-forms-list-edit/5968424
What is the pros and cons of editing in the GV window? 

Also... I use a plugin for collapsible sections of the form. In the main form, the section headers are gold...
https://snag.gy/tmZCDe.jpg

When editing an entry... I lose the color of the section headers... not sure what is causing it to be striped.
https://snag.gy/G3tT16.jpg

**Comment by soulseekah** [comment]
We do have a complete revamp of the Edit component within GravityView planned for early next year, so stay tuned. It should solve a lot of the issues we have with entry editing, including the ones you address. Thanks Matt/@mashdun :)

**Comment by mashdun** [comment]
Next year? I’ve built an entire sales portal around this plugin that isn’t working properly. When we are sending quotes, purchase orders and bill of sale documents to customers, there isn’t an option for them to be inaccurate or we will either lose money, get sued or both. Are you saying your not going to get to fixing the issues until 2018?

**Comment by soulseekah** [comment]
Matt, I'm sorry for the confusion. What I mean is that the Edit component within GravityView will be rewritten from the ground up, simple as that. The issue that you reported originally (labels disappearing) has been fixed. You are welcome to report all other issues that are critical for your use-cases via our support portal and we will look into them.

Thanks.

**Comment by mashdun** [comment]
Shew... great. I'm guessing I'll need to download the updated plugin from GV?

**Comment by soulseekah** [comment]
Matt, the updated plugin was sent 2 days ago as a zip file via our support department. Write to support if you didn't receive it, etc.

**Comment by mashdun** [comment]
I never received it. I will reach out to them. thanks

**Comment by soulseekah** [comment]
Sent on the 16th of September:

If you didn't get it I can try resending.

![image](https://user-images.githubusercontent.com/685880/30600533-2b6b15c2-9d79-11e7-8f5a-65d8a492fa7f.png)

**Comment by mashdun** [comment]
I went back through all my emails and didn't see it. Our spam filter may have gotten it. I've emailed support and asked them to resend it.

**Comment by soulseekah** [comment]
Gravity Forms saves fields 297, 298, 299 as 0 even though  they were populated on entry creation.

![image](https://user-images.githubusercontent.com/685880/30717835-8c39deaa-9f37-11e7-8b6c-32ace01e7a9a.png)

However, calculation (Number) field 487 is saved as a negative number.

![image](https://user-images.githubusercontent.com/685880/30717922-c54dc238-9f37-11e7-8698-aec4b77850f5.png)

The only thing they have in common is using {Total:300}. 487 does {Total:300} - lots of stuff (which explains the negative number). And the other 3 use {Total:300} * X which explains the 0. But as we can see field 300 has the correct total in it stored in the database.

The form itself must be buggy somehow. And we can't work with a buggy form like this.

On a happier note, GravityView saves the calculation result into the database after recalculations correctly, as it the total seems to be fine in our form, which is why we're seeing the added numbers.

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/708219855/17641/

**Comment by soulseekah** [comment]
It's back, but I'll check before reopening: https://secure.helpscout.net/conversation/946590013/22329

**Comment by soulseekah** [comment]
The label is indeed being lost in some weird cases. I could not reproduce. This:

```php
add_filter( 'gform_get_field_value', function( $value, $entry, $field ) {
	if ( $field->id == 489 && empty( $value['489.1'] ) ) {
		$value['489.1'] = 'Discount or Credits';
	}
	return $value;
}, 10, 3 );
```

Along with this: `delete from wp_gf_entry_meta where meta_key like 'gform_product_info%';` will help with such rare edge cases meanwhile.
