### ISSUE TITLE
editing impossible

### ISSUE THREAD

**Issue by thenax** [gravityview/GravityView#925]
I created a personalized view by the values picked from a gravity form.
I have a big problem: I can see all the posts and if I click on 'delete' the post is deleted (www.xxxxx.it/view/edit-events/…) , but if I click on 'Edit' I redirect to the right page but it's empy: no fields, no values, but only the post title! (www.xxxxx.it/view/edit-events/entry/30/?edit=ceb2813104)
The post Id is 29844, in this example.
I already checked all the permission with members and inside gravity.
What's happen??

**Comment by soulseekah** [comment]
Please visit https://gravityview.co/support/ and create a technical support request.
