### ISSUE TITLE
Embedding an "ugly" permalink of a single entry page won't work

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#927]
If you try to embed a permalink like this into a post or page, it won't work:

`http://gravityview.com.br/?gravityview=planets&entry=8494`

But if you embed it like this:

`http://gravityview.com.br/view/planets/entry/8494/`

It works!

**Comment by soulseekah** [comment]
Filed upstream https://core.trac.wordpress.org/ticket/42148 might get through in a couple of years.
