### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by Kuzovlev-Sanya** [gravityview/GravityView#928]
I have two views with different ids on one page. In one view there is a search bar. Use of this search bar affects the result list of the second view. How to solve this problem?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656888398636)

**Comment by Kuzovlev-Sanya** [comment]
![gvrs](https://user-images.githubusercontent.com/24545497/31439559-44df820e-ae95-11e7-858a-6b38b3892b08.gif)

**Comment by soulseekah** [comment]
This needs retesting.

**Comment by rafaehlers** [comment]
This shouldn't be happening anymore. For the second View to be affected, it has to have a Search Bar as well.

**Comment by zackkatz** [comment]
When testing, make sure that the forms include fields that have the same IDs

**Comment by rafaehlers** [comment]
This is not considered a bug anymore, but useful functionality.
