### ISSUE TITLE
GVCommon::check_entry_display() may not filter Post Categories properly

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#929]
This may be due to data structure, and the `GFFormsModel::is_value_match()` comparison method.

1. Multiple Views on a page, connected to same form
2. The form has a field defining post categories
3. The Views are filtered by post category
4. Click on a single entry, and the `Entry cannot be displayed. Failed a criterium for ALL mode` message is triggered

See [HS#11545](https://secure.helpscout.net/conversation/447503938/11545?folderId=408730)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656890469757)

**Comment by soulseekah** [comment]
An overhaul of check_entry_display is required for https://github.com/gravityview/Advanced-Filter/issues/61

**Comment by soulseekah** [comment]
Entries should be checked by all IDs within a View in the current context.

**Comment by soulseekah** [comment]
Post Categories should work fine with the newer $view-based flow with GF_Query. I'm trying to make sure that check_entry_display is called with $view as a second parameter in all of our cases (except unit tests).

**Comment by soulseekah** [comment]
https://github.com/gravityview/GravityView/issues/1185

This is an issue with GF_Query again. Looks like we don't support relative dates in plain GF_Query. It works fine for AF.

**Comment by soulseekah** [comment]
I need to write tests for this particular issue with Post Categories and it can be closed. Stay tuned.

**Comment by soulseekah** [comment]
This needs more work. We can't deprecate old path because there's GVCommon::get_entry which uses it without an ad-hoc View atm. We can maybe try is_view() or something, I'm still investigating. This is tough to get right :(

**Comment by soulseekah** [comment]
This is done.

A couple of things for those who will be looking at related code in the future:

check_entry_details expects everything to have been converted to SQL query form. That is if GF_Query doesn't know how to go from "today" to "2019-01-14" then don't try to feed it this. This will make sense as we use get_entries() and if the query doesn't have the proper values then the View will not output the entries to begin with. Things get complicated when using the legacy search_criteria filters. Remember: they are bad and should not be used. Look at how Advanced Filters handles things.

There will be small issue but everything can be solved pretty easily with adhoc contexts and GF_Query.
