### ISSUE TITLE
Add ability to duplicate entries

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#930]
Add a field that, when clicked, would duplicate an entry on the frontend.

GravityWiz already has some code for this: https://gist.github.com/spivurno/32e914d67723f89717be2904ce6234c4

----

Maybe implement as a pseudo-field like Edit Entry.

Questions: 

- Would it clone the entry exactly, or would it update the entry to change the `created_by` meta to make the entry creator the person clicking the link?
- What happens after click? A redirect? Or is this AJAX, so it'd just clone below and `$.slideDown`?
- Add another custom capability (`gravityview_duplicate_entry`)
- How to handle form feeds

https://app.drift.com/inboxes/57311/conversations/37323244

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656893917778)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/746483339/18423/

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/817608180/19994

**Comment by soulseekah** [comment]
> Would it clone the entry exactly, or would it update the entry to change the created_by meta to make the entry creator the person clicking the link?

I would change the `created_by` to the user doing the cloning, but we should certainly have a filter to override and allow users to set the creator to anyone they like, and not only that but all the fields. Maybe through an action (`gravityview/entry/duplicated`) that they can then do a `GFAPI::update_entry` call. Or have it configurable in the field settings.

> What happens after click? A redirect? Or is this AJAX, so it'd just clone below and $.slideDown?

I think just reloading the page with a message on top (like after Edit) would work well here.

> Add another custom capability (gravityview_duplicate_entry)

Yes.

> How to handle form feeds

Not only this, but how to handle hooks, entry limitations, validation (unique values, for example), etc. Creating an entry (just like with import entries) has a lot of potential side-effects that some may want, others not. Everything can be solved with UI configurations and filters :)

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/984671634/22990?folderId=408730

**Comment by vendojo** [comment]
Thank you very much @zackkatz for pointing me to this issue. Really looking forward to the development of this additional feature. Please let me know if you need feedback from a potential user of this feature :)

**Comment by soulseekah** [comment]
First iteration is now ready. Please test the feature/duplicate branch: https://github.com/gravityview/GravityView/archive/feature/duplicate.zip

**Comment by soulseekah** [comment]
- [ ] tests
- [ ] pull filters for pre entry creation
- [ ] pull filters for post entry creation

**Comment by vendojo** [comment]
> First iteration is now ready. Please test the feature/duplicate branch: https://github.com/gravityview/GravityView/archive/feature/duplicate.zip

Hi @soulseekah and thanks or the update. I just installed the zip filed you linked to, added the respective 'Duplicate entry' to the list view but the cells of this column are empty. Am I doing something wrong?

**Comment by soulseekah** [comment]
@vendojo Thank you for testing. Make sure you have the appropriate permissions. Empty cells usually mean that you don't have permissions to Edit or Delete either. Can you add a Delete cell, is it empty as well?

**Comment by vendojo** [comment]
@soulseekah No, all the other cells are working fine.

![screenshot-bwe6id myraidbox de-2019 10 27-13_24_11](https://user-images.githubusercontent.com/56757832/67634645-f76b7480-f8be-11e9-8cc0-df68b8fecec3.png)

I'm admin and should have all the necessary permissions. I even manually added the gravityview_duplicate_entry capability as described in this thread's opening comment.

**Comment by soulseekah** [comment]
Are you able to send admin access to support@gravityview.co I'd like to make a copy of the site and debug it locally. Thanks.

**Comment by vendojo** [comment]
> Are you able to send admin access to [support@gravityview.co](mailto:support@gravityview.co) I'd like to make a copy of the site and debug it locally. Thanks.

Done

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/991812008/23129?folderId=408730

**Comment by soulseekah** [comment]
> > Are you able to send admin access to [support@gravityview.co](mailto:support@gravityview.co) I'd like to make a copy of the site and debug it locally. Thanks.
> 
> Done

Thank you. Can you please add the Plugin menu or install UpdraftWP Backups, I'd like to clone the website to my local environment for live debugging.

**Comment by vendojo** [comment]
> > > Are you able to send admin access to [support@gravityview.co](mailto:support@gravityview.co) I'd like to make a copy of the site and debug it locally. Thanks.
> > 
> > 
> > Done
> 
> Thank you. Can you please add the Plugin menu or install UpdraftWP Backups, I'd like to clone the website to my local environment for live debugging.

Ooops, sorry. Still had the White Label CMS plugin activated. Should be working now.

**Comment by soulseekah** [comment]
@vendojo looks like you're running the wrong version of the build, though. I removed your GravityView plugin and activated the `feature/duplicate` branch locally and it shows up well:

![image](https://user-images.githubusercontent.com/685880/67759499-9a9fc380-fa50-11e9-99d5-3dfc94181630.png)

Please take some time to install the branch version properly. Make sure your templates/fields/field-duplicate_entry-html.php file exists. Redownload https://github.com/gravityview/GravityView/archive/feature/duplicate.zip

**Comment by vendojo** [comment]
@soulseekah love it, works without any problems :)

**Comment by vendojo** [comment]
@soulseekah when will this be available in the stable version?

**Comment by soulseekah** [comment]
As with the multipage entries - by the end of November. Cheers. @vendojo
