### ISSUE TITLE
Show only approved entries conflicts with Adv Filters "ANY" mode

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#932]
Having this:

![gv-show-only](https://user-images.githubusercontent.com/1222472/32248032-851a4f30-be6b-11e7-9411-97495cb7ba8d.jpg)

And this:

![gv-adv](https://user-images.githubusercontent.com/1222472/32248036-86d115c0-be6b-11e7-8129-32036aa109ec.jpg)

Results in the first condition here to be met:

![gv -final](https://user-images.githubusercontent.com/1222472/32248129-cbf9c5fc-be6b-11e7-97e2-12e32ffd6480.jpg)

Therefore, displaying all entries on the View.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/458047206/11898?folderId=408730

**Comment by zackkatz** [comment]
This is only possible to fix with Version 2.0— @soulseekah when you're back, let's make sure this works propery. Thanks!

**Comment by soulseekah** [comment]
https://github.com/gravityview/Advanced-Filter/commit/abe6fa0a29ed14b4f86e52d6f949f135e8533b01 fixes this issue as well, as far as I've tested.

**Comment by soulseekah** [comment]
The approval filter forces mode "all" for security reasons. This also conflicts with Search ANY. So while https://github.com/gravityview/Advanced-Filter/commit/abe6fa0a29ed14b4f86e52d6f949f135e8533b01 fixes it for Advanced Filters, it does not for the Search Widget.

Will work this out soon.
