### ISSUE TITLE
Deleting entries mess up with existing advanced filters

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#933]
When deleting an entry from the multiple entries page/table mess up existing Views on the same page set up with advanced filters.

Resulting URL: http://website.com/ideas/?entry_id=1781&gvid=288&view_id=288&delete=a34ac5e5c6&status=deleted

[Edit:] The redirection should remove the `gvid` parameter.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/462502286/11994/

**Comment by soulseekah** [comment]
The gvid parameter is present in the resulting URL.
