### ISSUE TITLE
Enable CodeMirror in Custom Content fields

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#934]
This would make the Custom Content fields more powerful for HTML.

https://make.wordpress.org/core/2017/10/22/code-editing-improvements-in-wordpress-4-9/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656917836351)

**Comment by rafaehlers** [comment]
But we'll also need to allow this by default, right?

```add_filter( 'gravityview/fields/custom/content_after', 'gv_html_entity_decode',10,2 );
function gv_html_entity_decode(){
		return 'html_entity_decode';
}```

**Comment by rafaehlers** [comment]
That's done on GV 2.13.1

![image](https://user-images.githubusercontent.com/1222472/135933741-8a135149-89f5-455c-9d75-a4869baa2762.png)
