### ISSUE TITLE
Some special characters can break the filters

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#935]
A customer commented:

>We create a new view that had filters. One of the filters is based off a multi-select form field. One of the options on the multi-select form field has a / in it. It is the only filter that does not work. It returns back no results but there are results. After you hit the search button no results come back then it deselects the options in the filter.

![gravity_view_filter_issue](https://user-images.githubusercontent.com/1222472/33400253-98070506-d53c-11e7-947d-eeef2ba1e5aa.PNG)

Tested on GV: 1.20

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656586280878)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/477424566/12347/

**Comment by soulseekah** [comment]
The forward slash case is solved in https://github.com/gravityforms/gravityforms/pull/424

The backslash case, not sure yet.

**Comment by soulseekah** [comment]
This was merged into upstream master Nov 14, 2018

Closing.
