### ISSUE TITLE
Support Ultimate Member 2.0

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#939]
[UM Version 2.0](https://github.com/ultimatemember/ultimatemember/commit/9e53314c3a6a51f4385e2f654e9cea607990bcd8) changes how profiles are rendered, causing a fatal error [HS#12410](https://secure.helpscout.net/conversation/479534405/12410).

The [Profile Tabs plugin](https://wordpress.org/plugins/profile-tabs-for-ultimate-member/) hasn't yet been updated to support 2.0; when it is, we should update our code to support it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656929238912)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/506795490/12888/

**Comment by soulseekah** [comment]
I believe this must have been fixed? At least in 90f758efe5a273f55f5e3934a3955fe9c9b72b87 right?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1086086668/25346

**Comment by rafaehlers** [comment]
I believe the issue is related to this:

![image](https://user-images.githubusercontent.com/1222472/74794570-5310a200-52a2-11ea-8ea0-0d5405db9d33.png)

Almost the same thing as the WooCommerce account tabs.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1228591287/28094

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1244597578/28423/

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/GravityView/issues/1451

**Comment by zackkatz** [comment]
`#RafaClose` - We should prioritize WooCommerce Membership instead.
