### ISSUE TITLE
Edit Entry: If Post Title is not in "Edit" View configuration, title will be overwritten as blank

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#942]
This definitely affects post titles, but may also affect other Post Fields.

![](http://share.gravityview.co/ibEcb1/2X9Rs0b0+)

See [HS#12166](https://secure.helpscout.net/conversation/468672677/12166)

--------------

To reproduce: 

- Have a GF form with Post fields
- Create an entry/post "Post 1"
- Configure a View with "Edit Entry" fields not containing the post title
- Edit the entry in GV
- "Post 1" title will now be empty

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656941510103)

**Comment by zackkatz** [comment]
This may have been a Gravity Forms bug—I can no longer reproduce it. @rafaehlers Can you reproduce?

**Comment by soulseekah** [comment]
The Posts fields will be discontinued soon now. The Advanced Post Fields addon is what they're recommending now.

Cannot reproduce.
