### ISSUE TITLE
Edit Entry: Improve Conditional Logic + Calculations

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#943]
When an entry is updated, GravityView currently ignores fields that are hidden by conditional logic, because they are hidden and unset by `unset_hidden_field_values()`.

We need to review conditional logic and Edit Entry to come up with a comprehensive solution.

#689 
#840
https://github.com/gravityview/GravityView/commit/c778a7b293d90f4781790404bdea3e53c27ad31f

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995656939568044)

**Comment by soulseekah** [comment]
We're fine overall.

We have specific issues:

https://github.com/gravityview/GravityView/issues/1295
https://github.com/gravityview/GravityView/issues/941

The rest have been dealt with overall.
