### ISSUE TITLE
Edit Entry not rendering when inside tabs (Membership plugins & Page Builders)

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#946]
- Elementor Page Builder
- Beaver Builder

Renders blank tab content instead of the Edit Entry form.

See UserVoice comment: https://gravityview.uservoice.com/forums/238941-gravityview-ideas/suggestions/33462139-gravityview-compatible-with-tabs
```
Usually you need to create one page per view. But as you can have many tabs in just one page, then you could have many views in just one page: one view per tab.

With this plugin: https://wordpress.org/plugins/tabby-responsive-tabs/ views are shown perfectly in tabs. But problem is when you need to edit an entry, page reloads and tabs do not show nothing anymore.

It would be great and much faster working with views in tabs as you do not need to reload pages to change view because views are actually in the same page.
```

See [HS#12450](https://secure.helpscout.net/conversation/481500914/12450)

**Comment by zackkatz** [comment]
[HS#12518](https://secure.helpscout.net/conversation/485202393/12518?folderId=408730)

**Comment by zackkatz** [comment]
@rafaehlers Is this still true? I just added two Views to a Beaver Builder page, and it worked for me.

The blank content happens still for the Views that aren't being edited (which is expected behavior currently), but the Edit Entry form does appear as it should.

**Comment by rafaehlers** [comment]
@zackkatz it should be tested inside a tab, not a page built with the Visual Editor.

**Comment by zackkatz** [comment]
Yeah I tested it in a tab.

**Comment by soulseekah** [comment]
What's the latest on this, guys? :)

**Comment by soulseekah** [comment]
Bump.

**Comment by zackkatz** [comment]
@rafaehlers @bennemann Please reproduce this on `try`.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1324254804/30048/

**Comment by zackkatz** [comment]
https://github.com/gravityview/GravityView/issues/946

**Comment by rafaehlers** [comment]
Tested with Beaver Builder Plugin (Standard Version) Version 2.3.2.5 and Elementor Version 3.4.4 and all pages of a View worked fine inside a second tab (not shown first). 💯 

Tested with GV 2.13.1
