### ISSUE TITLE
[gvlogic2] issues

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#949]
- [x] If both `[gvlogic]` and `[gvlogic2]` shortcodes both have [else], it doesn't parse properly
- [x] Content after `[gvlogic2]` won't show

```
[gvlogic if="{Text Field:62}" is="Ada"] 
  Match 1
[else]
​  [gvlogic2 if="{Text Field:52}" isnot="Ada"] 
    Match 2
  [else] 
    Match 3
  [/gvlogic2]

  This won't show.
[/gvlogic]
```

Needs unit tests!

[HS#12502](https://secure.helpscout.net/conversation/484150946/12502/?folderId=408730)
[HS#12408](https://secure.helpscout.net/conversation/479390842/12408/?folderId=408735)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995657444337265)

**Comment by artsgirl** [comment]
Ah, this answers why I can't get this to work!

**Comment by soulseekah** [comment]
We should transform it to `else2`. The core shortcode regular expression is probably greedy, nobody knows.

**Comment by soulseekah** [comment]
Fixed. Please test whenever @rafaehlers @jlgrisham 

Thank you.

**Comment by zackkatz** [comment]
@soulseekah This isn't working for me.

This test passes:

```
$value = do_shortcode( '[gvlogic2 if="2" is="3"]2 is 3.[else]2 is NOT three.[/gvlogic2]' );
$this->assertEquals( '2 is NOT three.', $value );
```

But this test fails:

```
$value = do_shortcode( '[gvlogic if="1" is="1"][gvlogic2 if="2" is="3"]2 is 3.[else]2 is NOT three.[/gvlogic2][/gvlogic]' );
$this->assertEquals( '2 is NOT three.', $value );
```

**Comment by soulseekah** [comment]
So I've rewritten the thing from the ground up.

All new and old tests pass.

`[else if` shortcode support is pretty good (update the documentation to talk about the construct!)
Nested support is amazing, we can have triple nesting with gvlogic3 if needed ;) and 4 and so on, as many as anyone needs!

We need some testing, and it can be merged.
