### ISSUE TITLE
Yoast SEO auto-generated descriptions cause widgets not to render on embedded Views

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#956]
The issue is: normally, we'd just check for whether a View is `in_the_loop()` to determine whether or not the widgets should be rendered. Except that Views can be embedded in Text Widgets, and sidebars aren't in the loop!

Yoast SEO plugin pre-runs `the_content` in order to auto-generate description meta tags. This is inside the `wp_head` action.

We've had problems with widgets being rendered multiple times because of things like the Yoast SEO plugin, which is not good either. We need to do a better job of this; it's silly that widgets are being rendered multiple times or not at all.

I'd love for @soulseekah to review this and come up with a recommended solution. My ideas are all obviously pretty bad.

See:

- #806
- [HS#12612](https://secure.helpscout.net/conversation/489580591/12612)
- [HS#7594](https://secure.helpscout.net/conversation/287424884/7594/)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995657945077169)

**Comment by rafaehlers** [comment]
This hasn't been reported anymore.
GV 2.13.1
