### ISSUE TITLE
When Gravity Forms Chained Selects Add-On is used a 500 error happens on GravityView

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#957]
Apparently, GravityView 1.22.3 is not compatible yet with the Gravity Forms Chained Selects Add-On (1.0.3).

When trying to access the Edit Entry page or Single Entry page in a form where this add-on is installed, a 500 error shows up.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/498179604/12717/

**Comment by tunox** [comment]
@rafaehlers Thanks for posting this. It was driving me mad to identify the issue. I have 28 users adding reports on a gravity form with a Chained Selects field. Randomly some of them are getting the http 500 error when trying to modify an exisiting entry. This confirms it.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/520583244/13265/?folderId=408730

**Comment by zackkatz** [comment]
Thanks to the Gravity Forms team, this was fixed in Version 1.0.5 of Chained Selects Addon. 🙏

**Comment by zackkatz** [comment]
FreeScout #45557. <br>https://support.gravitykit.com/conversation/45557?folder_id=4

**Comment by zackkatz** [comment]
FreeScout #45557. <br>https://support.gravitykit.com/conversation/45557?folder_id=4

**Comment by zackkatz** [comment]
FreeScout #45557. <br>https://support.gravitykit.com/conversation/45557?folder_id=4

**Comment by zackkatz** [comment]
FreeScout #45173. <br>https://support.gravitykit.com/conversation/45173?folder_id=4
