### ISSUE TITLE
User Feature Request: Change Post Status & Approval when Entry modified

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#958]
This is a feature request to complement the Front End Post Editing capability that GravityView offers. Some users want the Post Status to change to Draft after the Entry/Post is being edited in GravityView to have some sort of moderation over its contents.

Also, there should be an option to update the entry Approval status when an entry is modified.

- The approval status should only change if the entry is modified by the user; if it's modified by an admin, no need to re-approve

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995657958996169)

**Comment by karolkudla** [comment]
It would be nice to have an activity log. When someone changes the entry - then the data about who, what and when changed the entry. I am starting to search how to do this. If anyone can help - please write a comment.

**Comment by rafaehlers** [comment]
@karolkudla you can use this plugin to send a notification when an entry has been modified: https://gravityplus.pro/gravity-forms-utility/

**Comment by karolkudla** [comment]
Thank you! It will help. I will install it and check how to store changes data in a frontend table.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/517083401/13156?folderId=408730

**Comment by rafaehlers** [comment]
We now have this option built-in:

![image](https://user-images.githubusercontent.com/1222472/135934810-12df9e47-bf5a-4e42-b890-d20ffe5673f9.png)
