### ISSUE TITLE
Version 2.0: PHP warning

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#968]
Context: An embedded View in a post on an archive page.

![](http://share.gravityview.co/tWkUys+)

![](http://share.gravityview.co/q8rTjk+)

**Comment by soulseekah** [comment]
No luck in reproducing this. Seems like something is up with the "fields" in that View.

Can you please:

1. Test on latest 2.0 just in case some oddity in between development rounds was in issue.
2. Dump the `$fields` in _mock.php to see what value is being passed to us.
3. Disable all plugins, themes that may be using that filter and passing a bad `$fields` value to us.

Many thanks.
