### ISSUE TITLE
Version 2.0: Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#969]
PHP warning shown in View Settings box: 

```Warning: Cannot use a scalar value as an array in /app/public/wp-content/plugins/gravityview/includes/admin/class.render.settings.php on line 314```

![Screenshot](http://share.gravityview.co/uXinmz+)

**Comment by soulseekah** [comment]
Same here as in the previous ticket.

1. `var_dump` the `$setting` variable around line 304 in that file, let's see what it contains if not an array.
2. make sure you're running latest 2.0
3. plugins, themes that might be overriding the default settings?

**Comment by zackkatz** [comment]
The `$setting` variable isn't being set as an GV setting array with `name`, `label`, `id`, `tooltip`, etc. It's getting set as the setting value. 

In current `master`, the code is:

```
$setting = GravityView_View_Data::get_default_arg( $key, true );

// If the key doesn't exist, there's something wrong.
if( empty( $setting ) ) { return; }

// If the key doesn't exist, there's something wrong.
if( empty( $setting ) ) { return; }
```
