### ISSUE TITLE
VaultPress reports PHP.Generic.BadPattern.5 on Math plugin

### ISSUE THREAD

**Issue by m-e-h** [gravityview/GravityView#970]
Not sure why it doesn't like `$acc($a(` but letting you know in case you didn't.

![gv_vp](https://user-images.githubusercontent.com/3585901/36215422-130d7e5a-117a-11e8-80c2-55c4c6aa17dc.png)

**Comment by soulseekah** [comment]
Thanks. It is indeed very common in obfuscated PHP backdoors. However this is a third-party library that's being used inside the extension, so this issue has to be raised upstream at https://github.com/hoaproject/Math
