### ISSUE TITLE
Namespace `EDD_SL_Plugin_Updater` class

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#971]
May be causing issues with the plugin not updating properly due to conflicts with other plugins running the `EDD_SL_Plugin_Updater` class.

See https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1066

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/509744915/12957?folderId=408736

**Comment by soulseekah** [comment]
Closed in 208f385a109414fa33dbcf328bd008e1f9eeed1c
