### ISSUE TITLE
Joins: `$gravityview->entries->count()` should return empty but it's not

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#975]
Steps to reproduce: 

- Create a View connected to a form with no entries
- Join with another form with no entries
- Look at the View

What should happen: 

- The `gv_no_results()` function should print, since `$gravityview->entries->count()` should return false

What does happen: 

- `$gravityview->entries->count()` returns `1`

-----

It seems like the Entry Collection has an entry…it's just hydrated with `null`!

![Entry Collection](http://share.gravityview.co/whZjt3+)

**Comment by soulseekah** [comment]
This is on the feature/joins branch, yes? If so can't reproduce.

![image](https://user-images.githubusercontent.com/685880/36900663-05dfaea0-1e46-11e8-9f16-e75528c34c55.png)
