### ISSUE TITLE
Sort by Date field when using Drop Down style

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#983]
When we have a Date field set up as a Drop Down like this one:

![gv-date-bug](https://user-images.githubusercontent.com/1222472/37853236-788d01f8-2ec4-11e8-81e6-21c27d87d8d3.jpg)

There's no way to sort by the whole date field:

![gv-date-bug1](https://user-images.githubusercontent.com/1222472/37853265-9fc1a49a-2ec4-11e8-9677-4d8a134b6d14.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995660170882256)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/547330757/13891/

**Comment by rafaehlers** [comment]
Workaround: 

>you can bypass that problem by specifying which field you want to sort by using the sort_field and sort_direction methods of the [gravityview] shortcode: Using the [gravityview] Shortcode
That way, you just need to specify the ID of the Date field on your form.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/840878795/20449/

**Comment by rafaehlers** [comment]
Somewhat related: https://github.com/gravityview/Advanced-Filter/issues/73

**Comment by soulseekah** [comment]
Similar to #1230

**Comment by soulseekah** [comment]
Please test. Should be good to go.

**Comment by jlgrisham** [comment]
Whole date sorting good to go.
