### ISSUE TITLE
Add a Result Number field to display a the current row number

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#984]
Some users would like to use their Views as leaderboard, then we need to include an option to display an additional column to the View to indicate the row number.

This would add a GravityView field named "Result Number" that would output the current entry's result number across multiple pages. 

It would start counting from 1; the first result on the second page of a 25-entries-per-page layout would be 26.

- [ ] Add Result Number field
- [ ] Add Merge Tag or shortcode so that it's able to be used in GV Custom Content field
- [ ] Write tests
- [ ] Make sure it works in CSV output

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995660205809381)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/548935855/13911/?folderId=408735

**Comment by zackkatz** [comment]
This seems like low-hanging fruit. Another customer approached me about this at WordCamp Miami.

**Comment by soulseekah** [comment]
I don't think we can have a `{sequence}` merge tag, unfortunately. The context is not passed into merge tags, which means that we have no idea what the context around is. It's a different problem. So let's hold on the merge tag for now.

**Comment by zackkatz** [comment]
Makes sense—a field is good.

**Comment by soulseekah** [comment]
Just need to finish up on the single view tests and we can merge in a bit. Exciting.
