### ISSUE TITLE
Hydrating \GV\Entry_Collection results in lots of queries

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#985]
There are 112 matches of `SELECT * from wp_gf_entry WHERE id = 6` on a page with 10 entries. Same with all the entry IDs. I think the entry storage system isn't working.

> `require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/gravityformstheme/single-gravityview.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, GV\View::content, GV\View_Renderer->render, GV\View_Template->render, Gamajo_Template_Loader->get_template_part, Gamajo_Template_Loader->locate_template, load_template, require('/plugins/gravityview-diy/templates/views/diy.php'), GV\View_DIY_Template->the_field, GV\Template_Context::from_template, GV\Entry_Collection->fetch, GV\GF_Form->GV\{closure}, GFAPI::get_entries, GF_Query->get, GF_Query->get_entry`

**Comment by zackkatz** [comment]
For some reason, `$this->count()` doesn't correctly return the size of the `\GV\Collection` array of entries (10). 

![](http://share.gravityview.co/IlU6CN+)

**Comment by zackkatz** [comment]
For example, there are six of these queries being performed: 

```
SELECT * from wp_gf_entry WHERE id = 23406
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/themedd/single.php'), get_template_part, locate_template, load_template, require('/themes/themedd/template-parts/content-single.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, GV\View::content, GV\View_Renderer->render, GV\View_Template->render, Gamajo_Template_Loader->get_template_part, Gamajo_Template_Loader->locate_template, load_template, require('/plugins/gravityview/templates/views/table.php'), Gamajo_Template_Loader->get_template_part, Gamajo_Template_Loader->locate_template, load_template, require('/plugins/gravityview/templates/views/table/table-header.php'), GV\View_Table_Template->the_columns, GV\Template_Context::from_template, GV\Entry_Collection->fetch, GV\GF_Form->GV\{closure}, GFAPI::get_entries, GF_Query->get, GF_Query->get_entry
```

And six of these: 

```
SELECT meta_key, meta_value from wp_gf_entry_meta WHERE entry_id = 23406
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/themedd/single.php'), get_template_part, locate_template, load_template, require('/themes/themedd/template-parts/content-single.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, GV\View::content, GV\View_Renderer->render, GV\View_Template->render, Gamajo_Template_Loader->get_template_part, Gamajo_Template_Loader->locate_template, load_template, require('/plugins/gravityview/templates/views/table.php'), Gamajo_Template_Loader->get_template_part, Gamajo_Template_Loader->locate_template, load_template, require('/plugins/gravityview/templates/views/table/table-header.php'), GV\View_Table_Template->the_columns, GV\Template_Context::from_template, GV\Entry_Collection->fetch, GV\GF_Form->GV\{closure}, GFAPI::get_entries, GF_Query->get, GF_Query->get_entry
```

I think this is a serious performance issue with 2.0…Can you check this out, @soulseekah ?

**Comment by soulseekah** [comment]
Absolutely, working on this and will update ASAP

**Comment by soulseekah** [comment]
1 view, 6 displayed entries, 4 columns. 24 calls to `View_Renderer::the_field` a crapton of overhead, 24 calls to context which is pretty expensive as well. Object caching is not working somewhere it seems.

![image](https://user-images.githubusercontent.com/685880/38013708-8ba0716c-327f-11e8-8fa7-d4bca85f33b7.png)

Optimization is due.

**Comment by zackkatz** [comment]
That looks like it! I was staring it right in the face, wondering “why are you doing this!?” But I’m glad you realized it didn’t need to!

**Comment by zackkatz** [comment]
I'd say it's fixed.

<img width="735" alt="screen shot 2018-03-28 at 8 32 33 am" src="https://user-images.githubusercontent.com/870979/38035890-a5897c94-3262-11e8-8f47-c6aa169c4a0a.png">
<img width="712" alt="screen shot 2018-03-28 at 8 32 11 am" src="https://user-images.githubusercontent.com/870979/38035891-a5a03c0e-3262-11e8-8d8f-023506d164d3.png">

**Comment by soulseekah** [comment]
> That looks like it! I was staring it right in the face, wondering “why are you doing this!?” But I’m glad you realized it didn’t need to!

Right, there was a breaking change in the collections objects where `fetch()` would reset the collection, so we ended up with a crapton of resets.

The more substantial change came from caching `View::from_post` actually, though, since that does a lot more overhead. Glad it works well. Tests are passing, too.
