### ISSUE TITLE
Download Multiple Files

### ISSUE THREAD

**Issue by cbrcongit** [gravityview/GravityView#990]
Having an entry view of downloads, displayed as individual links, is a painful UX to download multiple files through...
+ Long
+ Lists
+ of Links
+ are Losing
+ my Love

Please [take this as a start](https://github.com/cbrcongit/Gravityview-jszip-fileuploads), and as a huge thanks for developing so much functionality already.

![JSzip FileUploads Single Entry template](https://github.com/cbrcongit/Gravityview-jszip-fileuploads/raw/master/gravity-zip.png)

Hoping you can take over and label `In Progress` ASAP.
Cheers mate :1st_place_medal: :+1:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995660977138678)

**Comment by rafaehlers** [comment]
This will need new functionality to .zip all uploaded files on the server and then display a link to this .zip dynamically on the View. This functionality hasn't been requested again.
