### ISSUE TITLE
Can't search for single day using date range on Search Bar

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#992]
![gv-date-range](https://user-images.githubusercontent.com/1222472/38443589-95e12d16-39c2-11e8-959c-a2d3c7798c01.jpg)

![gv-date-range-2](https://user-images.githubusercontent.com/1222472/38443612-ac7b91f6-39c2-11e8-9833-fe56d8122fed.jpg)

When performing a search for the same day in a date range field (select the option "Date Range" for a Date field in the Search Bar), nothing is returned. 

Here's the log for that type of query/search where we think the 5 hour time is breaking it:

```2018-04-05 22:36:31.916054 - DEBUG --> 'GravityView_Widget_Search[filter_entries] Returned Search Criteria: 'array (
  'field_filters' => 
  array (
    'mode' => 'all',
  ),
  'start_date' => '2018-04-04 05:00:00',
  'end_date' => '2018-04-04 05:00:00',
) ```

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/554677708/14014/

**Comment by soulseekah** [comment]
End date is now always 24 hours ahead to INCLUDE it.
