### ISSUE TITLE
Edit entry: update button won't work

### ISSUE THREAD

**Issue by jasmines** [gravityview/GravityView#993]
When I try to update an entry, the update button won't do anything... If I watch the console, a strange call to facebook occurs:

Request URL: https://www.facebook.com/tr/
Request Method: POST
Status Code: 200 
Referrer Policy: no-referrer-when-downgrade
content-length: 0
content-type: text/plain
date: Sat, 07 Apr 2018 20:28:33 GMT
server: proxygen-bolt
status: 200
:authority: www.facebook.com
:method: POST
:path: /tr/
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,es;q=0.5
cache-control: no-cache
content-length: 4545
content-type: application/x-www-form-urlencoded
dnt: 1
origin: https://icostart.ch
pragma: no-cache
referer: https://mydomain.com/view/kyc-view/entry/12188/?edit=38335550a2
save-data: on
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36
id: 273922613129216
ev: SubscribedButtonClick
dl: https://icostart.ch/view/kyc-view/entry/12188/?edit=38335550a2
rl: https://icostart.ch/view/kyc-view/
if: false
ts: 1523132913529
cd[buttonText]: Update
cd[buttonFeatures]: {"name":"save","id":"gform_submit_button_1","tag":"input","classList":"btn btn-lg button button-large gform_button button-primary gv-button-update","value":"Update","innerText":"","numChildButtons":0,"destination":""}
cd[formFeatures]: [{"name":"edit_17911_1_12188","id":"edit_17911_1_12188","tag":"input","inputType":"hidden"},{"name":"_wp_http_referer","id":"","tag":"input","inputType":"hidden"},{"name":"is_gv_edit_entry","id":"is_gv_edit_entry","tag":"input","inputType":"hidden"},{"name":"input_2","id":"input_1_2","tag":"input","inputType":"text"},{"name":"input_2_2","id":"input_1_2_2","tag":"input","inputType":"text"},{"name":"input_1.3","id":"input_1_1_3","tag":"input","inputType":"text"},{"name":"input_1.6","id":"input_1_1_6","tag":"input","inputType":"text"},{"name":"input_25","id":"input_1_25","tag":"input","inputType":"text"},{"name":"","id":"gforms_calendar_icon_input_1_25","tag":"input","inputType":"hidden"},{"name":"input_11","id":"input_1_11","tag":"input","inputType":"text"},{"name":"input_13","id":"input_1_13","tag":"input","inputType":"text"},{"name":"input_21","id":"choice_1_21_0","tag":"input","inputType":"radio"},{"name":"input_21","id":"choice_1_21_1","tag":"input","inputType":"radio"},{"name":"input_21","id":"choice_1_21_2","tag":"input","inputType":"radio"},{"name":"","id":"gform_browse_button_1_8","tag":"input","inputType":"button"},{"name":"","id":"html5_1cagsn51clqktr47ai1mdu1kg33","tag":"input","inputType":"file"},{"name":"input_8","id":"","tag":"input","inputType":"hidden"},{"name":"","id":"gform_browse_button_1_9","tag":"input","inputType":"button"},{"name":"","id":"html5_1cagsn51gqfe1dbfapa19i7ho16","tag":"input","inputType":"file"},{"name":"input_9","id":"","tag":"input","inputType":"hidden"},{"name":"input_6","id":"input_1_6","tag":"input","inputType":"text"},{"name":"input_27","id":"input_1_27","tag":"select"},{"name":"action","id":"","tag":"input","inputType":"hidden"},{"name":"lid","id":"","tag":"input","inputType":"hidden"},{"name":"_gform_submit_nonce_1","id":"_gform_submit_nonce_1","tag":"input","inputType":"hidden"},{"name":"_wp_http_referer","id":"","tag":"input","inputType":"hidden"},{"name":"is_submit_1","id":"","tag":"input","inputType":"hidden"},{"name":"gform_submit","id":"","tag":"input","inputType":"hidden"},{"name":"gform_unique_id","id":"","tag":"input","inputType":"hidden"},{"name":"state_1","id":"","tag":"input","inputType":"hidden"},{"name":"gform_target_page_number_1","id":"gform_target_page_number_1","tag":"input","inputType":"hidden"}]
sw: 1366
sh: 768
v: 2.8.12
r: stable
ec: 2
o: 30
it: 1523132895722

And obviously nothing happens.

**Comment by soulseekah** [comment]
Thanks for your report! Seems like something is overriding the POST URL. Please contact https://gravityview.co/support/ for help debugging this. The ticket will be reopened by a member of our staff if this is a bug inherent to GravityView.
