### ISSUE TITLE
Add a filter to globally prevent all CSS styles from being loaded

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#994]
The only possible solution at this moment is by using this trick: https://docs.gravityview.co/article/456-prevent-gravityview-from-loading-its-css-styles

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995660988387360)

**Comment by soulseekah** [comment]
https://secure.helpscout.net/conversation/833341854/20321/

https://docs.gravityview.co/article/575-how-to-remove-all-styles-and-scripts-of-gravityview-from-your-website

**Comment by rafaehlers** [comment]
Easily achievable with that DOC above.
