### ISSUE TITLE
2.0: Cannot embed [gravityview] shortcode in Custom Content

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#996]
It should be possible to embed View 2 inside View 1 using a shortcode.

Currently, that doesn't appear possible.

```
$current_view = $request->is_view();

$is_current_view = ( $current_view->ID === $view->ID );
```

Possible solution coming, but we need a bunch of unit tests. Can you help, @soulseekah?

**Comment by soulseekah** [comment]
Is this Falcon-related? Or just a customer request?

**Comment by zackkatz** [comment]
@soulseekah Falcon but also commonly done

**Comment by soulseekah** [comment]
So I tried this out, seems to work well, though (and I'd expect it to really, since there shouldn't be any global context, I really want to believe):

![image](https://user-images.githubusercontent.com/685880/39068295-4844ec9e-44f5-11e8-9cba-f7eab0e06ac5.png)

What doesn't work in your case?

**Comment by zackkatz** [comment]
Yes, multiple entries works great. Single entry context doesn’t work at all because of the code.

**Comment by soulseekah** [comment]
Okay, getting closer :) will test single entry next.

**Comment by soulseekah** [comment]
Added commit https://github.com/gravityview/GravityView/commit/3943669c0d3716edb43d365ab0d7f42cfcd26cab

It builds on your idea, but only behaves as edit/single if it's detected as non-embedded. The rest of the cases it will only display in directory-mode. Also mocks the request to the correct view in the renderer.

Give it a spin on Falcon.

**Comment by soulseekah** [comment]
Comes with bugs. Tests failing (which is great, hurray unit tests). Figuring it out...
