### ISSUE TITLE
Entry Notes are not visible

### ISSUE THREAD

**Issue by pareshmithra** [gravityview/GravityView#999]
Hi Team,
We created a page with login for entering the entry notes. After entering Entry notes, if we refresh the page the notes are not displaying. If we logout and login again the notes are visible. Can you please let us know how to display the notes in real-time.?
Thanks in advance,

- Paresh

**Comment by rafaehlers** [comment]
@pareshmithra Please submit a support ticket and we'll check that for you: https://gravityview.co/support/

This is not the place to ask support questions.
